export const COMMUNITY_PRIVACY_GUARD_CONTRACT = {
  version: '2026-06-28.community-privacy-guard.v1',
  publicFollowerProfile: {
    surfaces: [
      'GET /api/v1/users/:userId/followers',
      'GET /api/v1/users/:userId/following-users',
      'GET /api/v1/users/handle/:publicHandle/followers',
      'GET /api/v1/users/handle/:publicHandle/following-users',
    ],
    sourceOfTruth: ['user_follows', 'users', 'user_profiles', 'user_blocks'],
    targetProfileRequired: {
      userStatus: 'active',
      userDeletedAt: null,
      publicHandleRequired: true,
      viewerBlockedEitherDirection: false,
    },
    returnedRowsWhere: {
      followStatus: 'active',
      followDeletedAt: null,
      sourceUserStatus: 'active',
      targetUserStatus: 'active',
      sourceUserDeletedAt: null,
      targetUserDeletedAt: null,
      activeBlockEitherDirection: false,
    },
    countUsesSameWhereAsItems: true,
    hiddenStatuses: ['deleted', 'suspended', 'inactive', 'private'],
    stableErrors: {
      targetNotFound: {
        status: 404,
        code: 'USER_NOT_FOUND',
        messageKey: 'social.user.notFound',
      },
      blockedTarget: {
        status: 403,
        code: 'USER_PROFILE_BLOCKED',
        messageKey: 'social.profile.blocked',
      },
    },
    privateFieldsReturned: {
      rawEmail: false,
      phone: false,
      providerIds: false,
      walletAccounts: false,
      walletLedger: false,
      paymentOrders: false,
      adminNotes: false,
      blockReason: false,
      rawUserIdFromQaNotes: false,
    },
    mutation: false,
  },
  accountProviderParity: {
    providers: ['email', 'google', 'kakao', 'naver', 'apple'],
    relationProjectionSource: [
      'users.id',
      'users.status',
      'users.deletedAt',
      'user_profiles.publicHandle',
      'user_follows',
      'user_blocks',
    ],
    providerSpecificBranches: false,
    rawEmailReturned: false,
    providerUserIdReturned: false,
    socialAccountRowsReturned: false,
    passwordHashReturned: false,
    samePrivacyRulesForSocialAndEmail: true,
  },
  accountLifecycleExclusion: {
    excludedStatuses: ['deleted', 'suspended', 'inactive'],
    deletedAtRequiredNull: true,
    surfaces: [
      'followers',
      'following',
      'profile_relation_entry',
      'feed_author_link',
      'feed_author_profile_handoff',
    ],
    filterBefore: ['pagination', 'counts', 'linkRendering'],
    stableFallback: {
      status: 404,
      code: 'USER_NOT_FOUND',
      messageKey: 'social.user.notFound',
    },
    mutation: false,
  },
  qaHandleNamespace: {
    prefix: 'qa-fb-',
    allowedUse: 'approved_disposable_fixture_rows_only',
    normalUserSignupAllowed: false,
    normalUserHandleUpdateAllowed: false,
    collisionCheckSource: 'user_profiles.publicHandle',
    confirmedRunValueRecording: false,
    allowedReportFields: [
      'runId',
      'fixtureStatus',
      'publicProfileHandle',
      'publicProfilePath',
      'publicProfileApiPath',
      'followersApiPath',
      'followingApiPath',
      'blockApiPath',
      'followerPublicHandle',
    ],
  },
  blockVisibility: {
    sourceOfTruth: 'user_blocks',
    activeBlockWhere: {
      status: 'active',
      deletedAt: null,
      direction: 'either_direction',
    },
    hiddenSurfaces: [
      'feed',
      'comments',
      'replies',
      'followers',
      'following',
      'profile_relation_entry',
      'notifications',
    ],
    filteringRules: {
      excludeBlockedAuthorsBeforePagination: true,
      excludeBlockedRepliesBeforeCount: true,
      excludeBlockedFollowRowsBeforeCount: true,
      tombstoneInsteadOfIdentityLeak: true,
      countsUseFilteredRows: true,
    },
    stableErrors: {
      blockedProfile: {
        status: 403,
        code: 'USER_PROFILE_BLOCKED',
        messageKey: 'social.profile.blocked',
      },
    },
    privateFieldsReturned: {
      blockedUserEmail: false,
      blockerUserEmail: false,
      blockReason: false,
      moderationNotes: false,
      walletFields: false,
      paymentFields: false,
      rawRelationshipId: false,
    },
    mutation: false,
  },
} as const;
