export const COMMUNITY_PRIVACY_GUARD_CONTRACT = {
  version: '2026-06-28.community-privacy-guard.v1',
  publicFollowerProfile: {
    surfaces: [
      'GET /api/v1/users/:userId/followers',
      'GET /api/v1/users/:userId/following-users',
      'GET /api/v1/users/handle/:publicHandle/followers',
      'GET /api/v1/users/handle/:publicHandle/following-users',
    ],
    sourceOfTruth: ['user_follows', 'users', 'user_profiles', 'user_blocks'],
    targetProfileRequired: {
      userStatus: 'active',
      userDeletedAt: null,
      publicHandleRequired: true,
      viewerBlockedEitherDirection: false,
    },
    returnedRowsWhere: {
      followStatus: 'active',
      followDeletedAt: null,
      sourceUserStatus: 'active',
      targetUserStatus: 'active',
      sourceUserDeletedAt: null,
      targetUserDeletedAt: null,
      activeBlockEitherDirection: false,
    },
    countUsesSameWhereAsItems: true,
    hiddenStatuses: ['deleted', 'suspended', 'inactive', 'private'],
    stableErrors: {
      targetNotFound: {
        status: 404,
        code: 'USER_NOT_FOUND',
        messageKey: 'social.user.notFound',
      },
      blockedTarget: {
        status: 403,
        code: 'USER_PROFILE_BLOCKED',
        messageKey: 'social.profile.blocked',
      },
    },
    privateFieldsReturned: {
      rawEmail: false,
      phone: false,
      providerIds: false,
      walletAccounts: false,
      walletLedger: false,
      paymentOrders: false,
      adminNotes: false,
      blockReason: false,
      rawUserIdFromQaNotes: false,
    },
    mutation: false,
  },
  blockVisibility: {
    sourceOfTruth: 'user_blocks',
    activeBlockWhere: {
      status: 'active',
      deletedAt: null,
      direction: 'either_direction',
    },
    hiddenSurfaces: [
      'feed',
      'comments',
      'replies',
      'followers',
      'following',
      'profile_relation_entry',
      'notifications',
    ],
    filteringRules: {
      excludeBlockedAuthorsBeforePagination: true,
      excludeBlockedRepliesBeforeCount: true,
      excludeBlockedFollowRowsBeforeCount: true,
      tombstoneInsteadOfIdentityLeak: true,
      countsUseFilteredRows: true,
    },
    stableErrors: {
      blockedProfile: {
        status: 403,
        code: 'USER_PROFILE_BLOCKED',
        messageKey: 'social.profile.blocked',
      },
    },
    privateFieldsReturned: {
      blockedUserEmail: false,
      blockerUserEmail: false,
      blockReason: false,
      moderationNotes: false,
      walletFields: false,
      paymentFields: false,
      rawRelationshipId: false,
    },
    mutation: false,
  },
} as const;
