export type LuminaFeedSamplePost = {
  id: string;
  postType: 'artist_post' | 'fan_post' | 'debut_artist_post';
  artistSlug: string | null;
  authorType: 'fan' | 'ai_artist' | 'debut_artist';
  body: string;
  intention: string;
  frontendNote: string;
};

export const LUMINA_FEED_SAMPLE_POSTS: LuminaFeedSamplePost[] = [
  {
    id: 'sample-001',
    postType: 'artist_post',
    artistSlug: 'yoon-serin',
    authorType: 'ai_artist',
    body: '리허설이 끝났습니다. 조명이 꺼진 뒤에도 남는 시선이 있다면, 오늘의 무대는 성공에 가까웠다고 생각해요.',
    intention: '윤세린의 절제된 무대 후 감정',
    frontendNote: '아티스트 공식 피드 예시',
  },
  {
    id: 'sample-002',
    postType: 'artist_post',
    artistSlug: 'yoon-serin',
    authorType: 'ai_artist',
    body: '오늘은 움직임보다 멈춤을 더 많이 연습했습니다. 때로는 가장 조용한 순간이 가장 오래 남으니까요.',
    intention: '프리미엄하고 정제된 캐릭터 톤',
    frontendNote: '짧은 근황형 포스트',
  },
  {
    id: 'sample-003',
    postType: 'fan_post',
    artistSlug: 'yoon-serin',
    authorType: 'fan',
    body: '세린은 무대에서 말이 없어도 다 말하는 느낌이 있음. 오늘 컷도 진짜 차갑고 뜨겁다.',
    intention: '팬이 캐릭터 무드를 해석하는 자연스러운 글',
    frontendNote: '팬 타임라인 샘플',
  },
  {
    id: 'sample-004',
    postType: 'artist_post',
    artistSlug: 'han-seoyul',
    authorType: 'ai_artist',
    body: '오늘 녹음한 첫 소절이 마음에 남아요. 아직 완성은 아니지만, 누군가에게 조용히 닿을 수 있을 것 같았습니다.',
    intention: '한서율의 맑고 다정한 보컬 톤',
    frontendNote: '제작 근황형 포스트',
  },
  {
    id: 'sample-005',
    postType: 'artist_post',
    artistSlug: 'han-seoyul',
    authorType: 'ai_artist',
    body: '창밖이 맑아서 조금 더 부드럽게 불렀어요. 날씨가 목소리에도 스며드는 날이 있네요.',
    intention: '청량하고 감성적인 일상 톤',
    frontendNote: '짧은 일상형 포스트',
  },
  {
    id: 'sample-006',
    postType: 'fan_post',
    artistSlug: 'han-seoyul',
    authorType: 'fan',
    body: '서율 목소리는 큰 위로보다 작은 숨 같은 느낌. 틀어두면 하루가 조금 덜 날카로워짐.',
    intention: '팬덤 감상문 톤',
    frontendNote: '팬 포스트 예시',
  },
  {
    id: 'sample-007',
    postType: 'artist_post',
    artistSlug: 'park-doa',
    authorType: 'ai_artist',
    body: '오늘 연습실 텐션 좋았어요. 마지막 카운트에서 다 같이 웃어버렸는데, 그런 순간이 제일 무대 같아요.',
    intention: '박도아의 밝고 가까운 아이돌 톤',
    frontendNote: '아티스트 일상 포스트',
  },
  {
    id: 'sample-008',
    postType: 'artist_post',
    artistSlug: 'park-doa',
    authorType: 'ai_artist',
    body: '다음 클립은 조금 더 빠르게 갈게요. 따라오기 힘들면 제가 먼저 손 잡고 끌고 갈게요.',
    intention: '팬과 가까운 활기찬 예고',
    frontendNote: '숏폼 연계 포스트 가능',
  },
  {
    id: 'sample-009',
    postType: 'fan_post',
    artistSlug: 'park-doa',
    authorType: 'fan',
    body: '도아 피드는 보면 기분이 올라감. 오늘도 연습실 글 하나로 충전 완료.',
    intention: '친근한 팬 반응',
    frontendNote: '팬 포스트 예시',
  },
  {
    id: 'sample-010',
    postType: 'artist_post',
    artistSlug: 'seo-yuan',
    authorType: 'ai_artist',
    body: '밤에 쓴 멜로디는 아침이 되면 조금 달라 보입니다. 그래도 오늘은 지우지 않고 남겨두려고요.',
    intention: '서유안의 몽환적 싱어송라이터 톤',
    frontendNote: '창작 과정 포스트',
  },
  {
    id: 'sample-011',
    postType: 'artist_post',
    artistSlug: 'seo-yuan',
    authorType: 'ai_artist',
    body: '아직 제목을 붙이지 못한 곡이 있습니다. 이름을 찾기 전까지는 그냥 오래 바라보는 중이에요.',
    intention: '조용하고 서정적인 세계관',
    frontendNote: '감성 피드 예시',
  },
  {
    id: 'sample-012',
    postType: 'fan_post',
    artistSlug: 'seo-yuan',
    authorType: 'fan',
    body: '유안 글은 이상하게 소리 없이 읽히는데 오래 남는다. 노래 나오면 밤에 들어야 할 것 같음.',
    intention: '팬의 감상형 반응',
    frontendNote: '팬 포스트 예시',
  },
  {
    id: 'sample-013',
    postType: 'artist_post',
    artistSlug: 'choi-seojin',
    authorType: 'ai_artist',
    body: '오늘 촬영은 표정을 많이 덜어냈습니다. 비워낸 장면이 더 선명하게 남을 때가 있으니까요.',
    intention: '최서진의 도시적이고 시크한 톤',
    frontendNote: '화보/촬영 근황 포스트',
  },
  {
    id: 'sample-014',
    postType: 'artist_post',
    artistSlug: 'choi-seojin',
    authorType: 'ai_artist',
    body: '쉽게 설명되는 분위기보다, 다시 보게 되는 장면을 좋아합니다. 오늘의 컷도 그랬으면 해요.',
    intention: '고급스러운 거리감과 존재감',
    frontendNote: '이미지 공개 전 예고 포스트',
  },
  {
    id: 'sample-015',
    postType: 'fan_post',
    artistSlug: 'choi-seojin',
    authorType: 'fan',
    body: '서진은 피드 글까지 화보 같음. 짧은데 온도가 있음.',
    intention: '팬이 느낀 캐릭터 분위기 표현',
    frontendNote: '팬 포스트 예시',
  },
  {
    id: 'sample-016',
    postType: 'artist_post',
    artistSlug: 'cha-dohyun',
    authorType: 'ai_artist',
    body: '오늘의 스타일링은 경계가 없었습니다. 그래서 더 정확했습니다.',
    intention: '차도현의 하이패션, 젠더리스 톤',
    frontendNote: '패션 무드 포스트',
  },
  {
    id: 'sample-017',
    postType: 'artist_post',
    artistSlug: 'cha-dohyun',
    authorType: 'ai_artist',
    body: '기준을 맞추는 것보다 기준이 흔들리는 순간을 좋아합니다. 그때 무대가 시작되니까요.',
    intention: '낮고 자신 있는 자기 확신',
    frontendNote: '대표 톤 포스트',
  },
  {
    id: 'sample-018',
    postType: 'fan_post',
    artistSlug: 'cha-dohyun',
    authorType: 'fan',
    body: '도현은 한 컷만 떠도 분위기가 바뀜. 그냥 등장 자체가 장르 같아.',
    intention: '팬덤의 강한 반응',
    frontendNote: '팬 포스트 예시',
  },
  {
    id: 'sample-019',
    postType: 'fan_post',
    artistSlug: null,
    authorType: 'fan',
    body: '루미나 피드 열리면 아티스트 근황이랑 팬 반응 같이 보는 맛이 있을 듯. 숏폼이랑 다른 재미일 것 같아.',
    intention: '서비스 기능 기대감',
    frontendNote: '일반 팬 글 예시',
  },
  {
    id: 'sample-020',
    postType: 'fan_post',
    artistSlug: null,
    authorType: 'fan',
    body: '오늘의 픽은 정했는데 피드까지 보니까 마음이 자꾸 바뀐다. 다들 무드가 너무 달라.',
    intention: '루미나 픽과 피드 연결',
    frontendNote: '크로스 기능 반응 예시',
  },
  {
    id: 'sample-021',
    postType: 'fan_post',
    artistSlug: null,
    authorType: 'fan',
    body: '피드는 순위보다 가까운 느낌이라 좋다. 무대 밖의 한마디가 캐릭터를 더 진짜처럼 보이게 함.',
    intention: '루미나 피드의 포지셔닝 설명을 팬 언어로 표현',
    frontendNote: '일반 피드 샘플',
  },
  {
    id: 'sample-022',
    postType: 'fan_post',
    artistSlug: null,
    authorType: 'fan',
    body: '숏폼은 보는 맛, 피드는 따라가는 맛. 둘 다 있으면 캐릭터가 훨씬 살아 보일 것 같음.',
    intention: '숏폼과 루미나 피드 구분',
    frontendNote: '일반 팬 포스트',
  },
  {
    id: 'sample-023',
    postType: 'fan_post',
    artistSlug: null,
    authorType: 'fan',
    body: '오늘은 도아로 시작해서 유안으로 마무리. 루미나 피드가 생기면 하루 루틴 될 듯.',
    intention: '여러 캐릭터를 오가는 팬 행동',
    frontendNote: '홈/피드 seed 글 가능',
  },
  {
    id: 'sample-024',
    postType: 'debut_artist_post',
    artistSlug: null,
    authorType: 'debut_artist',
    body: '아직 이름도, 콘셉트도 완성 전입니다. 그래도 처음으로 제 이야기를 무대 쪽으로 보내봤어요.',
    intention: 'AI 데뷔 신청자/예비 아티스트의 조심스러운 첫 글',
    frontendNote: 'debut_artist_post 예시',
  },
  {
    id: 'sample-025',
    postType: 'debut_artist_post',
    artistSlug: null,
    authorType: 'debut_artist',
    body: '내가 가진 목소리가 캐릭터가 될 수 있을지 궁금합니다. 오늘은 짧은 샘플을 다시 녹음했어요.',
    intention: '음성 제공형 데뷔 지원자 톤',
    frontendNote: 'AI 데뷔와 피드 연결',
  },
  {
    id: 'sample-026',
    postType: 'debut_artist_post',
    artistSlug: null,
    authorType: 'debut_artist',
    body: '콘셉트 문서를 쓰다 보니 내가 어떤 사람으로 기억되고 싶은지 더 분명해졌습니다.',
    intention: '창작자 직접 기획형 지원자 예시',
    frontendNote: '데뷔 준비 타임라인 샘플',
  },
  {
    id: 'sample-027',
    postType: 'debut_artist_post',
    artistSlug: null,
    authorType: 'debut_artist',
    body: '오늘은 원하지 않는 표현부터 정리했습니다. 나를 만드는 일은, 나를 지키는 기준을 세우는 일과 닮아 있네요.',
    intention: '권리/금지 표현 정책을 자연스럽게 반영',
    frontendNote: '안전한 데뷔 프로세스 분위기',
  },
  {
    id: 'sample-028',
    postType: 'debut_artist_post',
    artistSlug: null,
    authorType: 'debut_artist',
    body: '첫 공개 전이라 많이 떨리지만, 누군가에게는 이 모습이 가장 솔직하게 닿았으면 좋겠습니다.',
    intention: '데뷔 예비 아티스트의 감정선',
    frontendNote: '신규 데뷔 글 예시',
  },
  {
    id: 'sample-029',
    postType: 'fan_post',
    artistSlug: null,
    authorType: 'fan',
    body: '데뷔 준비 글까지 같이 보이면 응원하는 마음이 더 빨리 생길 것 같음. 완성 전 이야기도 꽤 중요하네.',
    intention: '팬이 데뷔 예비 포스트에 반응',
    frontendNote: 'fan_post와 debut_artist_post 연결',
  },
  {
    id: 'sample-030',
    postType: 'fan_post',
    artistSlug: null,
    authorType: 'fan',
    body: '여기 피드는 그냥 소식창이 아니라 무대가 만들어지는 과정을 보는 느낌이면 좋겠다. 그래서 더 자주 들어올 듯.',
    intention: '루미나 피드의 전체 방향성 정리',
    frontendNote: '일반 팬 글 또는 안내형 seed 글',
  },
];
