export const STORY_AUTHOR_SETTLEMENT_PENALTY_REASONS = [
  'none',
  'long_hiatus',
  'serialization_stopped',
  'operator_review',
] as const;

export const STORY_AUTHOR_SETTLEMENT_RATE_PENALTY_READ_MODEL = {
  version: '2026-06-19.story-author-settlement-rate-penalty.v1',
  feature: 'story_author_settlement_rate_penalty_read_model',
  status: 'read_model_contract_only',
  enabled: false,
  mutationEnabled: false,
  settlementMutationEnabled: false,
  payoutMutationEnabled: false,
  walletMutationEnabled: false,
  paymentMutationEnabled: false,
  sourceOfTruth: {
    completedChapterLedger: 'future_story_completed_chapter_ledger',
    serializationState: 'future_story_pack_serialization_state',
    operatorDecisionAudit: 'future_story_author_policy_decisions',
    existingSettlementRowsMutated: false,
  },
  baseRatePolicy: {
    defaultAuthorShareBps: 5000,
    penaltyAuthorShareBps: 4500,
    clientSubmittedRateTrusted: false,
    operatorMustUseStableReasonKey: true,
  },
  penaltyReasons: STORY_AUTHOR_SETTLEMENT_PENALTY_REASONS,
  completedChapterProtection: {
    alreadyCompletedChapterRateLocked: true,
    completedAtSource: 'server_chapter_completion_event',
    completedBeforePenaltyUsesOriginalRate: true,
    retroactivePenaltyOnCompletedChapters: false,
    settledOrPayoutRowsRewritten: false,
  },
  futureAndIncompletePolicy: {
    appliesOnlyToFutureOrIncompleteChapters: true,
    incompleteChapterStatusKeys: ['draft', 'scheduled', 'publishing', 'paused'],
    newCompletionAfterPenaltyUsesPenaltyRate: true,
    penaltyLiftRequiresNewOperatorDecision: true,
  },
  projection: {
    storyPackId: '<story pack uuid>',
    seasonId: '<season uuid or null>',
    authorId: '<author uuid>',
    penaltyReasonKey: '<stable reason key>',
    effectiveFrom: '<ISO datetime>',
    effectiveUntil: '<ISO datetime or null>',
    baseAuthorShareBps: 5000,
    currentAuthorShareBps: '<5000|4500>',
    completedChapterRateLocked: true,
    futureChapterPenaltyApplies: '<boolean>',
    affectedFutureChapterCount: '<integer>',
    unaffectedCompletedChapterCount: '<integer>',
  },
  adminReadModel: {
    endpoint: 'GET /admin/api/v1/story-settlement/author-rate-penalties',
    enabled: false,
    requiredPermission: 'settlement:read',
    mutation: false,
    filters: {
      storyPackId: 'optional uuid',
      authorId: 'optional uuid',
      penaltyReasonKey: STORY_AUTHOR_SETTLEMENT_PENALTY_REASONS,
      activeOnly: 'optional boolean',
      take: { default: 50, max: 100 },
      cursor: 'opaque cursor',
    },
  },
  forbiddenSideEffects: {
    settlementRateUpdate: false,
    settlementRecalculation: false,
    payoutRecalculation: false,
    walletDebit: false,
    walletCredit: false,
    paymentCapture: false,
    chapterAccessMutation: false,
  },
  privacy: {
    bankAccountReturned: false,
    taxIdReturned: false,
    rawContractReturned: false,
    settlementLedgerIdsReturned: false,
    payoutIdsReturned: false,
    tokenReturned: false,
    cookieReturned: false,
  },
} as const;
