import {
  STORY_SCENE_BACKGROUND_STATE_RESOLVER_CONTRACT,
  STORY_SCENE_ASSET_FALLBACK_ERROR_ENVELOPE_CONTRACT,
  STORY_SCENE_CHARACTER_VISIBILITY_RESOLVER_CONTRACT,
  STORY_SCENE_CHARACTER_LAYER_READ_MODEL_CONTRACT,
  STORY_SCENE_CHOICE_PROGRESS_WRITE_GUARD_CONTRACT,
  STORY_SCENE_CURRENT_SCENE_ENDPOINT_DELTA_CONTRACT,
  STORY_SCENE_FIXTURE_API_CONTRACT,
  STORY_SCENE_FIXTURE_LOCALE_FIELD_CONTRACT,
  STORY_SCENE_PROVIDER_GUARD_CONTRACT,
  STORY_SCENE_READ_MODEL_CONTRACT,
} from './story-scene-read-model';
import {
  STORY_SHORTS_ROUTE_RELOCATION_CONTRACT,
  STORY_STAGE_I18N_RUNTIME_EXPOSURE_CONTRACT,
  LUMINA_FEED_SHORTFORM_EMBEDDED_DATA_CONTRACT,
  LUMINA_FEED_SHORTS_SURFACE_FALLBACK_CONTRACT,
  SHORTFORM_LEGACY_ROUTE_COMPATIBILITY_CONTRACT,
  GLOBAL_NAV_STORY_TAB_ACTIVE_STATE_TEST_SKELETON,
  STORY_ROUTE_RELOCATION_DIFF_AUDIT_CONTRACT,
  STORY_SHORTS_ROUTE_ANALYTICS_CONTRACT,
  STORY_STAGE_MOBILE_SAFE_AREA_CONTRACT,
} from './story-route-relocation-contract';
import {
  IMMERSIVE_STORY_PLAYER_DATA_CONTRACT,
  STORY_DETAIL_PROLOGUE_PREVIEW_CONTRACT,
  STORY_DISCOVERY_FILTER_LIST_UX_CONTRACT,
  STORY_IMMERSIVE_EXPERIENCE_CONTRACT,
  TUTORIAL_FREE_PROLOGUE_RECOVERY_CONTRACT,
} from './story-immersive-experience-contract';
import {
  MANUSCRIPT_SCENE_EXTRACTION_CONTRACT,
  PUBLIC_SOURCE_STORY_COPYRIGHT_BOUNDARY_CONTRACT,
  STORY_BRANCH_MARKER_INGESTION_CONTRACT,
  STORY_CHAT_PLAY_SCENE_READ_MODEL_SUPPORT_CONTRACT,
  STORY_MANUSCRIPT_PIPELINE_CONTRACT,
  WRITER_MANUSCRIPT_HANDOFF_FORMAT_CONTRACT,
} from './story-manuscript-ingestion-contract';
import {
  STORY_UPLOAD_BACKEND_GUARD_CONTRACT,
} from './story-upload-guard-contract';
import {
  STORY_UPLOAD_CONTRACT_BUNDLE,
  STORY_UPLOAD_I18N_HANDOFF_KEY_PACKAGE,
  STORY_UPLOAD_IMPORT_EXPORT_MIGRATION_CONTRACT,
  STORY_UPLOAD_INTAKE_API_CONTRACT,
  STORY_UPLOAD_REVIEW_WORKFLOW_CONTRACT,
  WRITER_MANUSCRIPT_SCENE_CHOICE_ENDING_SCHEMA,
} from './story-upload-intake-contract';

export {
  buildStorySceneAssetFallbackErrorEnvelope,
  findStorySceneProviderGuardViolations,
  getStorySceneFixtureReadModel,
  listStorySceneFixtureReadModels,
  projectStorySceneReadModel,
  resolveStorySceneBackgroundState,
  resolveStorySceneCharacterVisibility,
  STORY_SCENE_BACKGROUND_STATE_RESOLVER_CONTRACT,
  STORY_SCENE_ASSET_FALLBACK_ERROR_ENVELOPE_CONTRACT,
  STORY_SCENE_CHARACTER_VISIBILITY_RESOLVER_CONTRACT,
  STORY_SCENE_CHARACTER_LAYER_READ_MODEL_CONTRACT,
  STORY_SCENE_CHOICE_PROGRESS_WRITE_GUARD_CONTRACT,
  STORY_SCENE_CURRENT_SCENE_ENDPOINT_DELTA_CONTRACT,
  STORY_SCENE_FIXTURE_API_CONTRACT,
  STORY_SCENE_FIXTURE_LOCALE_FIELD_CONTRACT,
  STORY_SCENE_PROVIDER_GUARD_CONTRACT,
  STORY_SCENE_READ_MODEL_CONTRACT,
} from './story-scene-read-model';
export {
  findStoryShortsAnalyticsPayloadViolations,
  GLOBAL_NAV_STORY_TAB_ACTIVE_STATE_TEST_SKELETON,
  LUMINA_FEED_SHORTFORM_EMBEDDED_DATA_CONTRACT,
  LUMINA_FEED_SHORTS_SURFACE_FALLBACK_CONTRACT,
  SHORTFORM_LEGACY_ROUTE_COMPATIBILITY_CONTRACT,
  STORY_ROUTE_RELOCATION_DIFF_AUDIT_CONTRACT,
  STORY_SHORTS_ROUTE_ANALYTICS_CONTRACT,
  STORY_SHORTS_ROUTE_RELOCATION_CONTRACT,
  STORY_STAGE_I18N_RUNTIME_EXPOSURE_CONTRACT,
  STORY_STAGE_MOBILE_SAFE_AREA_CONTRACT,
} from './story-route-relocation-contract';
export {
  findImmersiveStorySensitiveFieldViolations,
  IMMERSIVE_STORY_PLAYER_DATA_CONTRACT,
  STORY_DETAIL_PROLOGUE_PREVIEW_CONTRACT,
  STORY_DISCOVERY_CARD_FIELDS,
  STORY_DISCOVERY_FILTER_IDS,
  STORY_DISCOVERY_FILTER_LIST_UX_CONTRACT,
  STORY_IMMERSIVE_EXPERIENCE_CONTRACT,
  STORY_IMMERSIVE_EXPERIENCE_FORBIDDEN_FIELDS,
  TUTORIAL_FREE_PROLOGUE_RECOVERY_CONTRACT,
} from './story-immersive-experience-contract';
export {
  findStoryManuscriptSensitiveFieldViolations,
  MANUSCRIPT_SCENE_EXTRACTION_CONTRACT,
  PUBLIC_SOURCE_STORY_COPYRIGHT_BOUNDARY_CONTRACT,
  STORY_BRANCH_MARKER_INGESTION_CONTRACT,
  STORY_CHAT_PLAY_SCENE_READ_MODEL_SUPPORT_CONTRACT,
  STORY_MANUSCRIPT_INGESTION_FORBIDDEN_FIELDS,
  STORY_MANUSCRIPT_MARKER_TOKENS,
  STORY_MANUSCRIPT_PIPELINE_CONTRACT,
  WRITER_MANUSCRIPT_HANDOFF_FORMAT_CONTRACT,
} from './story-manuscript-ingestion-contract';
export {
  AUTHOR_SUB_ENDING_COUNT_VALIDATION_GUARD_CONTRACT,
  findStoryUploadSensitiveFieldViolations,
  STORY_ENDING_TYPE_BACKEND_POLICY_CONTRACT,
  STORY_BRANCH_RESULT_STATE_BACKEND_GUARD_CONTRACT,
  STORY_HIATUS_PENALTY_PENDING_VALUES_GUARD_CONTRACT,
  STORY_PART_LENGTH_POLICY_CONTRACT,
  STORY_UPLOAD_BACKEND_GUARD_CONTRACT,
  STORY_UPLOAD_ENDING_TYPES,
  STORY_UPLOAD_FIXTURE_PRIVACY_GUARD_CONTRACT,
  STORY_UPLOAD_GUARD_FORBIDDEN_FIELDS,
  STORY_UPLOAD_INTAKE_STORAGE_GUARD_CONTRACT,
  STORY_UPLOAD_PENDING_DECISION_AUDIT_GUARD_CONTRACT,
  STORY_UPLOAD_PUBLIC_SOURCE_SAFETY_GUARD_CONTRACT,
} from './story-upload-guard-contract';
export {
  findStoryUploadIntakeSensitiveFieldViolations,
  STORY_UPLOAD_CONTRACT_BUNDLE,
  STORY_UPLOAD_I18N_HANDOFF_KEY_PACKAGE,
  STORY_UPLOAD_INTAKE_ENDING_TYPES,
  STORY_UPLOAD_IMPORT_EXPORT_MIGRATION_CONTRACT,
  STORY_UPLOAD_INTAKE_API_CONTRACT,
  STORY_UPLOAD_INTAKE_FORBIDDEN_FIELDS,
  STORY_UPLOAD_REVIEW_STATUSES,
  STORY_UPLOAD_REVIEW_WORKFLOW_CONTRACT,
  STORY_UPLOAD_SAFE_DTO_FIELD_GROUPS,
  WRITER_MANUSCRIPT_SCENE_CHOICE_ENDING_SCHEMA,
} from './story-upload-intake-contract';

export const STORY_STAGE_FREE_PROLOGUE_ENTITLEMENT_GUARD = {
  version: '2026-06-18.story-stage-free-prologue-entitlement-guard.v1',
  status: 'contract_only',
  endpoints: {
    preview: 'GET /api/v1/story-stage/prologue/preview',
    start: 'POST /api/v1/story-stage/prologue/sessions',
  },
  entitlement: {
    type: 'story_stage_free_prologue',
    platformAccountLimit: 1,
    uniquenessScope: ['userId', 'story_stage_free_prologue'],
    sourceOfTruth: 'user_entitlements',
    replayBehavior: 'return_existing_entitlement_without_new_session_charge',
  },
  companionPolicy: {
    allowedModes: ['self', 'ai_artist_companion'],
    maxAiArtistCompanions: 1,
    userSelfIncluded: true,
    artistSource: 'server_resolved_active_ai_artist',
    clientSubmittedArtistTrusted: false,
  },
  validationOrder: [
    'authenticate_platform_account',
    'resolve_story_pack_and_prologue_chapter',
    'verify_prologue_is_free_and_active',
    'verify_user_has_no_prior_free_prologue_entitlement',
    'resolve_optional_ai_artist_companion',
    'enforce_max_one_ai_artist_companion',
    'create_free_prologue_session_and_entitlement_in_same_transaction',
  ],
  responsePolicy: {
    stableCodeRequired: true,
    messageKeyRequired: true,
    rawUserFacingEnglishCopy: false,
    entitlementIdReturned: true,
    walletLedgerIdReturned: false,
    settlementIdReturned: false,
  },
  failureCodes: {
    alreadyUsed: {
      status: 409,
      code: 'STORY_FREE_PROLOGUE_ALREADY_USED',
      messageKey: 'storyStage.prologue.alreadyUsed',
    },
    invalidCompanion: {
      status: 400,
      code: 'STORY_PROLOGUE_INVALID_COMPANION',
      messageKey: 'storyStage.prologue.invalidCompanion',
    },
    unavailable: {
      status: 404,
      code: 'STORY_PROLOGUE_UNAVAILABLE',
      messageKey: 'storyStage.prologue.unavailable',
    },
  },
  mutationPolicy: {
    freeEntitlementMutation: true,
    storySessionMutation: true,
    paymentMutation: false,
    walletMutation: false,
    walletDebit: false,
    settlementMutation: false,
    payoutMutation: false,
    providerCall: false,
  },
} as const;

export const STORY_STAGE_PURCHASE_LEDGER_SKELETON = {
  version: '2026-06-18.story-stage-purchase-ledger-skeleton.v1',
  status: 'contract_only',
  purchaseTypes: ['chapter_single', 'season_bundle'],
  ledgerSourceOfTruth: 'story_purchase_ledger',
  productAuthority: {
    chapterPriceSource: 'story_chapters.server_price_lumina',
    seasonPriceSource: 'story_seasons.server_bundle_price_lumina',
    clientSubmittedPriceTrusted: false,
    clientSubmittedPurchaseTypeTrusted: false,
  },
  chapterSingle: {
    purchaseType: 'chapter_single',
    entitlementType: 'story_chapter_access',
    referenceType: 'story_chapter',
    idempotencyScope: ['userId', 'chapterId', 'purchaseType'],
    grants: ['chapter_read_access', 'choice_access_within_chapter'],
  },
  seasonBundle: {
    purchaseType: 'season_bundle',
    entitlementType: 'story_season_access',
    referenceType: 'story_season',
    idempotencyScope: ['userId', 'seasonId', 'purchaseType'],
    grants: ['published_chapters_in_season', 'future_chapters_when_published'],
  },
  choicePolicy: {
    choiceLevelBilling: false,
    choicesIncludedInChapterPrice: true,
    choicePriceFieldAllowed: false,
    premiumChoiceSurchargeAllowed: false,
    ledgerLinePerChoice: false,
  },
  ledgerLineShape: {
    id: 'storyPurchaseLedger.id',
    userId: 'users.id',
    purchaseType: 'chapter_single|season_bundle',
    referenceId: 'story_chapter.id|story_season.id',
    amountLumina: 'server_calculated_integer_lumina',
    currency: 'LUMINA',
    status: 'pending|granted|voided',
    idempotencyKey: 'story_stage:<purchaseType>:<userId>:<referenceId>',
  },
  mutationPolicy: {
    contractAddsEndpoint: false,
    paymentProviderCall: false,
    walletCredit: false,
    walletDebit: false,
    walletLedgerMutation: false,
    refundMutation: false,
    settlementMutation: false,
    payoutMutation: false,
  },
  responsePolicy: {
    stableCodeRequired: true,
    messageKeyRequired: true,
    rawUserFacingEnglishCopy: false,
    walletLedgerIdReturned: false,
    paymentTransactionIdReturned: false,
  },
} as const;

export const STORY_STAGE_AI_ARTIST_SETTLEMENT_SPLIT_SKELETON = {
  version: '2026-06-18.story-stage-ai-artist-settlement-split.v1',
  status: 'read_model_skeleton_only',
  readModel: 'story_stage_settlement_preview',
  settlementSources: {
    purchaseLedger: 'story_purchase_ledger',
    storyAuthor: 'story_packs.author_user_id',
    aiArtistCompanion: 'story_sessions.ai_artist_id',
  },
  splitOrder: [
    'load_granted_story_purchase',
    'detect_ai_artist_companion_participation',
    'reserve_ai_participation_cost_first',
    'calculate_story_author_share_from_remaining_basis',
    'publish_read_only_preview_without_mutation',
  ],
  aiArtistParticipation: {
    appliesWhenAiArtistCompanionPresent: true,
    aiParticipationCostRateBps: 5000,
    aiCreatorSettlementRateBps: 5000,
    sourceAmount: 'gross_story_purchase_amount_lumina',
    settlementBucket: 'ai_creator_participation_cost',
  },
  storyAuthorSettlement: {
    remainingBasisAfterAiCost: true,
    maxAuthorSettlementRateBps: 5000,
    sourceAmount: 'gross_minus_ai_participation_cost',
    settlementBucket: 'story_author_share',
  },
  projectionFields: [
    'purchaseLedgerId',
    'storyPackId',
    'storyAuthorUserId',
    'aiArtistId',
    'grossAmountLumina',
    'aiParticipationCostLumina',
    'storyAuthorBasisLumina',
    'storyAuthorMaxShareLumina',
    'platformRemainderLumina',
  ],
  mutationPolicy: {
    contractAddsSettlementEndpoint: false,
    settlementMutation: false,
    payoutMutation: false,
    walletMutation: false,
    walletLedgerMutation: false,
    paymentMutation: false,
  },
  responsePolicy: {
    readOnly: true,
    stableCodeRequired: true,
    messageKeyRequired: true,
    rawUserFacingEnglishCopy: false,
    privateUserIdentifierReturned: false,
  },
} as const;

export const STORY_STAGE_AUTHOR_REVENUE_READ_MODEL_CONTRACT = {
  version: '2026-06-23.story-stage-author-revenue-read-model.v1',
  status: 'read_model_contract_only',
  readModel: 'story_author_revenue_preview',
  sourceLedgers: {
    chapterPurchaseLedger: 'story_purchase_ledger.chapter_single',
    seasonBundleLedger: 'story_purchase_ledger.season_bundle',
    entitlementLedger: 'user_entitlements.story_chapter_or_season_access',
    aiArtistParticipation: 'story_sessions.ai_artist_id',
  },
  revenueBuckets: {
    chapterGrossRevenue: {
      source: 'granted_chapter_single_purchase',
      amountField: 'chapterGrossLumina',
      refundAdjusted: true,
    },
    seasonDiscountAllocation: {
      source: 'season_bundle_allocated_per_chapter',
      amountField: 'seasonDiscountLumina',
      discountIsSeparateFromRefund: true,
    },
    aiArtistParticipationCost: {
      source: 'ai_artist_companion_participation',
      amountField: 'aiParticipationCostLumina',
      deductedBeforeAuthorShare: true,
    },
    storyAuthorShare: {
      source: 'chapter_net_after_discount_refund_and_ai_participation',
      amountField: 'authorShareLumina',
      payoutEligible: false,
    },
  },
  projectionFields: [
    'storyPackId',
    'storySeasonId',
    'chapterId',
    'chapterNo',
    'authorUserId',
    'chapterGrossLumina',
    'seasonDiscountLumina',
    'refundAdjustedLumina',
    'aiArtistId',
    'aiParticipationCostLumina',
    'authorShareBasisLumina',
    'authorShareLumina',
    'payoutEligible',
  ],
  separationPolicy: {
    chapterRevenueAndSeasonDiscountSameField: false,
    aiArtistParticipationIncludedInAuthorShare: false,
    authorShareIncludesUnsettledOnly: true,
    clientSubmittedRevenueTrusted: false,
    clientSubmittedDiscountTrusted: false,
    clientSubmittedShareTrusted: false,
  },
  allocationSkeleton: {
    version: '2026-06-23.story-author-revenue-bucket-allocation.v1',
    calculationOrder: [
      'load_completed_chapter_purchase_revenue',
      'allocate_completed_season_bundle_revenue_to_chapter',
      'subtract_refund_or_chargeback_adjustment',
      'reserve_ai_character_companion_participation_cost',
      'calculate_story_author_share_preview',
      'return_read_only_projection_without_settlement_or_payout_mutation',
    ],
    chapterRevenue: {
      bucket: 'chapter_direct_revenue',
      source: 'completed_chapter_single_purchase',
      grossField: 'chapterGrossLumina',
      refundAdjustmentField: 'refundAdjustedLumina',
      seasonBundleRevenueIncluded: false,
    },
    seasonRevenue: {
      bucket: 'season_bundle_allocated_revenue',
      source: 'completed_season_bundle_purchase_allocated_per_chapter',
      allocatedField: 'seasonAllocatedGrossLumina',
      discountField: 'seasonDiscountLumina',
      chapterDirectRevenueIncluded: false,
    },
    aiCompanionCost: {
      bucket: 'ai_character_companion_participation_cost',
      source: 'story_session_companion_roster_confirmed_by_server',
      amountField: 'aiParticipationCostLumina',
      deductedBeforeAuthorShare: true,
      providerCostPayloadReturned: false,
    },
    authorPreview: {
      basisField: 'authorShareBasisLumina',
      previewField: 'authorShareLumina',
      finalSettlementAuthority: false,
      payoutEligible: false,
    },
  },
  noMutationPolicy: {
    contractAddsEndpoint: false,
    paymentMutation: false,
    refundMutation: false,
    settlementMutation: false,
    payoutMutation: false,
    walletMutation: false,
    walletLedgerMutation: false,
  },
  responsePolicy: {
    readOnly: true,
    stableCodeRequired: true,
    messageKeyRequired: true,
    rawUserFacingEnglishCopy: false,
    privateReaderIdentifierReturned: false,
    payoutAccountReturned: false,
    internalFormulaReturned: false,
  },
} as const;

export const STORY_STAGE_SESSION_RETENTION_POLICY_CONTRACT = {
  version: '2026-06-18.story-stage-session-retention-policy.v1',
  status: 'contract_only',
  endpoints: {
    continueSession: 'GET /api/v1/me/story-stage/sessions/:sessionId/continue',
    sessionList: 'GET /api/v1/me/story-stage/sessions',
  },
  sessionStatuses: ['active', 'paused', 'archived_inactive'],
  archivePolicy: {
    inactivityDays: 30,
    clockSource: 'server_time',
    trigger: 'no_user_progress_for_30_days',
    action: 'mark_session_archived_inactive',
    hardDeleteSession: false,
    deleteChoices: false,
    deleteProgress: false,
  },
  cleanupReadModel: {
    version: '2026-06-23.story-continuation-expiry-cleanup-read-model.v1',
    readModel: 'story_continuation_expiry_cleanup_preview',
    endpoint: 'GET /api/v1/me/story-stage/sessions/continuation-cleanup',
    enabled: false,
    readOnly: true,
    inactivityThresholdDays: 30,
    staleSessionStatusKey: 'archived_inactive',
    projectionFields: [
      'sessionId',
      'storyPackId',
      'currentChapterId',
      'lastProgressAt',
      'inactiveDays',
      'expiryCandidate',
      'statusKey',
      'dropAvailability',
      'entitlementRetention',
      'companionRetention',
    ],
    stateSeparation: {
      sessionArchivedInactive: true,
      chapterEntitlementDeleted: false,
      seasonEntitlementDeleted: false,
      purchasedHistoryDeleted: false,
      companionRosterDeleted: false,
      refundCandidateCreated: false,
    },
    dropAvailability: {
      userCanDropArchivedSession: true,
      dropDoesNotCancelEntitlement: true,
      dropDoesNotRefundWallet: true,
      messageKey: 'storyStage.session.archive.dropAvailable',
    },
    companionRetention: {
      selectedAiCompanionRetained: true,
      companionContextMayBeSummarized: true,
      paidCompanionAccessCanceled: false,
    },
  },
  purchaseHistoryPolicy: {
    purchaseHistoryRetained: true,
    chapterEntitlementsRetained: true,
    seasonEntitlementsRetained: true,
    archivedSessionCancelsPurchase: false,
    archivedSessionRefundsPurchase: false,
    restoreRequiresNewPurchase: false,
  },
  copyAndStatusPolicy: {
    rawStatusAsCopy: false,
    rawUserFacingEnglishCopy: false,
    titleKey: 'storyStage.session.archive.title',
    bodyKey: 'storyStage.session.archive.body',
    ctaKey: 'storyStage.session.archive.continueCta',
    statusKey: 'storyStage.session.status.archivedInactive',
    copyMustExplainPurchaseHistoryRetained: true,
  },
  inactivityExpirationBackendGuard: {
    version: '2026-06-24.story-inactivity-expiration-backend-guard.v1',
    status: 'read_model_contract_only',
    readOnly: true,
    inactivityThresholdDays: 30,
    serverClockAuthoritative: true,
    candidateStatusFrom: ['active', 'paused'],
    expiredStatusKey: 'archived_inactive',
    decisionOrder: [
      'load_owner_session',
      'calculate_inactive_days_from_last_progress_at',
      'mark_candidate_when_inactive_days_gte_30',
      'return_read_model_without_session_delete',
      'preserve_purchase_and_entitlement_history',
    ],
    retentionPolicy: {
      hardDeleteSession: false,
      deleteChoices: false,
      deleteProgress: false,
      cancelPurchase: false,
      revokeChapterEntitlement: false,
      revokeSeasonEntitlement: false,
    },
    mutationPolicy: {
      cleanupJobEnabledByThisContract: false,
      sessionDeleteMutation: false,
      purchaseCancellationMutation: false,
      refundMutation: false,
      walletMutation: false,
      walletLedgerMutation: false,
      settlementMutation: false,
      payoutMutation: false,
    },
  },
  mutationPolicy: {
    contractAddsArchiveJob: false,
    userProgressMutation: false,
    hardDeleteMutation: false,
    purchaseCancellationMutation: false,
    walletMutation: false,
    refundMutation: false,
    settlementMutation: false,
    payoutMutation: false,
  },
  responsePolicy: {
    stableCodeRequired: true,
    messageKeyRequired: true,
    purchaseHistoryReturnedAsOwnerOnly: true,
    privateAuthorNotesReturned: false,
  },
} as const;

export const STORY_STAGE_AUTHOR_INTERRUPTION_REFUND_PENALTY_READ_MODEL = {
  version: '2026-06-18.story-stage-author-interruption-refund-penalty.v1',
  status: 'read_model_contract_only',
  readModel: 'story_author_interruption_refund_penalty_preview',
  triggerPolicy: {
    events: ['long_hiatus', 'author_discontinued'],
    longHiatusThresholdSource: 'story_stage_policy.author_inactivity_days',
    authorDiscontinuedSource: 'story_packs.publication_status',
    manualOperatorReviewRequired: true,
  },
  refundCandidatePolicy: {
    completedChaptersRefundEligible: false,
    completedChaptersReason: 'reader_already_completed_chapter',
    incompleteStartedChaptersPartialRefundCandidate: true,
    unpublishedPurchasedChaptersPartialRefundCandidate: true,
    futureSeasonChaptersCandidate: true,
    refundAmountSource: 'server_calculated_unconsumed_chapter_value_lumina',
    clientSubmittedRefundAmountTrusted: false,
  },
  settlementPenaltyPreview: {
    penaltyAppliesTo: 'future_unsettled_story_author_share_only',
    alreadySettledPayoutsReopened: false,
    authorRateChangeMutation: false,
    payoutHoldMutation: false,
    requiresOperatorDecision: true,
  },
  readOnlyAuditGuard: {
    version: '2026-06-22.story-refund-penalty-read-only-audit-guard.v1',
    status: 'read_model_contract_only',
    conflictPolicy: 'separate_refund_candidates_from_author_penalty_preview',
    chapterBuckets: {
      completed: {
        refundEligible: false,
        authorPenaltyApplies: false,
        settlementRateLocked: true,
        reasonKey: 'reader_already_completed_chapter',
      },
      incompleteStarted: {
        refundEligible: true,
        authorPenaltyApplies: false,
        settlementRateLocked: false,
        reasonKey: 'unconsumed_started_chapter',
      },
      discontinuedFuture: {
        refundEligible: true,
        authorPenaltyApplies: true,
        settlementRateLocked: false,
        reasonKey: 'author_discontinued_future_chapter',
      },
    },
    auditProjectionFields: [
      'chapterBucket',
      'refundCandidateState',
      'authorPenaltyState',
      'settlementRateLocked',
      'refundMutationAllowed',
      'settlementMutationAllowed',
      'payoutMutationAllowed',
    ],
    forbiddenMergedStates: [
      'completed_chapter_refund_and_penalty_same_row',
      'wallet_refund_and_settlement_rate_update_same_action',
      'payout_hold_and_user_refund_credit_same_action',
    ],
  },
  projectionFields: [
    'storyPackId',
    'storySeasonId',
    'affectedChapterIds',
    'completedChapterIdsExcluded',
    'partialRefundCandidateChapterIds',
    'estimatedRefundLumina',
    'authorPenaltyPreview',
    'reviewRequired',
  ],
  responsePolicy: {
    stableCodeRequired: true,
    messageKeyRequired: true,
    rawUserFacingEnglishCopy: false,
    privateAuthorNotesReturned: false,
    userPaymentCredentialReturned: false,
  },
  mutationPolicy: {
    contractAddsRefundEndpoint: false,
    refundMutation: false,
    walletCredit: false,
    walletDebit: false,
    walletLedgerMutation: false,
    settlementRateMutation: false,
    settlementMutation: false,
    payoutMutation: false,
  },
} as const;

export const STORY_STAGE_COMPANION_BILLING_PROJECTION_CONTRACT = {
  version: '2026-06-27.story-companion-billing-projection.v1',
  status: 'read_model_contract_only',
  readModel: 'story_companion_billing_preview',
  surfaces: ['story_session_create_preview', 'story_session_roster_preview'],
  storyEntryCharge: {
    source: 'story_purchase_ledger.chapter_single_or_season_bundle',
    amountField: 'storyEntryCostLumina',
    alreadyEntitledAmountLumina: 0,
    clientSubmittedEntryCostTrusted: false,
  },
  companionRosterPolicy: {
    freePrologue: {
      maxAiCompanions: 1,
      paidExpansionAllowed: false,
      companionCostLumina: 0,
    },
    paidStory: {
      maxAiCompanions: 5,
      firstCompanionFree: true,
      paidCompanionSlots: 4,
      addOrSwapCostSource: 'server_story_product_policy',
      clientSubmittedCompanionCostTrusted: false,
    },
  },
  costSeparation: {
    storyEntryAndCompanionCostSameField: false,
    storyEntryCostField: 'storyEntryCostLumina',
    companionCostField: 'companionRosterCostLumina',
    totalPreviewField: 'totalPreviewLumina',
    doubleChargeAllowed: false,
    freeCompanionCountField: 'freeCompanionCount',
    paidCompanionCountField: 'paidCompanionCount',
  },
  rosterChangeStates: {
    add: {
      action: 'add_companion',
      costSource: 'server_story_product_policy',
      preservesChapterEntitlement: true,
    },
    swap: {
      action: 'swap_companion',
      costSource: 'server_story_product_policy',
      preservesChapterEntitlement: true,
    },
    leave: {
      action: 'leave_companion',
      costLumina: 0,
      refundPreviewOnly: true,
      preservesPurchasedStoryAccess: true,
    },
  },
  projectionFields: [
    'storySessionId',
    'storyPackId',
    'currentChapterId',
    'storyEntryCostLumina',
    'companionRosterCostLumina',
    'freeCompanionCount',
    'paidCompanionCount',
    'maxAiCompanions',
    'totalPreviewLumina',
    'rosterChangeState',
    'messageKey',
  ],
  mutationPolicy: {
    contractAddsEndpoint: false,
    storyPurchaseMutation: false,
    storyProgressMutation: false,
    companionRosterMutation: false,
    walletDebit: false,
    walletCredit: false,
    walletLedgerMutation: false,
    settlementMutation: false,
    payoutMutation: false,
    providerCall: false,
  },
  privacy: {
    rawPaymentLedgerIdReturned: false,
    rawWalletLedgerIdReturned: false,
    privateArtistNotesReturned: false,
    providerPromptReturned: false,
  },
} as const;

export const STORY_STAGE_COMPANION_SWAP_COST_PROJECTION_CONTRACT = {
  version: '2026-06-28.story-companion-swap-cost-projection.v1',
  status: 'read_model_contract_only',
  readModel: 'story_companion_swap_cost_preview',
  surfaces: [
    'story_session_roster_preview',
    'story_session_companion_change_preview',
  ],
  sourceOfTruth: {
    session: 'story_sessions',
    currentRoster: 'story_session_companions.confirmed',
    storyPolicy: 'server_story_product_policy',
    entitlements: 'user_entitlements.story_chapter_or_season_access',
  },
  actionStates: {
    keep: {
      action: 'keep_existing_companion',
      costLumina: 0,
      preservesCurrentContext: true,
      refundPreview: false,
    },
    add: {
      action: 'add_companion',
      costSource: 'server_story_product_policy',
      preservesPurchasedStoryAccess: true,
    },
    swap: {
      action: 'swap_companion',
      costSource: 'server_story_product_policy',
      previousCompanionContextArchived: true,
      preservesPurchasedStoryAccess: true,
    },
    leave: {
      action: 'leave_companion',
      costLumina: 0,
      refundPreviewOnly: true,
      preservesPurchasedStoryAccess: true,
    },
  },
  projectionFields: [
    'storySessionId',
    'storyPackId',
    'currentChapterId',
    'currentCompanionArtistId',
    'targetCompanionArtistId',
    'actionState',
    'freeCompanionCount',
    'paidCompanionCount',
    'companionChangeCostLumina',
    'totalPreviewLumina',
    'messageKey',
  ],
  separationPolicy: {
    storyEntryCostSeparate: true,
    companionChangeCostSeparate: true,
    clientSubmittedCompanionCostTrusted: false,
    clientSubmittedRosterTrusted: false,
    leaveDoesNotRefundWallet: true,
    keepDoesNotCreateLedger: true,
    swapDoesNotRevokePurchasedStoryAccess: true,
  },
  mutationPolicy: {
    contractAddsEndpoint: false,
    companionRosterMutation: false,
    storyProgressMutation: false,
    entitlementMutation: false,
    walletDebit: false,
    walletCredit: false,
    walletLedgerMutation: false,
    paymentMutation: false,
    settlementMutation: false,
    payoutMutation: false,
    providerCall: false,
  },
  privacy: {
    rawPaymentLedgerIdReturned: false,
    rawWalletLedgerIdReturned: false,
    privateArtistNotesReturned: false,
    providerPromptReturned: false,
    adminMemoReturned: false,
  },
} as const;

export const STORY_STAGE_AUTHOR_SETTLEMENT_REFUND_READ_MODEL = {
  version: '2026-06-27.story-author-settlement-refund-read-model.v1',
  status: 'read_model_contract_only',
  readModel: 'story_author_settlement_refund_preview',
  endpoint: 'GET /api/v1/creator-studio/story-packs/:packId/settlement-refunds',
  ownerScope: {
    authorOnly: true,
    backstageRequiresPermission: 'story:settlement:read',
    nonOwnerResponse: '403_or_404_without_identity_leak',
  },
  sourceLedgers: {
    purchaseLedger: 'story_purchase_ledger.granted',
    refundLedger: 'story_purchase_ledger.refunded_or_chargeback',
    entitlementLedger: 'user_entitlements.story_chapter_or_season_access',
    authorRevenuePreview: 'story_author_revenue_preview',
  },
  buckets: {
    grossStoryRevenue: {
      source: 'granted_chapter_or_season_purchase',
      amountField: 'grossLumina',
    },
    refundAdjustment: {
      source: 'refunded_or_chargeback_purchase_rows',
      amountField: 'refundAdjustedLumina',
      deductedBeforeAuthorShare: true,
    },
    aiCompanionCost: {
      source: 'server_confirmed_ai_companion_participation',
      amountField: 'aiCompanionCostLumina',
      deductedBeforeAuthorShare: true,
    },
    authorSharePreview: {
      source: 'gross_minus_refund_and_ai_companion_cost',
      amountField: 'authorSharePreviewLumina',
      payoutEligible: false,
    },
  },
  projectionFields: [
    'storyPackId',
    'storySeasonId',
    'chapterId',
    'period',
    'grossLumina',
    'refundAdjustedLumina',
    'aiCompanionCostLumina',
    'authorShareBasisLumina',
    'authorSharePreviewLumina',
    'payoutEligible',
    'messageKey',
  ],
  separationPolicy: {
    grossAndRefundSameField: false,
    refundAdjustmentCanIncreaseAuthorShare: false,
    aiCompanionCostIncludedInAuthorShare: false,
    payoutMutationFromRead: false,
    clientSubmittedRevenueTrusted: false,
    clientSubmittedRefundTrusted: false,
    clientSubmittedShareTrusted: false,
  },
  privacy: {
    rawBuyerUserIdReturned: false,
    rawPaymentLedgerIdReturned: false,
    rawWalletLedgerIdReturned: false,
    rawRefundReasonReturned: false,
    privateAuthorNotesReturned: false,
    adminMemoReturned: false,
  },
  mutationPolicy: {
    contractAddsEndpoint: false,
    settlementMutation: false,
    payoutMutation: false,
    refundMutation: false,
    walletCredit: false,
    walletDebit: false,
    walletLedgerMutation: false,
  },
} as const;

export const STORY_SCENE_ASSET_READ_MODEL_CONTRACT = {
  version: '2026-06-29.story-scene-asset-read-model.v1',
  status: 'read_model_contract_only',
  readModel: 'story_scene_asset_projection',
  endpoints: {
    sessionSceneList: {
      method: 'GET',
      path: '/api/v1/story-sessions/:sessionId/scenes',
      enabled: false,
      authRequired: true,
      response: 'StorySceneAssetProjection[]',
    },
    currentScene: {
      method: 'GET',
      path: '/api/v1/story-sessions/:sessionId/current-scene',
      enabled: false,
      authRequired: true,
      response: 'StorySceneAssetProjection',
    },
    fixtureSceneList: STORY_SCENE_FIXTURE_API_CONTRACT.endpoint,
  },
  sourceOfTruth: {
    sceneText: 'story_session_scenes.safe_text_projection',
    backgroundAsset: 'story_scene_assets.public_background_asset',
    backgroundPromptKey: 'story_scene_asset_prompt_keys.public_key',
    characterAsset: 'story_scene_character_assets.public_character_asset',
    fallbackKey: 'story_scene_asset_fallback_keys.public_i18n_key',
  },
  projectionFields: [
    'sceneId',
    'sceneText',
    'backgroundAsset',
    'backgroundPromptKey',
    'backgroundState',
    'characters',
    'fallbackKey',
  ],
  backgroundAsset: {
    assetIdField: 'assetId',
    publicUrlField: 'url',
    labelKeyField: 'labelKey',
    allowedStates: ['ready', 'loading', 'missing', 'fallback'],
    storageKeyReturned: false,
    signedUrlReturned: false,
    providerAssetIdReturned: false,
  },
  characters: {
    maxVisibleCharactersPerScene: 4,
    fields: [
      'characterId',
      'artistSlug',
      'displayNameKey',
      'assetId',
      'characterPose',
      'characterLayer',
      'entranceState',
    ],
    allowedPoses: ['neutral', 'speaking', 'listening', 'alert', 'leaving'],
    allowedLayers: ['background', 'midground', 'foreground', 'offscreen'],
    storageKeyReturned: false,
    privatePersonaReturned: false,
  },
  characterLayerReadModel: STORY_SCENE_CHARACTER_LAYER_READ_MODEL_CONTRACT,
  fallbackPolicy: {
    fallbackKeyRequired: true,
    fallbackKeySeparateFromScreenCopy: true,
    rawPromptAsFallbackCopyAllowed: false,
    supportedLocaleKeys: ['ko', 'en', 'ja', 'zh-Hans', 'zh-Hant'],
    defaultFallbackKey: 'storyStage.scene.assetFallback.default',
  },
  backgroundStateResolver: STORY_SCENE_BACKGROUND_STATE_RESOLVER_CONTRACT,
  currentSceneEndpointDelta: STORY_SCENE_CURRENT_SCENE_ENDPOINT_DELTA_CONTRACT,
  choiceProgressWriteGuard: STORY_SCENE_CHOICE_PROGRESS_WRITE_GUARD_CONTRACT,
  fixtureLocaleFields: STORY_SCENE_FIXTURE_LOCALE_FIELD_CONTRACT,
  characterVisibilityResolver:
    STORY_SCENE_CHARACTER_VISIBILITY_RESOLVER_CONTRACT,
  assetFallbackErrorEnvelope:
    STORY_SCENE_ASSET_FALLBACK_ERROR_ENVELOPE_CONTRACT,
  fixtureApi: STORY_SCENE_FIXTURE_API_CONTRACT,
  providerGuard: STORY_SCENE_PROVIDER_GUARD_CONTRACT,
  validationOrder: [
    'authenticate_session_owner_or_entitled_reader',
    'load_story_session_scene_projection',
    'map_background_asset_to_public_projection',
    'map_character_assets_to_public_projection',
    'apply_fallback_key_when_asset_missing_or_loading',
    'return_scene_asset_projection_without_mutation',
  ],
  privacy: {
    rawPromptReturned: false,
    providerPayloadReturned: false,
    internalCostReturned: false,
    privateUserInputReturned: false,
    rawModelResponseReturned: false,
    privateAuthorNotesReturned: false,
    adminMemoReturned: false,
    storageKeyReturned: false,
    signedUrlReturned: false,
  },
  mutationPolicy: {
    contractAddsEndpoint: false,
    providerCall: false,
    imageGeneration: false,
    videoGeneration: false,
    assetCreate: false,
    assetUploadIntentCreate: false,
    storyProgressMutation: false,
    storySceneWrite: false,
    paymentMutation: false,
    walletDebit: false,
    walletCredit: false,
    walletLedgerMutation: false,
    settlementMutation: false,
    payoutMutation: false,
  },
} as const;

export const STORY_STAGE_CONTRACT = {
  version: '2026-06-18.story-stage-contract.v1',
  freePrologueEntitlementGuard: STORY_STAGE_FREE_PROLOGUE_ENTITLEMENT_GUARD,
  purchaseLedgerSkeleton: STORY_STAGE_PURCHASE_LEDGER_SKELETON,
  aiArtistSettlementSplitSkeleton:
    STORY_STAGE_AI_ARTIST_SETTLEMENT_SPLIT_SKELETON,
  authorRevenueReadModel: STORY_STAGE_AUTHOR_REVENUE_READ_MODEL_CONTRACT,
  companionBillingProjection: STORY_STAGE_COMPANION_BILLING_PROJECTION_CONTRACT,
  companionSwapCostProjection:
    STORY_STAGE_COMPANION_SWAP_COST_PROJECTION_CONTRACT,
  sessionRetentionPolicy: STORY_STAGE_SESSION_RETENTION_POLICY_CONTRACT,
  authorInterruptionRefundPenaltyReadModel:
    STORY_STAGE_AUTHOR_INTERRUPTION_REFUND_PENALTY_READ_MODEL,
  authorSettlementRefundReadModel:
    STORY_STAGE_AUTHOR_SETTLEMENT_REFUND_READ_MODEL,
  sceneAssetReadModel: STORY_SCENE_ASSET_READ_MODEL_CONTRACT,
  storySceneReadModel: STORY_SCENE_READ_MODEL_CONTRACT,
  storyShortsRouteRelocation: STORY_SHORTS_ROUTE_RELOCATION_CONTRACT,
  storyStageI18nRuntimeExposure: STORY_STAGE_I18N_RUNTIME_EXPOSURE_CONTRACT,
  storyStageMobileSafeArea: STORY_STAGE_MOBILE_SAFE_AREA_CONTRACT,
  luminaFeedShortformEmbeddedData:
    LUMINA_FEED_SHORTFORM_EMBEDDED_DATA_CONTRACT,
  luminaFeedShortsSurfaceFallback:
    LUMINA_FEED_SHORTS_SURFACE_FALLBACK_CONTRACT,
  shortformLegacyRouteCompatibility:
    SHORTFORM_LEGACY_ROUTE_COMPATIBILITY_CONTRACT,
  globalNavStoryTabActiveState:
    GLOBAL_NAV_STORY_TAB_ACTIVE_STATE_TEST_SKELETON,
  storyShortsRouteAnalytics: STORY_SHORTS_ROUTE_ANALYTICS_CONTRACT,
  routeRelocationDiffAudit: STORY_ROUTE_RELOCATION_DIFF_AUDIT_CONTRACT,
  storyDiscoveryFilterListUx: STORY_DISCOVERY_FILTER_LIST_UX_CONTRACT,
  storyDetailProloguePreview: STORY_DETAIL_PROLOGUE_PREVIEW_CONTRACT,
  immersiveStoryPlayerData: IMMERSIVE_STORY_PLAYER_DATA_CONTRACT,
  tutorialFreePrologueRecovery: TUTORIAL_FREE_PROLOGUE_RECOVERY_CONTRACT,
  storyImmersiveExperience: STORY_IMMERSIVE_EXPERIENCE_CONTRACT,
  storyChatPlaySceneReadModelSupport:
    STORY_CHAT_PLAY_SCENE_READ_MODEL_SUPPORT_CONTRACT,
  writerManuscriptHandoffFormat: WRITER_MANUSCRIPT_HANDOFF_FORMAT_CONTRACT,
  storyBranchMarkerIngestion: STORY_BRANCH_MARKER_INGESTION_CONTRACT,
  manuscriptSceneExtraction: MANUSCRIPT_SCENE_EXTRACTION_CONTRACT,
  publicSourceStoryCopyrightBoundary:
    PUBLIC_SOURCE_STORY_COPYRIGHT_BOUNDARY_CONTRACT,
  storyManuscriptPipeline: STORY_MANUSCRIPT_PIPELINE_CONTRACT,
  storyUploadBackendGuard: STORY_UPLOAD_BACKEND_GUARD_CONTRACT,
  storyUploadIntakeApi: STORY_UPLOAD_INTAKE_API_CONTRACT,
  writerManuscriptSceneChoiceEndingSchema:
    WRITER_MANUSCRIPT_SCENE_CHOICE_ENDING_SCHEMA,
  storyUploadImportExportMigration:
    STORY_UPLOAD_IMPORT_EXPORT_MIGRATION_CONTRACT,
  storyUploadReviewWorkflow: STORY_UPLOAD_REVIEW_WORKFLOW_CONTRACT,
  storyUploadI18nHandoffKeyPackage:
    STORY_UPLOAD_I18N_HANDOFF_KEY_PACKAGE,
  storyUploadContractBundle: STORY_UPLOAD_CONTRACT_BUNDLE,
} as const;

export const STORY_STAGE_PACK_CHAPTER_SESSION_CONTRACT = {
  version: '2026-06-18.story-stage-pack-chapter-session-skeleton.v1',
  status: 'backend_contract_skeleton_only',
  scope: {
    surfaces: ['story_pack', 'story_chapter', 'story_session', 'story_choice'],
    implementationReady: false,
    readModelOnly: true,
    publicMutationEnabled: false,
  },
  apiContracts: {
    storyPackList: {
      method: 'GET',
      path: '/api/v1/story-packs',
      enabled: false,
      authRequired: false,
      response: 'StoryPack list projection',
    },
    storyPackDetail: {
      method: 'GET',
      path: '/api/v1/story-packs/:packSlug',
      enabled: false,
      authRequired: false,
      response: 'StoryPack detail with safe chapter list projection',
    },
    storyChapterDetail: {
      method: 'GET',
      path: '/api/v1/story-packs/:packSlug/chapters/:chapterNo',
      enabled: false,
      authRequired: false,
      response: 'StoryChapter detail projection',
    },
    storySessionCreate: {
      method: 'POST',
      path: '/api/v1/story-packs/:packSlug/sessions',
      enabled: false,
      authRequired: true,
      idempotencyRequired: true,
      response: 'StorySession projection',
    },
    storyChoiceList: {
      method: 'GET',
      path: '/api/v1/story-sessions/:sessionId/choices',
      enabled: false,
      authRequired: true,
      response: 'StoryChoice list projection',
    },
  },
  storyPack: {
    idField: 'story_packs.id',
    slugField: 'story_packs.slug',
    pricingModes: ['free', 'paid', 'mixed'],
    lifecycleStatuses: [
      'draft',
      'serializing',
      'completed',
      'hiatus',
      'season_ended',
      'archived',
    ],
    publicListStatuses: ['serializing', 'completed', 'hiatus', 'season_ended'],
    fields: [
      'id',
      'slug',
      'title',
      'summary',
      'coverImageUrl',
      'pricingMode',
      'lifecycleStatus',
      'chapterCount',
      'freeChapterCount',
      'paidChapterCount',
      'ageRatingKey',
      'genreKeys',
      'updatedAt',
    ],
    privateFieldsReturned: false,
  },
  storyChapter: {
    idField: 'story_chapters.id',
    packReferenceField: 'story_chapters.storyPackId',
    chapterNoField: 'story_chapters.chapterNo',
    pricingModes: ['free', 'paid'],
    lifecycleStatuses: [
      'draft',
      'scheduled',
      'published',
      'paused',
      'season_finale',
      'archived',
    ],
    publicReadableStatuses: ['published', 'paused', 'season_finale'],
    paidAccessPolicy: {
      freeChapterReadableWithoutPurchase: true,
      paidChapterRequiresEntitlement: true,
      previewFieldsForLockedPaidChapter: [
        'id',
        'chapterNo',
        'title',
        'summary',
        'pricingMode',
        'priceLumina',
        'locked',
      ],
      lockedBodyReturned: false,
    },
    paidEntitlementServerGuard: {
      version: '2026-06-24.story-paid-chapter-entitlement-server-guard.v1',
      status: 'read_model_contract_only',
      readOnly: true,
      sourceOfTruth: {
        chapterEntitlement: 'user_entitlements.story_chapter_access',
        seasonEntitlement: 'user_entitlements.story_season_access',
        purchaseLedger: 'story_purchase_ledger.granted',
        chapterPublication: 'story_chapters.publicReadableStatuses',
      },
      serverDecisionOrder: [
        'load_chapter_by_pack_slug_and_chapter_no',
        'return_body_when_chapter_is_free',
        'require_authenticated_reader_for_paid_chapter_body',
        'load_user_chapter_entitlement',
        'load_user_season_entitlement_for_chapter',
        'verify_purchase_ledger_status_granted',
        'return_locked_preview_when_entitlement_missing',
      ],
      entitlementScopes: {
        chapterSingle: {
          entitlementType: 'story_chapter_access',
          referenceType: 'story_chapter',
          grantsBodyAccessTo: 'exact_chapter_only',
        },
        seasonBundle: {
          entitlementType: 'story_season_access',
          referenceType: 'story_season',
          grantsBodyAccessTo: 'published_chapters_in_season',
          futureChapterAccessSource: 'chapter_publication_status',
        },
      },
      clientTrustPolicy: {
        clientSubmittedPurchasedTrusted: false,
        clientSubmittedEntitlementTrusted: false,
        clientSubmittedWalletBalanceTrusted: false,
        clientSubmittedPriceTrusted: false,
      },
      responsePolicy: {
        lockedBodyReturned: false,
        entitlementIdReturnedToReader: false,
        purchaseLedgerIdReturned: false,
        walletLedgerIdReturned: false,
        stableMessageKeyRequired: true,
        lockedMessageKey: 'storyStage.chapter.locked',
      },
      mutationPolicy: {
        paymentMutation: false,
        walletDebit: false,
        walletCredit: false,
        walletLedgerMutation: false,
        entitlementGrant: false,
        refundMutation: false,
        settlementMutation: false,
        payoutMutation: false,
      },
    },
    fields: [
      'id',
      'packId',
      'chapterNo',
      'title',
      'summary',
      'body',
      'pricingMode',
      'priceLumina',
      'lifecycleStatus',
      'publishedAt',
    ],
  },
  storySession: {
    idField: 'story_sessions.id',
    ownerField: 'story_sessions.userId',
    packReferenceField: 'story_sessions.storyPackId',
    chapterReferenceField: 'story_sessions.currentChapterId',
    lifecycleStatuses: [
      'active',
      'paused',
      'completed',
      'abandoned',
      'expired',
    ],
    source: 'server_created_story_session_after_entitlement_check',
    idempotencyScope: 'story-session:<userId>:<packSlug>:<client-idempotency-key>',
    replaySameRequest: true,
    conflictOnChangedFingerprint: true,
    aiProviderCallOnCreate: false,
    walletMutationOnCreate: false,
    imageVideoGenerationOnCreate: false,
  },
  storyChoice: {
    idField: 'story_choices.id',
    sessionReferenceField: 'story_choices.storySessionId',
    defaultCount: 3,
    maxCount: 5,
    choiceTypes: ['dialogue', 'action', 'investigate', 'travel', 'wait'],
    fields: [
      'id',
      'sessionId',
      'chapterId',
      'choiceNo',
      'labelKey',
      'body',
      'choiceType',
      'available',
      'disabledReasonKey',
    ],
    rawModelPromptReturned: false,
    providerPayloadReturned: false,
  },
  validationOrder: [
    'auth_optional_for_public_pack_reads',
    'validate_pack_slug',
    'load_public_story_pack',
    'validate_chapter_identifier_when_present',
    'load_public_or_entitled_chapter_projection',
    'require_auth_for_session_or_choice_reads',
    'check_paid_chapter_entitlement_before_body_projection',
    'validate_idempotency_key_for_session_create',
    'return_contract_projection_without_mutation',
  ],
  noMutationPolicy: {
    paymentOrderCreate: false,
    walletDebit: false,
    luminaDebit: false,
    entitlementGrant: false,
    storySessionCreateEnabled: false,
    storyStateMutation: false,
    storyChoiceSubmit: false,
    aiProviderCall: false,
    imageGeneration: false,
    videoGeneration: false,
    notificationCreate: false,
    settlementMutation: false,
    payoutMutation: false,
  },
  privacy: {
    rawUserEmailReturned: false,
    rawPaymentLedgerIdReturned: false,
    providerPromptReturned: false,
    providerResponseReturned: false,
    adminMemoReturned: false,
    internalModerationNoteReturned: false,
  },
} as const;
