import { STORY_ROUTE_SUPPORTED_LOCALE_SLOTS } from './story-route-relocation-contract';

export const STORY_PRODUCTION_RELEASE_CONTRACT = {
  version: '2026-07-12.story-production-release-replay-and-analysis.v1',
  status: 'architecture_contract_only',
  sourceDecisions: ['story_production_release_replay_policy', 'writer_paste_analysis_assistant'],
  initialPricePolicy: {
    priceAuthority: 'server_story_product_policy',
    rateCardInputs: {
      authorAndRightsCostPerSale: null,
      expectedFreeReplayCount: null,
      includedNewAiRouteCount: null,
      averageAiRouteCost: null,
      paymentFeePerSale: null,
      storageAndDeliveryCostPerSale: null,
      operatingMarginRate: null,
    },
    calculator: {
      requiredFormula:
        'author_and_rights + expected_replay_cost + included_ai_route_cost + payment_fee + storage_delivery + operating_margin',
      modelRateCardReplaceable: true,
      priceMustBeApprovedBeforeSale: true,
      clientSubmittedPriceTrusted: false,
    },
    productBoundary: {
      workEntitlementProduct: 'story_scope_access',
      freeReplayProduct: false,
      newAiRouteCreditProduct: 'story_new_ai_route_credit',
      workRepurchaseRequiredForOwnedScope: false,
      halfPriceRepurchaseAllowed: false,
    },
  },
  publicationLifecycle: {
    states: [
      'draft',
      'intake_received',
      'reviewing',
      'revision_requested',
      'release_ready',
      'published',
      'sale_suspended',
      'archived',
    ],
    publicRoutePolicy: {
      catalogSearchRecommendationStates: ['published'],
      draftOrReviewVisibleToPublic: false,
      releaseReadyVisibleToPublic: false,
      saleSuspendedNewPurchaseAllowed: false,
      publicProjectionSourceOfTruth: 'active_story_release_version',
    },
    writerAndPmProjection: {
      requiredFields: ['visible_status', 'required_next_action', 'revision_summary'],
      showImplementationDetails: false,
      supportedLocaleSlots: STORY_ROUTE_SUPPORTED_LOCALE_SLOTS,
    },
  },
  replayAndEndingGallery: {
    progressModel: ['continue', 'restart', 'save_slot', 'checkpoint', 'ending_gallery'],
    saveSlots: {
      minimumPerReaderAndStoryScope: 3,
      overwriteRequiresExplicitConfirmation: true,
      resetRequiresExplicitConfirmation: true,
      checkpointRestartDoesNotOverwriteActiveSlot: true,
    },
    endingGallery: {
      endingKinds: ['author_main', 'author_sub', 'ai_generated'],
      pathSignatureRequired: true,
      generatedRouteProvenanceRequired: true,
      existingGeneratedRouteReplayIsFree: true,
    },
    entitlementBoundary: {
      ownedStoryScopeUnlocksAuthorEndings: true,
      progressDeletionRevokesEntitlement: false,
      progressRetentionIndependentOfEntitlementRetention: true,
      newAiRouteCreditSeparateFromStoryEntitlement: true,
    },
  },
  aiUsageLedger: {
    sourceOfTruth: 'future_story_ai_usage_ledger',
    eventKinds: [
      'existing_route_read',
      'new_route_request',
      'new_route_completed',
      'new_route_failed',
      'retry_without_completion',
      'approved_compensation',
    ],
    chargePolicy: {
      existingGeneratedRouteRead: 'no_charge',
      authorWrittenEndingRead: 'no_charge',
      authorWrittenEndingCreation: 'not_ai_usage',
      newAiRouteCompleted: 'consumes_included_allowance_or_separate_credit',
      failedGeneration: 'no_charge_until_policy_review',
      retryWithoutCompletion: 'no_duplicate_charge',
    },
    provenancePolicy: {
      authorManuscript: 'writer_original',
      authorEnding: 'writer_original',
      aiSuggestion: 'ai_suggestion',
      approvedAiRoute: 'ai_generated_with_writer_approval',
      ledgerEventMustReferenceProvenance: true,
    },
    responsePrivacy: {
      providerPayloadReturned: false,
      providerCostDetailReturned: false,
      providerCredentialReturned: false,
      internalUsageLedgerReferenceReturned: false,
    },
  },
  immutableReleaseVersion: {
    releaseSnapshotIncludes: [
      'manuscript_version',
      'branch_graph_version',
      'ending_set_version',
      'scene_asset_manifest_version',
      'localized_display_version',
    ],
    activationPolicy: {
      validateCandidateBeforeActivation: true,
      currentPublishedReleaseStaysActiveOnCandidateFailure: true,
      activeReleaseSwitchIsAtomic: true,
      rollbackSelectsPriorImmutableRelease: true,
      rollbackEditsPublishedReleaseInPlace: false,
    },
    readerSessionPolicy: {
      sessionPinsReleaseVersionAtStart: true,
      activeSessionSwitchesGraphMidPlay: false,
      newSessionUsesCurrentPublishedRelease: true,
    },
    operatorReadProjection: {
      includes: ['candidate_diff_summary', 'active_release_summary', 'rollback_result'],
      includesPrivateManuscriptOrAssetSource: false,
      mutationEnabled: false,
    },
  },
  writerPasteAnalysisMemory: {
    immutableInputs: {
      manuscriptVersionRequired: true,
      aiMayRewriteSourceManuscript: false,
      writerApprovalStoredSeparatelyFromAiSuggestion: true,
      generatedBranchStoredSeparatelyFromWriterBranch: true,
    },
    analysisCadence: {
      currentPart: 'full_part_analysis',
      currentPartContext: 'related_memory_retrieval_only',
      actOrVolumeBoundary: 'precision_audit',
      preRelease: 'whole_work_structured_memory_audit',
      fullManuscriptResendForEveryPart: false,
    },
    retrievalMemory: [
      'approved_part_summary',
      'scene_and_beat_state',
      'entity_and_relationship_state',
      'event_timeline',
      'foreshadow_thread',
      'branch_state',
      'approved_style_profile',
    ],
    continuityPolicy: {
      everyFindingNeedsCurrentEvidence: true,
      relatedPastEvidenceRequiredForCrossPartFinding: true,
      criticalFindingBlocksReleaseUntilWriterDecision: true,
      writerDecisionKinds: ['confirm', 'edit', 'remove', 'defer', 'intended_exception'],
      analysisFailureRecovery: 'resume_from_immutable_input_and_completed_checkpoints',
    },
    mobileReviewPolicy: {
      desktopReviewDialog: 'single_dialog_with_steps',
      mobile390And400ReviewDialog: 'full_screen_single_dialog',
      nestedDialogAllowed: false,
      longEvidenceMustWrapOrUseContainedScroll: true,
      supportedLocaleSlots: STORY_ROUTE_SUPPORTED_LOCALE_SLOTS,
    },
  },
  mutationPolicy: {
    contractAddsEndpoint: false,
    paymentMutation: false,
    walletMutation: false,
    entitlementMutation: false,
    providerCall: false,
    providerGeneration: false,
    manuscriptWrite: false,
    storyPublish: false,
    storyProgressMutation: false,
    rollbackMutation: false,
  },
  privacy: {
    rawI18nKeyVisible: false,
    privateInputValueReturned: false,
    providerPayloadReturned: false,
    internalReferenceReturned: false,
  },
} as const;
