export const STORY_STAGE_FREE_PROLOGUE_ENTITLEMENT_GUARD = {
  version: '2026-06-18.story-stage-free-prologue-entitlement-guard.v1',
  status: 'contract_only',
  endpoints: {
    preview: 'GET /api/v1/story-stage/prologue/preview',
    start: 'POST /api/v1/story-stage/prologue/sessions',
  },
  entitlement: {
    type: 'story_stage_free_prologue',
    platformAccountLimit: 1,
    uniquenessScope: ['userId', 'story_stage_free_prologue'],
    sourceOfTruth: 'user_entitlements',
    replayBehavior: 'return_existing_entitlement_without_new_session_charge',
  },
  companionPolicy: {
    allowedModes: ['self', 'ai_artist_companion'],
    maxAiArtistCompanions: 1,
    userSelfIncluded: true,
    artistSource: 'server_resolved_active_ai_artist',
    clientSubmittedArtistTrusted: false,
  },
  validationOrder: [
    'authenticate_platform_account',
    'resolve_story_pack_and_prologue_chapter',
    'verify_prologue_is_free_and_active',
    'verify_user_has_no_prior_free_prologue_entitlement',
    'resolve_optional_ai_artist_companion',
    'enforce_max_one_ai_artist_companion',
    'create_free_prologue_session_and_entitlement_in_same_transaction',
  ],
  responsePolicy: {
    stableCodeRequired: true,
    messageKeyRequired: true,
    rawUserFacingEnglishCopy: false,
    entitlementIdReturned: true,
    walletLedgerIdReturned: false,
    settlementIdReturned: false,
  },
  failureCodes: {
    alreadyUsed: {
      status: 409,
      code: 'STORY_FREE_PROLOGUE_ALREADY_USED',
      messageKey: 'storyStage.prologue.alreadyUsed',
    },
    invalidCompanion: {
      status: 400,
      code: 'STORY_PROLOGUE_INVALID_COMPANION',
      messageKey: 'storyStage.prologue.invalidCompanion',
    },
    unavailable: {
      status: 404,
      code: 'STORY_PROLOGUE_UNAVAILABLE',
      messageKey: 'storyStage.prologue.unavailable',
    },
  },
  mutationPolicy: {
    freeEntitlementMutation: true,
    storySessionMutation: true,
    paymentMutation: false,
    walletMutation: false,
    walletDebit: false,
    settlementMutation: false,
    payoutMutation: false,
    providerCall: false,
  },
} as const;

export const STORY_STAGE_PURCHASE_LEDGER_SKELETON = {
  version: '2026-06-18.story-stage-purchase-ledger-skeleton.v1',
  status: 'contract_only',
  purchaseTypes: ['chapter_single', 'season_bundle'],
  ledgerSourceOfTruth: 'story_purchase_ledger',
  productAuthority: {
    chapterPriceSource: 'story_chapters.server_price_lumina',
    seasonPriceSource: 'story_seasons.server_bundle_price_lumina',
    clientSubmittedPriceTrusted: false,
    clientSubmittedPurchaseTypeTrusted: false,
  },
  chapterSingle: {
    purchaseType: 'chapter_single',
    entitlementType: 'story_chapter_access',
    referenceType: 'story_chapter',
    idempotencyScope: ['userId', 'chapterId', 'purchaseType'],
    grants: ['chapter_read_access', 'choice_access_within_chapter'],
  },
  seasonBundle: {
    purchaseType: 'season_bundle',
    entitlementType: 'story_season_access',
    referenceType: 'story_season',
    idempotencyScope: ['userId', 'seasonId', 'purchaseType'],
    grants: ['published_chapters_in_season', 'future_chapters_when_published'],
  },
  choicePolicy: {
    choiceLevelBilling: false,
    choicesIncludedInChapterPrice: true,
    choicePriceFieldAllowed: false,
    premiumChoiceSurchargeAllowed: false,
    ledgerLinePerChoice: false,
  },
  ledgerLineShape: {
    id: 'storyPurchaseLedger.id',
    userId: 'users.id',
    purchaseType: 'chapter_single|season_bundle',
    referenceId: 'story_chapter.id|story_season.id',
    amountLumina: 'server_calculated_integer_lumina',
    currency: 'LUMINA',
    status: 'pending|granted|voided',
    idempotencyKey: 'story_stage:<purchaseType>:<userId>:<referenceId>',
  },
  mutationPolicy: {
    contractAddsEndpoint: false,
    paymentProviderCall: false,
    walletCredit: false,
    walletDebit: false,
    walletLedgerMutation: false,
    refundMutation: false,
    settlementMutation: false,
    payoutMutation: false,
  },
  responsePolicy: {
    stableCodeRequired: true,
    messageKeyRequired: true,
    rawUserFacingEnglishCopy: false,
    walletLedgerIdReturned: false,
    paymentTransactionIdReturned: false,
  },
} as const;

export const STORY_STAGE_AI_ARTIST_SETTLEMENT_SPLIT_SKELETON = {
  version: '2026-06-18.story-stage-ai-artist-settlement-split.v1',
  status: 'read_model_skeleton_only',
  readModel: 'story_stage_settlement_preview',
  settlementSources: {
    purchaseLedger: 'story_purchase_ledger',
    storyAuthor: 'story_packs.author_user_id',
    aiArtistCompanion: 'story_sessions.ai_artist_id',
  },
  splitOrder: [
    'load_granted_story_purchase',
    'detect_ai_artist_companion_participation',
    'reserve_ai_participation_cost_first',
    'calculate_story_author_share_from_remaining_basis',
    'publish_read_only_preview_without_mutation',
  ],
  aiArtistParticipation: {
    appliesWhenAiArtistCompanionPresent: true,
    aiParticipationCostRateBps: 5000,
    aiCreatorSettlementRateBps: 5000,
    sourceAmount: 'gross_story_purchase_amount_lumina',
    settlementBucket: 'ai_creator_participation_cost',
  },
  storyAuthorSettlement: {
    remainingBasisAfterAiCost: true,
    maxAuthorSettlementRateBps: 5000,
    sourceAmount: 'gross_minus_ai_participation_cost',
    settlementBucket: 'story_author_share',
  },
  projectionFields: [
    'purchaseLedgerId',
    'storyPackId',
    'storyAuthorUserId',
    'aiArtistId',
    'grossAmountLumina',
    'aiParticipationCostLumina',
    'storyAuthorBasisLumina',
    'storyAuthorMaxShareLumina',
    'platformRemainderLumina',
  ],
  mutationPolicy: {
    contractAddsSettlementEndpoint: false,
    settlementMutation: false,
    payoutMutation: false,
    walletMutation: false,
    walletLedgerMutation: false,
    paymentMutation: false,
  },
  responsePolicy: {
    readOnly: true,
    stableCodeRequired: true,
    messageKeyRequired: true,
    rawUserFacingEnglishCopy: false,
    privateUserIdentifierReturned: false,
  },
} as const;

export const STORY_STAGE_AUTHOR_REVENUE_READ_MODEL_CONTRACT = {
  version: '2026-06-23.story-stage-author-revenue-read-model.v1',
  status: 'read_model_contract_only',
  readModel: 'story_author_revenue_preview',
  sourceLedgers: {
    chapterPurchaseLedger: 'story_purchase_ledger.chapter_single',
    seasonBundleLedger: 'story_purchase_ledger.season_bundle',
    entitlementLedger: 'user_entitlements.story_chapter_or_season_access',
    aiArtistParticipation: 'story_sessions.ai_artist_id',
  },
  revenueBuckets: {
    chapterGrossRevenue: {
      source: 'granted_chapter_single_purchase',
      amountField: 'chapterGrossLumina',
      refundAdjusted: true,
    },
    seasonDiscountAllocation: {
      source: 'season_bundle_allocated_per_chapter',
      amountField: 'seasonDiscountLumina',
      discountIsSeparateFromRefund: true,
    },
    aiArtistParticipationCost: {
      source: 'ai_artist_companion_participation',
      amountField: 'aiParticipationCostLumina',
      deductedBeforeAuthorShare: true,
    },
    storyAuthorShare: {
      source: 'chapter_net_after_discount_refund_and_ai_participation',
      amountField: 'authorShareLumina',
      payoutEligible: false,
    },
  },
  projectionFields: [
    'storyPackId',
    'storySeasonId',
    'chapterId',
    'chapterNo',
    'authorUserId',
    'chapterGrossLumina',
    'seasonDiscountLumina',
    'refundAdjustedLumina',
    'aiArtistId',
    'aiParticipationCostLumina',
    'authorShareBasisLumina',
    'authorShareLumina',
    'payoutEligible',
  ],
  separationPolicy: {
    chapterRevenueAndSeasonDiscountSameField: false,
    aiArtistParticipationIncludedInAuthorShare: false,
    authorShareIncludesUnsettledOnly: true,
    clientSubmittedRevenueTrusted: false,
    clientSubmittedDiscountTrusted: false,
    clientSubmittedShareTrusted: false,
  },
  allocationSkeleton: {
    version: '2026-06-23.story-author-revenue-bucket-allocation.v1',
    calculationOrder: [
      'load_completed_chapter_purchase_revenue',
      'allocate_completed_season_bundle_revenue_to_chapter',
      'subtract_refund_or_chargeback_adjustment',
      'reserve_ai_character_companion_participation_cost',
      'calculate_story_author_share_preview',
      'return_read_only_projection_without_settlement_or_payout_mutation',
    ],
    chapterRevenue: {
      bucket: 'chapter_direct_revenue',
      source: 'completed_chapter_single_purchase',
      grossField: 'chapterGrossLumina',
      refundAdjustmentField: 'refundAdjustedLumina',
      seasonBundleRevenueIncluded: false,
    },
    seasonRevenue: {
      bucket: 'season_bundle_allocated_revenue',
      source: 'completed_season_bundle_purchase_allocated_per_chapter',
      allocatedField: 'seasonAllocatedGrossLumina',
      discountField: 'seasonDiscountLumina',
      chapterDirectRevenueIncluded: false,
    },
    aiCompanionCost: {
      bucket: 'ai_character_companion_participation_cost',
      source: 'story_session_companion_roster_confirmed_by_server',
      amountField: 'aiParticipationCostLumina',
      deductedBeforeAuthorShare: true,
      providerCostPayloadReturned: false,
    },
    authorPreview: {
      basisField: 'authorShareBasisLumina',
      previewField: 'authorShareLumina',
      finalSettlementAuthority: false,
      payoutEligible: false,
    },
  },
  noMutationPolicy: {
    contractAddsEndpoint: false,
    paymentMutation: false,
    refundMutation: false,
    settlementMutation: false,
    payoutMutation: false,
    walletMutation: false,
    walletLedgerMutation: false,
  },
  responsePolicy: {
    readOnly: true,
    stableCodeRequired: true,
    messageKeyRequired: true,
    rawUserFacingEnglishCopy: false,
    privateReaderIdentifierReturned: false,
    payoutAccountReturned: false,
    internalFormulaReturned: false,
  },
} as const;

export const STORY_STAGE_SESSION_RETENTION_POLICY_CONTRACT = {
  version: '2026-06-18.story-stage-session-retention-policy.v1',
  status: 'contract_only',
  endpoints: {
    continueSession: 'GET /api/v1/me/story-stage/sessions/:sessionId/continue',
    sessionList: 'GET /api/v1/me/story-stage/sessions',
  },
  sessionStatuses: ['active', 'paused', 'archived_inactive'],
  archivePolicy: {
    inactivityDays: 30,
    clockSource: 'server_time',
    trigger: 'no_user_progress_for_30_days',
    action: 'mark_session_archived_inactive',
    hardDeleteSession: false,
    deleteChoices: false,
    deleteProgress: false,
  },
  cleanupReadModel: {
    version: '2026-06-23.story-continuation-expiry-cleanup-read-model.v1',
    readModel: 'story_continuation_expiry_cleanup_preview',
    endpoint: 'GET /api/v1/me/story-stage/sessions/continuation-cleanup',
    enabled: false,
    readOnly: true,
    inactivityThresholdDays: 30,
    staleSessionStatusKey: 'archived_inactive',
    projectionFields: [
      'sessionId',
      'storyPackId',
      'currentChapterId',
      'lastProgressAt',
      'inactiveDays',
      'expiryCandidate',
      'statusKey',
      'dropAvailability',
      'entitlementRetention',
      'companionRetention',
    ],
    stateSeparation: {
      sessionArchivedInactive: true,
      chapterEntitlementDeleted: false,
      seasonEntitlementDeleted: false,
      purchasedHistoryDeleted: false,
      companionRosterDeleted: false,
      refundCandidateCreated: false,
    },
    dropAvailability: {
      userCanDropArchivedSession: true,
      dropDoesNotCancelEntitlement: true,
      dropDoesNotRefundWallet: true,
      messageKey: 'storyStage.session.archive.dropAvailable',
    },
    companionRetention: {
      selectedAiCompanionRetained: true,
      companionContextMayBeSummarized: true,
      paidCompanionAccessCanceled: false,
    },
  },
  purchaseHistoryPolicy: {
    purchaseHistoryRetained: true,
    chapterEntitlementsRetained: true,
    seasonEntitlementsRetained: true,
    archivedSessionCancelsPurchase: false,
    archivedSessionRefundsPurchase: false,
    restoreRequiresNewPurchase: false,
  },
  copyAndStatusPolicy: {
    rawStatusAsCopy: false,
    rawUserFacingEnglishCopy: false,
    titleKey: 'storyStage.session.archive.title',
    bodyKey: 'storyStage.session.archive.body',
    ctaKey: 'storyStage.session.archive.continueCta',
    statusKey: 'storyStage.session.status.archivedInactive',
    copyMustExplainPurchaseHistoryRetained: true,
  },
  mutationPolicy: {
    contractAddsArchiveJob: false,
    userProgressMutation: false,
    hardDeleteMutation: false,
    purchaseCancellationMutation: false,
    walletMutation: false,
    refundMutation: false,
    settlementMutation: false,
    payoutMutation: false,
  },
  responsePolicy: {
    stableCodeRequired: true,
    messageKeyRequired: true,
    purchaseHistoryReturnedAsOwnerOnly: true,
    privateAuthorNotesReturned: false,
  },
} as const;

export const STORY_STAGE_AUTHOR_INTERRUPTION_REFUND_PENALTY_READ_MODEL = {
  version: '2026-06-18.story-stage-author-interruption-refund-penalty.v1',
  status: 'read_model_contract_only',
  readModel: 'story_author_interruption_refund_penalty_preview',
  triggerPolicy: {
    events: ['long_hiatus', 'author_discontinued'],
    longHiatusThresholdSource: 'story_stage_policy.author_inactivity_days',
    authorDiscontinuedSource: 'story_packs.publication_status',
    manualOperatorReviewRequired: true,
  },
  refundCandidatePolicy: {
    completedChaptersRefundEligible: false,
    completedChaptersReason: 'reader_already_completed_chapter',
    incompleteStartedChaptersPartialRefundCandidate: true,
    unpublishedPurchasedChaptersPartialRefundCandidate: true,
    futureSeasonChaptersCandidate: true,
    refundAmountSource: 'server_calculated_unconsumed_chapter_value_lumina',
    clientSubmittedRefundAmountTrusted: false,
  },
  settlementPenaltyPreview: {
    penaltyAppliesTo: 'future_unsettled_story_author_share_only',
    alreadySettledPayoutsReopened: false,
    authorRateChangeMutation: false,
    payoutHoldMutation: false,
    requiresOperatorDecision: true,
  },
  readOnlyAuditGuard: {
    version: '2026-06-22.story-refund-penalty-read-only-audit-guard.v1',
    status: 'read_model_contract_only',
    conflictPolicy: 'separate_refund_candidates_from_author_penalty_preview',
    chapterBuckets: {
      completed: {
        refundEligible: false,
        authorPenaltyApplies: false,
        settlementRateLocked: true,
        reasonKey: 'reader_already_completed_chapter',
      },
      incompleteStarted: {
        refundEligible: true,
        authorPenaltyApplies: false,
        settlementRateLocked: false,
        reasonKey: 'unconsumed_started_chapter',
      },
      discontinuedFuture: {
        refundEligible: true,
        authorPenaltyApplies: true,
        settlementRateLocked: false,
        reasonKey: 'author_discontinued_future_chapter',
      },
    },
    auditProjectionFields: [
      'chapterBucket',
      'refundCandidateState',
      'authorPenaltyState',
      'settlementRateLocked',
      'refundMutationAllowed',
      'settlementMutationAllowed',
      'payoutMutationAllowed',
    ],
    forbiddenMergedStates: [
      'completed_chapter_refund_and_penalty_same_row',
      'wallet_refund_and_settlement_rate_update_same_action',
      'payout_hold_and_user_refund_credit_same_action',
    ],
  },
  projectionFields: [
    'storyPackId',
    'storySeasonId',
    'affectedChapterIds',
    'completedChapterIdsExcluded',
    'partialRefundCandidateChapterIds',
    'estimatedRefundLumina',
    'authorPenaltyPreview',
    'reviewRequired',
  ],
  responsePolicy: {
    stableCodeRequired: true,
    messageKeyRequired: true,
    rawUserFacingEnglishCopy: false,
    privateAuthorNotesReturned: false,
    userPaymentCredentialReturned: false,
  },
  mutationPolicy: {
    contractAddsRefundEndpoint: false,
    refundMutation: false,
    walletCredit: false,
    walletDebit: false,
    walletLedgerMutation: false,
    settlementRateMutation: false,
    settlementMutation: false,
    payoutMutation: false,
  },
} as const;

export const STORY_STAGE_CONTRACT = {
  version: '2026-06-18.story-stage-contract.v1',
  freePrologueEntitlementGuard: STORY_STAGE_FREE_PROLOGUE_ENTITLEMENT_GUARD,
  purchaseLedgerSkeleton: STORY_STAGE_PURCHASE_LEDGER_SKELETON,
  aiArtistSettlementSplitSkeleton:
    STORY_STAGE_AI_ARTIST_SETTLEMENT_SPLIT_SKELETON,
  authorRevenueReadModel: STORY_STAGE_AUTHOR_REVENUE_READ_MODEL_CONTRACT,
  sessionRetentionPolicy: STORY_STAGE_SESSION_RETENTION_POLICY_CONTRACT,
  authorInterruptionRefundPenaltyReadModel:
    STORY_STAGE_AUTHOR_INTERRUPTION_REFUND_PENALTY_READ_MODEL,
} as const;

export const STORY_STAGE_PACK_CHAPTER_SESSION_CONTRACT = {
  version: '2026-06-18.story-stage-pack-chapter-session-skeleton.v1',
  status: 'backend_contract_skeleton_only',
  scope: {
    surfaces: ['story_pack', 'story_chapter', 'story_session', 'story_choice'],
    implementationReady: false,
    readModelOnly: true,
    publicMutationEnabled: false,
  },
  apiContracts: {
    storyPackList: {
      method: 'GET',
      path: '/api/v1/story-packs',
      enabled: false,
      authRequired: false,
      response: 'StoryPack list projection',
    },
    storyPackDetail: {
      method: 'GET',
      path: '/api/v1/story-packs/:packSlug',
      enabled: false,
      authRequired: false,
      response: 'StoryPack detail with safe chapter list projection',
    },
    storyChapterDetail: {
      method: 'GET',
      path: '/api/v1/story-packs/:packSlug/chapters/:chapterNo',
      enabled: false,
      authRequired: false,
      response: 'StoryChapter detail projection',
    },
    storySessionCreate: {
      method: 'POST',
      path: '/api/v1/story-packs/:packSlug/sessions',
      enabled: false,
      authRequired: true,
      idempotencyRequired: true,
      response: 'StorySession projection',
    },
    storyChoiceList: {
      method: 'GET',
      path: '/api/v1/story-sessions/:sessionId/choices',
      enabled: false,
      authRequired: true,
      response: 'StoryChoice list projection',
    },
  },
  storyPack: {
    idField: 'story_packs.id',
    slugField: 'story_packs.slug',
    pricingModes: ['free', 'paid', 'mixed'],
    lifecycleStatuses: [
      'draft',
      'serializing',
      'completed',
      'hiatus',
      'season_ended',
      'archived',
    ],
    publicListStatuses: ['serializing', 'completed', 'hiatus', 'season_ended'],
    fields: [
      'id',
      'slug',
      'title',
      'summary',
      'coverImageUrl',
      'pricingMode',
      'lifecycleStatus',
      'chapterCount',
      'freeChapterCount',
      'paidChapterCount',
      'ageRatingKey',
      'genreKeys',
      'updatedAt',
    ],
    privateFieldsReturned: false,
  },
  storyChapter: {
    idField: 'story_chapters.id',
    packReferenceField: 'story_chapters.storyPackId',
    chapterNoField: 'story_chapters.chapterNo',
    pricingModes: ['free', 'paid'],
    lifecycleStatuses: [
      'draft',
      'scheduled',
      'published',
      'paused',
      'season_finale',
      'archived',
    ],
    publicReadableStatuses: ['published', 'paused', 'season_finale'],
    paidAccessPolicy: {
      freeChapterReadableWithoutPurchase: true,
      paidChapterRequiresEntitlement: true,
      previewFieldsForLockedPaidChapter: [
        'id',
        'chapterNo',
        'title',
        'summary',
        'pricingMode',
        'priceLumina',
        'locked',
      ],
      lockedBodyReturned: false,
    },
    paidEntitlementServerGuard: {
      version: '2026-06-24.story-paid-chapter-entitlement-server-guard.v1',
      status: 'read_model_contract_only',
      readOnly: true,
      sourceOfTruth: {
        chapterEntitlement: 'user_entitlements.story_chapter_access',
        seasonEntitlement: 'user_entitlements.story_season_access',
        purchaseLedger: 'story_purchase_ledger.granted',
        chapterPublication: 'story_chapters.publicReadableStatuses',
      },
      serverDecisionOrder: [
        'load_chapter_by_pack_slug_and_chapter_no',
        'return_body_when_chapter_is_free',
        'require_authenticated_reader_for_paid_chapter_body',
        'load_user_chapter_entitlement',
        'load_user_season_entitlement_for_chapter',
        'verify_purchase_ledger_status_granted',
        'return_locked_preview_when_entitlement_missing',
      ],
      entitlementScopes: {
        chapterSingle: {
          entitlementType: 'story_chapter_access',
          referenceType: 'story_chapter',
          grantsBodyAccessTo: 'exact_chapter_only',
        },
        seasonBundle: {
          entitlementType: 'story_season_access',
          referenceType: 'story_season',
          grantsBodyAccessTo: 'published_chapters_in_season',
          futureChapterAccessSource: 'chapter_publication_status',
        },
      },
      clientTrustPolicy: {
        clientSubmittedPurchasedTrusted: false,
        clientSubmittedEntitlementTrusted: false,
        clientSubmittedWalletBalanceTrusted: false,
        clientSubmittedPriceTrusted: false,
      },
      responsePolicy: {
        lockedBodyReturned: false,
        entitlementIdReturnedToReader: false,
        purchaseLedgerIdReturned: false,
        walletLedgerIdReturned: false,
        stableMessageKeyRequired: true,
        lockedMessageKey: 'storyStage.chapter.locked',
      },
      mutationPolicy: {
        paymentMutation: false,
        walletDebit: false,
        walletCredit: false,
        walletLedgerMutation: false,
        entitlementGrant: false,
        refundMutation: false,
        settlementMutation: false,
        payoutMutation: false,
      },
    },
    fields: [
      'id',
      'packId',
      'chapterNo',
      'title',
      'summary',
      'body',
      'pricingMode',
      'priceLumina',
      'lifecycleStatus',
      'publishedAt',
    ],
  },
  storySession: {
    idField: 'story_sessions.id',
    ownerField: 'story_sessions.userId',
    packReferenceField: 'story_sessions.storyPackId',
    chapterReferenceField: 'story_sessions.currentChapterId',
    lifecycleStatuses: [
      'active',
      'paused',
      'completed',
      'abandoned',
      'expired',
    ],
    source: 'server_created_story_session_after_entitlement_check',
    idempotencyScope: 'story-session:<userId>:<packSlug>:<client-idempotency-key>',
    replaySameRequest: true,
    conflictOnChangedFingerprint: true,
    aiProviderCallOnCreate: false,
    walletMutationOnCreate: false,
    imageVideoGenerationOnCreate: false,
  },
  storyChoice: {
    idField: 'story_choices.id',
    sessionReferenceField: 'story_choices.storySessionId',
    defaultCount: 3,
    maxCount: 5,
    choiceTypes: ['dialogue', 'action', 'investigate', 'travel', 'wait'],
    fields: [
      'id',
      'sessionId',
      'chapterId',
      'choiceNo',
      'labelKey',
      'body',
      'choiceType',
      'available',
      'disabledReasonKey',
    ],
    rawModelPromptReturned: false,
    providerPayloadReturned: false,
  },
  validationOrder: [
    'auth_optional_for_public_pack_reads',
    'validate_pack_slug',
    'load_public_story_pack',
    'validate_chapter_identifier_when_present',
    'load_public_or_entitled_chapter_projection',
    'require_auth_for_session_or_choice_reads',
    'check_paid_chapter_entitlement_before_body_projection',
    'validate_idempotency_key_for_session_create',
    'return_contract_projection_without_mutation',
  ],
  noMutationPolicy: {
    paymentOrderCreate: false,
    walletDebit: false,
    luminaDebit: false,
    entitlementGrant: false,
    storySessionCreateEnabled: false,
    storyStateMutation: false,
    storyChoiceSubmit: false,
    aiProviderCall: false,
    imageGeneration: false,
    videoGeneration: false,
    notificationCreate: false,
    settlementMutation: false,
    payoutMutation: false,
  },
  privacy: {
    rawUserEmailReturned: false,
    rawPaymentLedgerIdReturned: false,
    providerPromptReturned: false,
    providerResponseReturned: false,
    adminMemoReturned: false,
    internalModerationNoteReturned: false,
  },
} as const;
