export const STORY_STAGE_PACK_CHAPTER_SESSION_CONTRACT = {
  version: '2026-06-18.story-stage-pack-chapter-session-skeleton.v1',
  status: 'backend_contract_skeleton_only',
  scope: {
    surfaces: ['story_pack', 'story_chapter', 'story_session', 'story_choice'],
    implementationReady: false,
    readModelOnly: true,
    publicMutationEnabled: false,
  },
  apiContracts: {
    storyPackList: {
      method: 'GET',
      path: '/api/v1/story-packs',
      enabled: false,
      authRequired: false,
      response: 'StoryPack list projection',
    },
    storyPackDetail: {
      method: 'GET',
      path: '/api/v1/story-packs/:packSlug',
      enabled: false,
      authRequired: false,
      response: 'StoryPack detail with safe chapter list projection',
    },
    storyChapterDetail: {
      method: 'GET',
      path: '/api/v1/story-packs/:packSlug/chapters/:chapterNo',
      enabled: false,
      authRequired: false,
      response: 'StoryChapter detail projection',
    },
    storySessionCreate: {
      method: 'POST',
      path: '/api/v1/story-packs/:packSlug/sessions',
      enabled: false,
      authRequired: true,
      idempotencyRequired: true,
      response: 'StorySession projection',
    },
    storyChoiceList: {
      method: 'GET',
      path: '/api/v1/story-sessions/:sessionId/choices',
      enabled: false,
      authRequired: true,
      response: 'StoryChoice list projection',
    },
  },
  storyPack: {
    idField: 'story_packs.id',
    slugField: 'story_packs.slug',
    pricingModes: ['free', 'paid', 'mixed'],
    lifecycleStatuses: [
      'draft',
      'serializing',
      'completed',
      'hiatus',
      'season_ended',
      'archived',
    ],
    publicListStatuses: ['serializing', 'completed', 'hiatus', 'season_ended'],
    fields: [
      'id',
      'slug',
      'title',
      'summary',
      'coverImageUrl',
      'pricingMode',
      'lifecycleStatus',
      'chapterCount',
      'freeChapterCount',
      'paidChapterCount',
      'ageRatingKey',
      'genreKeys',
      'updatedAt',
    ],
    privateFieldsReturned: false,
  },
  storyChapter: {
    idField: 'story_chapters.id',
    packReferenceField: 'story_chapters.storyPackId',
    chapterNoField: 'story_chapters.chapterNo',
    pricingModes: ['free', 'paid'],
    lifecycleStatuses: [
      'draft',
      'scheduled',
      'published',
      'paused',
      'season_finale',
      'archived',
    ],
    publicReadableStatuses: ['published', 'paused', 'season_finale'],
    paidAccessPolicy: {
      freeChapterReadableWithoutPurchase: true,
      paidChapterRequiresEntitlement: true,
      previewFieldsForLockedPaidChapter: [
        'id',
        'chapterNo',
        'title',
        'summary',
        'pricingMode',
        'priceLumina',
        'locked',
      ],
      lockedBodyReturned: false,
    },
    fields: [
      'id',
      'packId',
      'chapterNo',
      'title',
      'summary',
      'body',
      'pricingMode',
      'priceLumina',
      'lifecycleStatus',
      'publishedAt',
    ],
  },
  storySession: {
    idField: 'story_sessions.id',
    ownerField: 'story_sessions.userId',
    packReferenceField: 'story_sessions.storyPackId',
    chapterReferenceField: 'story_sessions.currentChapterId',
    lifecycleStatuses: [
      'active',
      'paused',
      'completed',
      'abandoned',
      'expired',
    ],
    source: 'server_created_story_session_after_entitlement_check',
    idempotencyScope: 'story-session:<userId>:<packSlug>:<client-idempotency-key>',
    replaySameRequest: true,
    conflictOnChangedFingerprint: true,
    aiProviderCallOnCreate: false,
    walletMutationOnCreate: false,
    imageVideoGenerationOnCreate: false,
  },
  storyChoice: {
    idField: 'story_choices.id',
    sessionReferenceField: 'story_choices.storySessionId',
    defaultCount: 3,
    maxCount: 5,
    choiceTypes: ['dialogue', 'action', 'investigate', 'travel', 'wait'],
    fields: [
      'id',
      'sessionId',
      'chapterId',
      'choiceNo',
      'labelKey',
      'body',
      'choiceType',
      'available',
      'disabledReasonKey',
    ],
    rawModelPromptReturned: false,
    providerPayloadReturned: false,
  },
  validationOrder: [
    'auth_optional_for_public_pack_reads',
    'validate_pack_slug',
    'load_public_story_pack',
    'validate_chapter_identifier_when_present',
    'load_public_or_entitled_chapter_projection',
    'require_auth_for_session_or_choice_reads',
    'check_paid_chapter_entitlement_before_body_projection',
    'validate_idempotency_key_for_session_create',
    'return_contract_projection_without_mutation',
  ],
  noMutationPolicy: {
    paymentOrderCreate: false,
    walletDebit: false,
    luminaDebit: false,
    entitlementGrant: false,
    storySessionCreateEnabled: false,
    storyStateMutation: false,
    storyChoiceSubmit: false,
    aiProviderCall: false,
    imageGeneration: false,
    videoGeneration: false,
    notificationCreate: false,
    settlementMutation: false,
    payoutMutation: false,
  },
  privacy: {
    rawUserEmailReturned: false,
    rawPaymentLedgerIdReturned: false,
    providerPromptReturned: false,
    providerResponseReturned: false,
    adminMemoReturned: false,
    internalModerationNoteReturned: false,
  },
} as const;
