export const STORY_AI_COMPANION_CONTEXT_BOUNDARY_CONTRACT = {
  version: '2026-06-18.story-ai-companion-context-boundary.v1',
  status: 'context_boundary_contract_only',
  enabled: false,
  scope: {
    maxCompanionArtistsPerSession: 5,
    activeSpeakersPerScene: { min: 1, recommended: [2, 3], max: 3 },
    nonActiveCompanionRoles: ['cameo', 'background', 'offscreen_reference'],
    providerCallEnabled: false,
    storyMutationEnabled: false,
  },
  participationBudget: {
    version: '2026-06-23.story-ai-companion-budget-guard.v1',
    targetMaxParticipantsIncludingPlayer: 6,
    playerIncluded: true,
    maxAiCompanionsPerSession: 5,
    freePrologue: {
      maxAiCompanions: 1,
      allowedModes: ['solo_player', 'one_ai_companion'],
      companionAddCostLumina: 0,
      companionSwapCostLumina: 0,
      paidExpansionAllowed: false,
    },
    paidStory: {
      maxAiCompanions: 5,
      companionAddCostPolicy: 'server_story_product_policy_required',
      companionSwapCostPolicy: 'server_story_product_policy_required',
      freeCompanionCarryOverAllowed: true,
      clientSubmittedCostAccepted: false,
    },
    readModelSelectionProjection: {
      version: '2026-06-25.story-ai-companion-limit-read-model.v1',
      projectionKey: 'storyAiCompanionSelectionProjection',
      enabled: false,
      freePrologue: {
        maxSelectableAiCompanions: 1,
        paidExpansionAllowed: false,
        addCostSource: 'none',
        swapCostSource: 'none',
      },
      paidStory: {
        maxSelectableAiCompanions: 5,
        addCostSource: 'server_story_product_policy',
        swapCostSource: 'server_story_product_policy',
        costPreviewOnly: true,
        clientSubmittedCostTrusted: false,
      },
      rosterChangePolicy: {
        companionAddMayRequireAdditionalCost: true,
        companionSwapMayRequireAdditionalCost: true,
        existingChapterEntitlementPreserved: true,
        existingSeasonEntitlementPreserved: true,
        previousChapterCompanionRosterImmutable: true,
        nextChapterUsesLatestConfirmedRoster: true,
      },
      mutationPolicy: {
        selectionSubmitEnabled: false,
        paymentMutation: false,
        refundMutation: false,
        walletMutation: false,
        settlementMutation: false,
        payoutMutation: false,
        storyProgressMutation: false,
      },
    },
    contextBudgetGuard: {
      maxActiveSpeakersPerScene: 3,
      maxBackgroundCompanionsSummarized: 2,
      downgradeOverflowCompanionsTo: ['cameo', 'background', 'offscreen_reference'],
      providerContextOverflowBehavior: 'summarize_or_exclude_before_provider',
      rawPromptBudgetReturned: false,
    },
    noMutationPolicy: {
      paymentMutation: false,
      walletMutation: false,
      luminaMutation: false,
      storyProgressMutation: false,
      providerCall: false,
    },
  },
  contextLayers: {
    world: {
      priority: 1,
      source: 'story_pack_world_bible',
      immutableDuringScene: true,
      playerCanOverride: false,
    },
    scene: {
      priority: 2,
      source: 'current_chapter_scene_state',
      includes: ['location', 'timeOfDay', 'sceneGoal', 'knownConstraints'],
    },
    artistPersona: {
      priority: 3,
      source: 'approved_artist_persona_tone_profile',
      maxActiveProfilesInjected: 3,
      maxBackgroundProfilesSummarized: 2,
      rawPromptReturned: false,
    },
    playerState: {
      priority: 4,
      source: 'story_session_player_state_projection',
      includes: ['presence', 'knownFacts', 'inventoryHints', 'relationshipHints'],
    },
  },
  companionRoles: {
    activeSpeaker: {
      canSpeakInScene: true,
      canDriveChoiceText: true,
      requiresPersonaToneContext: true,
      maxPerScene: 3,
    },
    cameo: {
      canSpeakInScene: 'brief_only',
      canDriveChoiceText: false,
      requiresPersonaToneContext: 'summary_only',
      maxPerScene: 5,
    },
    background: {
      canSpeakInScene: false,
      canDriveChoiceText: false,
      requiresPersonaToneContext: false,
      maxPerScene: 5,
    },
    offscreenReference: {
      canSpeakInScene: false,
      canDriveChoiceText: false,
      requiresPersonaToneContext: 'relationship_or_memory_key_only',
      maxPerScene: 5,
    },
  },
  boundaryRules: {
    preserveWorldCanon: true,
    preserveArtistTone: true,
    preserveSceneObjective: true,
    preventPersonaMerge: true,
    preventAllCompanionsSpeakingAtOnce: true,
    preventBackgroundRoleFromSolvingScene: true,
    preventPlayerChoiceFromOverridingCanon: true,
    rawProviderInstructionReturned: false,
  },
  validationOrder: [
    'load_story_session_context_projection',
    'load_selected_companion_artist_profiles',
    'cap_companion_count_at_five',
    'select_two_to_three_active_speakers_for_scene',
    'downgrade_remaining_companions_to_cameo_or_background',
    'compose_context_layers_without_provider_call',
    'return_boundary_projection_without_story_or_chat_mutation',
  ],
  noMutationPolicy: {
    providerCall: false,
    chatMessageCreate: false,
    storyStateMutation: false,
    companionRosterMutation: false,
    walletMutation: false,
    luminaMutation: false,
    paymentMutation: false,
    settlementMutation: false,
    payoutMutation: false,
  },
  privacy: {
    rawPersonaPromptReturned: false,
    rawWorldBibleReturned: false,
    providerPayloadReturned: false,
    privateArtistNotesReturned: false,
    adminMemoReturned: false,
  },
} as const;
