export const STORY_REVIEW_READER_PROJECTION_CONTRACT = {
  version: '2026-06-18.story-review-reader-projection.v1',
  status: 'projection_contract_only',
  enabled: false,
  surfaces: [
    'story_pack_comments',
    'story_pack_ratings',
    'story_chapter_comments',
    'story_chapter_ratings',
    'completed_reader_badge',
  ],
  commentPolicy: {
    packComments: {
      path: '/api/v1/story-packs/:packSlug/comments',
      enabled: false,
      scope: 'story_pack',
      commenterEligibility: 'paid_reader_or_entitled_reader_only',
    },
    chapterComments: {
      path: '/api/v1/story-packs/:packSlug/chapters/:chapterNo/comments',
      enabled: false,
      scope: 'story_chapter',
      commenterEligibility: 'chapter_entitled_reader_only',
    },
    maxChars: 500,
    rawSpoilerBodyReturnedToNonReader: false,
    rawModerationPayloadReturned: false,
  },
  ratingPolicy: {
    packRatings: {
      path: '/api/v1/story-packs/:packSlug/ratings',
      enabled: false,
      scope: 'story_pack',
      raterEligibility: 'paid_reader_or_entitled_reader_only',
    },
    chapterRatings: {
      path: '/api/v1/story-packs/:packSlug/chapters/:chapterNo/ratings',
      enabled: false,
      scope: 'story_chapter',
      raterEligibility: 'chapter_entitled_reader_only',
    },
    scale: { min: 1, max: 5, step: 1 },
    oneRatingPerUserPerScope: true,
    ratingMutationEnabled: false,
  },
  completedReaderBadge: {
    field: 'reader.badges.completedReader',
    meaning: 'viewer completed every currently published readable chapter',
    evidenceSources: [
      'story_chapter_read_progress.completed_at',
      'story_entitlements.confirmed',
    ],
    trustLevel: 'reader_completion_signal_not_authority_for_payment',
    displayedOnComments: true,
    displayedOnRatings: true,
    rawReadHistoryReturned: false,
  },
  authorReadProjection: {
    version: '2026-06-23.story-author-review-reader-read-projection.v1',
    status: 'read_model_contract_only',
    endpoint: 'GET /api/v1/creator-studio/story-packs/:packId/review-summary',
    auth: {
      authorOwnPackOnly: true,
      backstageReadRequiresPermission: 'story:read',
      nonAuthorDeniedWithoutIdentityLeak: true,
    },
    metrics: [
      'commentCount',
      'ratingCount',
      'averageRating',
      'completedReaderCount',
      'chapterCommentCount',
      'chapterRatingCount',
    ],
    commentPreviewPolicy: {
      maxItems: 20,
      includesSafeBodyPreview: true,
      includesCompletedReaderBadge: true,
      spoilerPreviewRedactedForUnentitledViewer: true,
      moderationHiddenCommentsExcluded: true,
    },
    ratingBreakdownPolicy: {
      buckets: [1, 2, 3, 4, 5],
      viewerSpecificRatingReturned: false,
      anonymousAggregateOnly: true,
    },
    completedReaderPolicy: {
      countOnlyForAuthor: true,
      readerListReturned: false,
      rawReadHistoryReturned: false,
      paymentAuthority: false,
    },
    privacy: {
      readerUserIdReturned: false,
      rawUserEmailReturned: false,
      paymentLedgerIdReturned: false,
      entitlementIdReturned: false,
      rawReadHistoryReturned: false,
      rawReportReasonReturned: false,
      moderationNotesReturned: false,
    },
    noMutationPolicy: {
      commentMutation: false,
      ratingMutation: false,
      badgeGrantMutation: false,
      notificationMutation: false,
      walletMutation: false,
      settlementMutation: false,
      payoutMutation: false,
    },
  },
  projectionFields: {
    commentItem: [
      'id',
      'scope',
      'body',
      'author.displayName',
      'author.publicHandle',
      'readerBadges',
      'createdAt',
      'viewer.canEdit',
      'viewer.canDelete',
    ],
    ratingSummary: [
      'scope',
      'averageRating',
      'ratingCount',
      'viewer.rating',
      'viewer.canRate',
      'viewer.disabledReasonKey',
    ],
    authorReviewSummary: [
      'packId',
      'commentCount',
      'ratingCount',
      'averageRating',
      'completedReaderCount',
      'chapterBreakdown',
      'safeCommentPreviews',
      'ratingBuckets',
    ],
  },
  validationOrder: [
    'load_public_story_pack_or_chapter',
    'authorize_author_or_public_reader_scope',
    'require_auth_for_comment_or_rating_write',
    'check_reader_entitlement_for_comment_or_rating',
    'check_completed_reader_badge_projection',
    'aggregate_author_review_summary_without_reader_identity',
    'return_projection_without_comment_rating_report_or_notification_mutation',
  ],
  noMutationPolicy: {
    commentCreate: false,
    commentUpdate: false,
    commentDelete: false,
    ratingCreate: false,
    ratingUpdate: false,
    reportCreate: false,
    notificationCreate: false,
    badgeGrantMutation: false,
    walletMutation: false,
    luminaMutation: false,
    paymentMutation: false,
    settlementMutation: false,
    payoutMutation: false,
  },
  privacy: {
    rawUserEmailReturned: false,
    rawPaymentLedgerIdReturned: false,
    rawReadHistoryReturned: false,
    rawReportReasonReturned: false,
    moderationNotesReturned: false,
  },
} as const;
