export const STORY_CHOICE_TIMELINE_READ_MODEL_CONTRACT = {
  version: '2026-06-18.story-choice-timeline-read-model.v1',
  status: 'read_model_contract_only',
  enabled: false,
  surfaces: ['story_session_choices', 'story_major_event_timeline'],
  choicePolicy: {
    defaultChoiceCount: 3,
    maxChoiceCount: 5,
    minChoiceCount: 1,
    expansionRule:
      'server may expose up to five choices only when scene complexity requires it',
    rawGeneratedChoiceReturned: false,
    clientSubmittedChoiceSetAllowed: false,
  },
  choiceProjection: {
    field: 'story.choices[]',
    fields: [
      'id',
      'choiceNo',
      'titleKey',
      'body',
      'choiceType',
      'availability',
      'disabledReasonKey',
      'scenePresence',
      'expectedTimelineEffect',
    ],
    choiceTypes: [
      'dialogue',
      'physical_action',
      'investigation',
      'travel',
      'wait',
      'letter_or_report',
    ],
    availabilityStates: ['available', 'locked', 'disabled'],
    rawEnumAsUiCopy: false,
  },
  scenePresencePolicy: {
    userPresent: {
      key: 'present',
      choiceMode: 'direct_intervention',
      allowedChoiceTypes: [
        'dialogue',
        'physical_action',
        'investigation',
        'travel',
        'wait',
      ],
      timelineNarrationMode: 'firsthand_scene',
      canInterveneInCurrentScene: true,
    },
    userNearby: {
      key: 'nearby',
      choiceMode: 'limited_intervention',
      allowedChoiceTypes: ['travel', 'wait', 'letter_or_report'],
      timelineNarrationMode: 'partial_witness_or_delayed_report',
      canInterveneInCurrentScene: false,
    },
    userFarAway: {
      key: 'far_away',
      choiceMode: 'indirect_information',
      allowedChoiceTypes: ['letter_or_report', 'wait', 'travel'],
      timelineNarrationMode: 'letter_rumor_report',
      canInterveneInCurrentScene: false,
    },
  },
  majorEventTimeline: {
    field: 'story.timeline.majorEvents[]',
    eventKinds: [
      'public_incident',
      'private_revelation',
      'relationship_shift',
      'world_state_change',
      'chapter_climax',
      'season_marker',
    ],
    fields: [
      'id',
      'eventNo',
      'eventKind',
      'titleKey',
      'summary',
      'chapterNo',
      'scenePresence',
      'playerKnowledgeState',
      'occurredAtStoryTime',
      'revealedAtStoryTime',
    ],
    playerKnowledgeStates: [
      'witnessed',
      'heard_as_rumor',
      'received_report',
      'unknown_to_player',
    ],
    privateSpoilerBodyReturnedWhenUnknown: false,
    rawAuthorNotesReturned: false,
  },
  timelineAnchorReadModel: {
    version: '2026-06-23.story-timeline-anchor-read-model.v1',
    status: 'read_model_contract_only',
    endpoint: 'GET /api/v1/story-sessions/:sessionId/timeline-anchors',
    sourceOfTruth: 'story_timeline_anchors',
    canonicalOrdering: {
      orderField: 'anchorNo',
      stableTieBreakers: ['occurredAtStoryTime', 'id'],
      clientSubmittedOrderTrusted: false,
      branchLocalEventMayNotReorderCanonicalAnchors: true,
    },
    anchorKinds: [
      'world_event',
      'regional_incident',
      'character_milestone',
      'faction_shift',
      'chapter_climax',
      'season_marker',
    ],
    projectionFields: [
      'anchorId',
      'anchorNo',
      'anchorKind',
      'titleKey',
      'summaryKey',
      'regionKey',
      'branchKey',
      'storyTimeKey',
      'playerKnowledgeState',
      'deliveryMode',
      'interventionChoiceKeys',
    ],
    regionBranchPolicy: {
      userSameRegion: {
        deliveryMode: 'scene_or_direct_news',
        canIntervene: true,
        allowedChoiceTypes: ['dialogue', 'physical_action', 'investigation'],
      },
      userDifferentRegion: {
        deliveryMode: 'delayed_report_or_rumor',
        canIntervene: false,
        allowedChoiceTypes: ['travel', 'letter_or_report', 'wait'],
      },
      userDifferentBranch: {
        deliveryMode: 'canonical_summary_only',
        canIntervene: false,
        allowedChoiceTypes: ['letter_or_report', 'wait'],
      },
    },
    playerKnowledgeStates: [
      'witnessed',
      'informed',
      'rumor',
      'not_yet_revealed',
    ],
    continuityGuard: {
      pastAnchorMutationAllowed: false,
      futureAnchorSpoilerReturned: false,
      branchChoiceCanHideAnchor: false,
      branchChoiceCanCreateLocalConsequence: true,
      canonicalAnchorMustRemainAddressable: true,
    },
    responsePolicy: {
      stableKeysOnly: true,
      rawEnumAsUiCopy: false,
      rawAuthorNotesReturned: false,
      providerPromptReturned: false,
      hiddenFutureTimelineReturned: false,
    },
    noMutationPolicy: {
      storyStateMutation: false,
      anchorCreate: false,
      anchorReorder: false,
      choiceSubmit: false,
      providerCall: false,
      notificationCreate: false,
      walletMutation: false,
      settlementMutation: false,
      payoutMutation: false,
    },
  },
  validationOrder: [
    'load_story_session_or_public_preview',
    'resolve_current_chapter_and_scene',
    'load_canonical_timeline_anchors_in_server_order',
    'resolve_user_scene_presence',
    'filter_choices_by_presence_and_availability',
    'project_major_events_by_player_knowledge',
    'project_timeline_anchors_by_region_branch_and_knowledge',
    'return_read_model_without_story_state_mutation',
  ],
  noMutationPolicy: {
    storyStateMutation: false,
    choiceSubmit: false,
    timelineEventCreate: false,
    aiProviderCall: false,
    aiChoiceGeneration: false,
    notificationCreate: false,
    walletMutation: false,
    luminaMutation: false,
    paymentMutation: false,
    settlementMutation: false,
    payoutMutation: false,
  },
  privacy: {
    rawPromptReturned: false,
    providerPayloadReturned: false,
    hiddenFutureTimelineReturned: false,
    authorPrivateNotesReturned: false,
    moderationNotesReturned: false,
  },
} as const;
