export const DEBUT_AUTH_ACCOUNT_GAP_CONTRACT = {
  version: '2026-05-20.debut-auth-account-gap.v1',
  endpoints: {
    publicPolicy: {
      method: 'GET',
      path: '/api/v1/debut/policy',
      authRequired: false,
      mutation: false,
    },
    submitApplication: {
      method: 'POST',
      path: '/api/v1/debut/applications',
      authRequired: true,
      guard: 'JwtAuthGuard',
      emailVerificationRequired: false,
      passwordRequiredForSocialOnlyUser: false,
      identityProviderRequired: false,
      adultSelfDeclarationRequired: true,
      verifiedMinorBlocked: true,
    },
    materialUploadIntent: {
      method: 'POST',
      path: '/api/v1/debut/application-materials/upload-intents',
      authRequired: true,
      guard: 'JwtAuthGuard',
      visibility: 'private',
    },
    ownerStatus: {
      method: 'GET',
      path: '/api/v1/me/debut-applications/:applicationId/status',
      authRequired: true,
      guard: 'JwtAuthGuard',
      ownerOnly: true,
      mutation: false,
    },
    adminReview: {
      method: 'PATCH',
      path: '/admin/api/v1/debut/applications/:applicationId/review',
      authRequired: true,
      guard: 'AdminAuthGuard + AdminPermissionGuard',
      requiredPermission: '*',
      finalDebutMutation: false,
      contractMutation: false,
      settlementMutation: false,
      payoutMutation: false,
      walletMutation: false,
    },
  },
  accountStates: [
    {
      key: 'logged_out',
      policyAllowed: true,
      applicationSubmitAllowed: false,
      reasonKey: 'auth.required',
    },
    {
      key: 'active_email_unverified',
      policyAllowed: true,
      applicationSubmitAllowed: true,
      emailVerificationWarningKey: 'auth.emailVerification.required',
      note: 'MVP debut application is low-friction; email verification is visible but not a hard gate.',
    },
    {
      key: 'active_email_verified',
      policyAllowed: true,
      applicationSubmitAllowed: true,
    },
    {
      key: 'active_social_only',
      policyAllowed: true,
      applicationSubmitAllowed: true,
      passwordRequired: false,
      setupPasswordAvailableSeparately: true,
    },
    {
      key: 'identity_unverified',
      policyAllowed: true,
      applicationSubmitAllowed: true,
      identityProviderRequired: false,
      niceIntegrationStatus: 'skeleton_not_public_gate',
    },
    {
      key: 'identity_verified_adult',
      policyAllowed: true,
      applicationSubmitAllowed: true,
    },
    {
      key: 'identity_verified_minor',
      policyAllowed: true,
      applicationSubmitAllowed: false,
      reasonCode: 'DEBUT_APPLICANT_MINOR_NOT_ALLOWED',
      messageKey: 'debut.applicant.minorNotAllowed',
    },
    {
      key: 'declared_minor',
      policyAllowed: true,
      applicationSubmitAllowed: false,
      reasonCode: 'DEBUT_APPLICANT_ADULT_CONFIRMATION_REQUIRED',
      messageKey: 'debut.applicant.adultConfirmationRequired',
    },
    {
      key: 'inactive_or_deleted_user',
      policyAllowed: true,
      applicationSubmitAllowed: false,
      reasonKey: 'auth.user.notActive',
    },
  ],
  remainingGaps: [
    {
      key: 'nice_real_provider_connection',
      status: 'deferred',
      owner: 'external_identity_provider_task',
      note: 'NICE/mobile/ipin real callback and signature verification are not connected in this scope.',
    },
    {
      key: 'email_verification_as_hard_gate',
      status: 'not_required_for_mvp',
      owner: 'pm_policy_decision',
      note: 'Server exposes email verification state; debut submit currently stays open to active logged-in users.',
    },
  ],
  identityProviderGapCheck: {
    version: '2026-07-08.debut-identity-provider-gap-check.v1',
    currentMvpProvider: 'phone_number_mvp_or_self_declaration',
    realProviderCallbacksConnected: false,
    realProviderSignatureVerificationConnected: false,
    providerCandidates: [
      {
        provider: 'nice',
        status: 'credentials_and_callbacks_required',
        blocksDebutSubmitToday: false,
      },
      {
        provider: 'ipin',
        status: 'not_connected',
        blocksDebutSubmitToday: false,
      },
      {
        provider: 'mobile_carrier',
        status: 'not_connected',
        blocksDebutSubmitToday: false,
      },
    ],
    debutSubmitPolicy: {
      authRequired: true,
      emailVerificationHardGate: false,
      identityProviderHardGate: false,
      adultSelfDeclarationRequired: true,
      verifiedMinorBlocked: true,
    },
    blockedLiveQa: {
      blockedBy: 'identity provider credentials/callbacks needed',
      nextAction:
        'Confirm approved provider sandbox credentials and callback URLs through a private integration channel.',
      passwordRequestAllowed: false,
      providerSecretRecordAllowed: false,
      rawPiiRecordAllowed: false,
    },
    safeOutputPolicy: {
      recordProviderStatus: true,
      recordStableCodeMessageKey: true,
      recordRawName: false,
      recordRawBirthdate: false,
      recordRawPhone: false,
      recordToken: false,
      recordCookie: false,
      recordProviderPayload: false,
    },
  },
  sensitiveValuesRecorded: false,
} as const;
