export const DEBUT_STATUS_READONLY_QA_FIXTURE_CONTRACT = {
  version: '2026-07-10.debut-status-readonly-qa-fixture.v1',
  endpoint: 'GET /api/v1/qa-fixtures/debut/status-states',
  status: 'contract_only_read_only',
  purpose:
    'Let QA verify debut status screens without submitting, resubmitting, or calling identity providers.',
  allowedOutput: [
    'runId',
    'fixtureStatus',
    'debutStatusKey',
    'publicPath',
    'ctaKey',
    'messageKey',
    'fallbackCopyKey',
    'localeCopyKeys',
    'safe boolean flags',
  ],
  states: [
    {
      debutStatusKey: 'not_started',
      publicPath: '/debut?statusFixture=not-started',
      ctaKey: 'debut.fixture.cta.start',
      messageKey: 'debut.fixture.notStarted',
    },
    {
      debutStatusKey: 'submitted_reviewing',
      publicPath: '/debut?statusFixture=submitted-reviewing',
      ctaKey: 'debut.fixture.cta.wait',
      messageKey: 'debut.fixture.submittedReviewing',
    },
    {
      debutStatusKey: 'needs_more_info',
      publicPath: '/debut?statusFixture=needs-more-info',
      ctaKey: 'debut.fixture.cta.resubmit',
      messageKey: 'debut.fixture.needsMoreInfo',
    },
    {
      debutStatusKey: 'approved',
      publicPath: '/debut?statusFixture=approved',
      ctaKey: 'debut.fixture.cta.approved',
      messageKey: 'debut.fixture.approved',
    },
    {
      debutStatusKey: 'rejected',
      publicPath: '/debut?statusFixture=rejected',
      ctaKey: 'debut.fixture.cta.closed',
      messageKey: 'debut.fixture.rejected',
    },
  ],
  localeContract: {
    requiredLocales: ['ko', 'en', 'ja', 'zh-Hans', 'zh-Hant'],
    fallbackCopyKeyRequired: true,
    rawCopyReturned: false,
  },
  mutationPolicy: {
    applicationSubmit: false,
    applicationResubmit: false,
    identityProviderCall: false,
    phoneVerification: false,
    assetUploadIntent: false,
    adminReviewMutation: false,
    walletMutation: false,
  },
  forbiddenOutput: [
    'phone number',
    'identity token',
    'provider payload',
    'real applicant info',
    'raw email',
    'raw user id',
    'private material URL',
    'storage key',
    'database URL',
  ],
} as const;
