export const STORY_ENTITLEMENT_PURCHASE_TYPES = [
  'chapter_single',
  'season_bundle',
  'free_prologue',
  'operator_adjustment',
] as const;

export const STORY_ENTITLEMENT_STATUSES = [
  'active',
  'revoked',
  'expired',
  'refunded',
] as const;

export const STORY_STAGE_ENTITLEMENT_ADMIN_AUDIT_PROJECTION = {
  version: '2026-06-18.story-entitlement-admin-audit-projection.v1',
  feature: 'story_stage_entitlement_admin_audit_projection',
  status: 'read_model_contract_only',
  audience: 'admin_story_entitlement_operator',
  readOnly: true,
  enabled: false,
  mutationEnabled: false,
  paymentMutationEnabled: false,
  refundMutationEnabled: false,
  walletMutationEnabled: false,
  settlementMutationEnabled: false,
  payoutMutationEnabled: false,
  paidLikeMutationEnabled: false,
  sourceTables: {
    futureEntitlementTable: 'story_entitlements',
    futureAuditTable: 'story_entitlement_audit_events',
    existingWalletLedgerJoin: false,
    existingSettlementJoin: false,
    existingPayoutJoin: false,
  },
  entitlementKinds: {
    chapterSingle: {
      purchaseType: 'chapter_single',
      grantsOneChapter: true,
      grantsWholeSeason: false,
      choiceBillingSeparate: false,
    },
    seasonBundle: {
      purchaseType: 'season_bundle',
      grantsOneChapter: false,
      grantsWholeSeason: true,
      choiceBillingSeparate: false,
    },
    freePrologue: {
      purchaseType: 'free_prologue',
      grantsOneChapter: true,
      grantsWholeSeason: false,
      choiceBillingSeparate: false,
    },
    operatorAdjustment: {
      purchaseType: 'operator_adjustment',
      grantsOneChapter: '<operator selected scope>',
      grantsWholeSeason: '<operator selected scope>',
      choiceBillingSeparate: false,
      requiresAuditReasonKey: true,
    },
  },
  videoGenerationPolicy: {
    separateConsentChargeException: true,
    entitlementImpliesVideoGenerationAccess: false,
    videoGenerationConsentRequired: true,
    videoGenerationWalletMutationInThisProjection: false,
    videoGenerationSettlementMutationInThisProjection: false,
  },
  projectionFields: {
    entitlementId: '<entitlement uuid>',
    userSafeId: '<user uuid or safe public id>',
    storyPackId: '<story pack uuid>',
    seasonId: '<season uuid or null>',
    chapterId: '<chapter uuid or null>',
    purchaseType: STORY_ENTITLEMENT_PURCHASE_TYPES,
    status: STORY_ENTITLEMENT_STATUSES,
    source: STORY_ENTITLEMENT_PURCHASE_TYPES,
    sourceLedgerId: '<safe entitlement source id or null>',
    auditReasonKey: '<stable reason key or null>',
    grantedAt: '<ISO datetime>',
    revokedAt: '<ISO datetime or null>',
    expiresAt: '<ISO datetime or null>',
    choiceBillingSeparate: false,
    videoGenerationConsentChargeSeparate: true,
  },
  adminFilters: {
    userId: 'optional uuid',
    storyPackId: 'optional uuid',
    seasonId: 'optional uuid',
    chapterId: 'optional uuid',
    purchaseType: STORY_ENTITLEMENT_PURCHASE_TYPES,
    status: STORY_ENTITLEMENT_STATUSES,
    take: { default: 50, max: 100 },
    cursor: 'opaque cursor',
  },
  privacy: {
    rawEmailReturned: false,
    rawPaymentProviderIdReturned: false,
    rawPaymentPayloadReturned: false,
    walletLedgerIdReturned: false,
    settlementIdReturned: false,
    payoutIdReturned: false,
    tokenReturned: false,
    cookieReturned: false,
  },
  forbiddenSideEffects: {
    paymentCapture: false,
    refundCreate: false,
    walletDebit: false,
    walletCredit: false,
    settlementAccrual: false,
    payoutAccrual: false,
    paidLike: false,
    chapterChoiceCharge: false,
    videoGenerationCharge: false,
  },
} as const;
