export const AI_PREMIUM_CONTENT_REQUEST_TYPES = [
  'image_single',
  'image_variation',
  'image_reference',
  'video_clip',
  'video_loop',
  'premium_pack',
] as const;

export const AI_PREMIUM_CONTENT_OUTPUT_CLASSES = [
  'image',
  'video',
  'mixed',
] as const;

export const AI_PREMIUM_CONTENT_REQUEST_STATUSES = [
  'draft',
  'submitted',
  'safety_blocked',
  'needs_more_info',
  'queued',
  'generating',
  'provider_failed',
  'awaiting_review',
  'approved',
  'rejected',
  'archived',
] as const;

export const AI_PREMIUM_CONTENT_MODERATION_STATUSES = [
  'pending',
  'cleared',
  'blocked',
  'needs_review',
] as const;

export const AI_PREMIUM_CONTENT_STATUS_COPY_KO = {
  draft: '작성 중',
  submitted: '요청이 접수됐어요',
  safety_blocked: '안전 기준 때문에 진행할 수 없어요',
  needs_more_info: '추가 정보가 필요해요',
  queued: '생성 준비 중이에요',
  generating: '콘텐츠를 만들고 있어요',
  provider_failed: '생성에 실패했어요',
  awaiting_review: '검수 중이에요',
  approved: '콘텐츠가 준비됐어요',
  rejected: '요청이 승인되지 않았어요',
  archived: '보관된 요청이에요',
} as const;

export const AI_PREMIUM_CONTENT_REQUEST_TYPE_POLICY = {
  image_single: {
    outputClass: 'image',
    firstSurface: ['creator_studio', 'backstage'],
    defaultCapability: 'text_to_image',
    humanReviewRequired: true,
  },
  image_variation: {
    outputClass: 'image',
    firstSurface: ['creator_studio', 'backstage'],
    defaultCapability: 'image_to_image',
    humanReviewRequired: true,
  },
  image_reference: {
    outputClass: 'image',
    firstSurface: ['creator_studio'],
    defaultCapability: 'text_to_image',
    humanReviewRequired: true,
  },
  video_clip: {
    outputClass: 'video',
    firstSurface: ['backstage'],
    defaultCapability: 'text_to_video',
    humanReviewRequired: true,
  },
  video_loop: {
    outputClass: 'video',
    firstSurface: ['backstage'],
    defaultCapability: 'image_to_video',
    humanReviewRequired: true,
  },
  premium_pack: {
    outputClass: 'mixed',
    firstSurface: ['backstage'],
    defaultCapability: 'mixed_generation_pack',
    humanReviewRequired: true,
  },
} as const;

export const AI_PREMIUM_CONTENT_STATE_API_CONTRACT = {
  version: '2026-06-02.ai-premium-content-request-state-api-skeleton.v1',
  feature: 'ai_premium_content_request_state',
  status: 'skeleton_ready_mutation_blocked',
  readOnly: true,
  providerCallEnabled: false,
  walletMutationEnabled: false,
  orderMutationEnabled: false,
  settlementMutationEnabled: false,
  payoutMutationEnabled: false,
  paidLikeMutationEnabled: false,
  publicPublishMutationEnabled: false,
  sourceQueues: {
    currentImageQueue: {
      table: 'creator_image_requests',
      mode: 'legacy_image_queue_bridge_candidate',
      liveMutationChangedByThisContract: false,
    },
    currentPremiumVideoCatalog: {
      table: 'premium_video_products',
      mode: 'unlock_catalog_only_not_generation_queue',
      liveMutationChangedByThisContract: false,
    },
    futureUnifiedQueue: {
      table: 'ai_premium_content_requests',
      migrationRequired: true,
      storageEnabled: false,
    },
  },
  requestTypes: AI_PREMIUM_CONTENT_REQUEST_TYPES,
  outputClasses: AI_PREMIUM_CONTENT_OUTPUT_CLASSES,
  statuses: AI_PREMIUM_CONTENT_REQUEST_STATUSES,
  moderationStatuses: AI_PREMIUM_CONTENT_MODERATION_STATUSES,
  requestTypePolicy: AI_PREMIUM_CONTENT_REQUEST_TYPE_POLICY,
  statusCopy: {
    locale: 'ko-KR',
    fallbackMap: AI_PREMIUM_CONTENT_STATUS_COPY_KO,
    rawEnumAsCopy: false,
    rawProviderStatusAsCopy: false,
    neutralFallbackCopy: '상태를 확인 중이에요',
  },
  apiContracts: {
    myRequestList: {
      method: 'GET',
      path: '/api/v1/me/ai-premium-content/requests',
      enabled: false,
      authRequired: true,
      ownerOnly: true,
      query: {
        artistId: 'optional artist uuid',
        status: AI_PREMIUM_CONTENT_REQUEST_STATUSES,
        requestType: AI_PREMIUM_CONTENT_REQUEST_TYPES,
        outputClass: AI_PREMIUM_CONTENT_OUTPUT_CLASSES,
        take: { default: 30, max: 100 },
        cursor: 'opaque request cursor',
      },
      mutation: false,
    },
    myRequestDetail: {
      method: 'GET',
      path: '/api/v1/ai-premium-content/requests/:requestId',
      enabled: false,
      authRequired: true,
      ownerOrArtistOperatorOnly: true,
      mutation: false,
    },
    adminRequestList: {
      method: 'GET',
      path: '/admin/api/v1/ai-premium-content/requests',
      enabled: false,
      adminRequired: true,
      requiredPermission: 'assets:read',
      query: {
        status: AI_PREMIUM_CONTENT_REQUEST_STATUSES,
        moderationStatus: AI_PREMIUM_CONTENT_MODERATION_STATUSES,
        requestType: AI_PREMIUM_CONTENT_REQUEST_TYPES,
        outputClass: AI_PREMIUM_CONTENT_OUTPUT_CLASSES,
        take: { default: 50, max: 100 },
        cursor: 'opaque request cursor',
      },
      mutation: false,
    },
    adminRequestDetail: {
      method: 'GET',
      path: '/admin/api/v1/ai-premium-content/requests/:requestId',
      enabled: false,
      adminRequired: true,
      requiredPermission: 'assets:read',
      mutation: false,
    },
    createRequest: {
      method: 'POST',
      path: '/api/v1/ai-premium-content/requests',
      enabled: false,
      submitEnabled: false,
      idempotencyRequired: true,
      mutation: false,
    },
    regenerateRequest: {
      method: 'POST',
      path: '/api/v1/ai-premium-content/requests/:requestId/regenerations',
      enabled: false,
      submitEnabled: false,
      idempotencyRequired: true,
      mutation: false,
    },
    adminUpdateRequest: {
      method: 'PATCH',
      path: '/admin/api/v1/ai-premium-content/requests/:requestId',
      enabled: false,
      mutation: false,
      idempotencyRequiredForReviewDecisions: true,
    },
  },
  projection: {
    requestItem: {
      id: '<request uuid>',
      requestType: '<image_single|image_variation|image_reference|video_clip|video_loop|premium_pack>',
      outputClass: '<image|video|mixed>',
      sourceSurface: '<creator_studio|backstage|system>',
      artist: {
        id: '<artist uuid>',
        slug: '<artist slug>',
        displayName: '<artist display name>',
      },
      status: {
        key: '<internal status>',
        labelKo: '<localized Korean copy>',
        messageKey: '<stable copy key>',
        rawEnumAsCopy: false,
      },
      moderationStatus: {
        key: '<pending|cleared|blocked|needs_review>',
        labelKo: '<localized Korean copy>',
        rawEnumAsCopy: false,
      },
      resultAvailability: {
        hasResultAssets: '<boolean>',
        resultAssetIds: '<safe asset uuid array>',
        publicOriginalUrlsReturned: false,
        signedUrlsReturned: false,
      },
      retryAvailability: {
        canRegenerate: false,
        disabledReasonKey: 'aiPremiumContent.regeneration.disabled',
      },
      publishAvailability: {
        canPublish: false,
        canEquip: false,
        disabledReasonKey: 'aiPremiumContent.publish.disabled',
      },
      timestamps: {
        createdAt: '<ISO datetime>',
        updatedAt: '<ISO datetime>',
        completedAt: '<ISO datetime or null>',
      },
    },
  },
  validationOrder: [
    'auth_required',
    'request_id_valid',
    'request_exists',
    'owner_or_artist_operator_access',
    'status_filter_valid',
    'safe_projection_only',
  ],
  mutationGates: {
    createRequest: false,
    regenerateRequest: false,
    providerAttempt: false,
    walletDebit: false,
    orderCreate: false,
    settlementAccrual: false,
    payoutAccrual: false,
    paidLike: false,
    publicPublish: false,
    equipToProfileOrFeed: false,
    adminReviewDecision: false,
  },
  serverAuthority: {
    clientSubmittedStatusTrusted: false,
    clientSubmittedModerationStatusTrusted: false,
    clientSubmittedProviderStatusTrusted: false,
    clientSubmittedCostTrusted: false,
    clientSubmittedResultAssetUrlsTrusted: false,
    serverBuildsContextSnapshot: true,
    serverOwnsSafetyGate: true,
  },
  privacy: {
    rawProviderPayloadReturned: false,
    rawPromptReturned: false,
    rawPrivateReferenceMaterialReturned: false,
    signedUrlsReturned: false,
    sensitiveAuthMaterialReturned: false,
    privateConnectionMaterialReturned: false,
    rawEmailReturned: false,
  },
} as const;
