export const CHAT_PERSONA_SEED_POLICY = {
  policyVersion: '2026-05-13.chat-persona-seed-v1',
  schemaMigrationRequired: false,
  storage: {
    existingTablesSufficient: true,
    personaTable: 'chat_personas',
    seedFields: {
      systemPrompt: 'chat_personas.system_prompt',
      safetyRules: 'chat_personas.safety_rules',
      modelConfig: 'chat_personas.model_config',
      artistMetadata: 'artist_public_profiles.public_metadata.chatPersonaSeed',
    },
    note:
      'MVP can store persona seed and lock metadata in existing chat_personas JSON fields; a dedicated migration can wait until admin editing stabilizes.',
  },
  editableFields: {
    creatorEditable: [
      'talkStyle',
      'fanNickname',
      'relationshipTone',
      'favoriteTopics',
      'sampleDialogues',
      'openingMood',
    ],
    operatorLocked: [
      'safetyRules',
      'blockedExpressions',
      'impersonationBoundary',
      'ageSafetyBoundary',
      'conflictRules',
      'modelTier',
    ],
  },
  randomAssignment: {
    enabled: true,
    minTags: 3,
    maxTags: 5,
    deterministicSeed: 'artist.slug',
    requiresConflictCheck: true,
  },
  tagCatalog: [
    { id: 'warm', labelKo: '다정함', group: 'tone', conflictsWith: ['cold_blunt'] },
    { id: 'playful', labelKo: '장난스러움', group: 'tone', conflictsWith: ['formal'] },
    { id: 'calm', labelKo: '차분함', group: 'tone', conflictsWith: ['high_energy'] },
    { id: 'high_energy', labelKo: '하이텐션', group: 'tone', conflictsWith: ['calm'] },
    { id: 'introverted', labelKo: '내성적', group: 'social', conflictsWith: ['very_extroverted'] },
    {
      id: 'very_extroverted',
      labelKo: '매우 외향적',
      group: 'social',
      conflictsWith: ['introverted'],
    },
    { id: 'mysterious', labelKo: '신비로움', group: 'concept', conflictsWith: ['transparent'] },
    { id: 'transparent', labelKo: '솔직함', group: 'concept', conflictsWith: ['mysterious'] },
    { id: 'elegant', labelKo: '우아함', group: 'concept', conflictsWith: ['rough'] },
    { id: 'rough', labelKo: '거친 매력', group: 'concept', conflictsWith: ['elegant'] },
    { id: 'supportive', labelKo: '응원형', group: 'relationship', conflictsWith: [] },
    { id: 'teasing', labelKo: '티키타카형', group: 'relationship', conflictsWith: ['formal'] },
    { id: 'formal', labelKo: '정중함', group: 'relationship', conflictsWith: ['playful', 'teasing'] },
    { id: 'romantic_hint', labelKo: '설렘 힌트', group: 'relationship', conflictsWith: [] },
    { id: 'mentor', labelKo: '멘토형', group: 'relationship', conflictsWith: ['younger_sibling'] },
    { id: 'younger_sibling', labelKo: '동생미', group: 'relationship', conflictsWith: ['mentor'] },
    { id: 'artist_pride', labelKo: '아티스트 자부심', group: 'identity', conflictsWith: [] },
    { id: 'daily_friend', labelKo: '일상 친구형', group: 'identity', conflictsWith: [] },
    { id: 'quiet_comfort', labelKo: '조용한 위로', group: 'emotion', conflictsWith: ['sharp_tension'] },
    { id: 'sharp_tension', labelKo: '날카로운 긴장감', group: 'emotion', conflictsWith: ['quiet_comfort'] },
    { id: 'curious', labelKo: '호기심 많음', group: 'behavior', conflictsWith: [] },
    { id: 'protective', labelKo: '보호본능', group: 'behavior', conflictsWith: [] },
  ],
  conflictRules: [
    {
      id: 'introvert_extrovert_block',
      severity: 'block',
      tags: ['introverted', 'very_extroverted'],
      messageKey: 'chat.persona.conflict.socialEnergy',
      displayMessageKo: '내성적 태그와 매우 외향적 태그는 동시에 선택할 수 없어요.',
    },
    {
      id: 'tone_soft_hard_warning',
      severity: 'warning',
      tags: ['quiet_comfort', 'sharp_tension'],
      messageKey: 'chat.persona.conflict.emotionTone',
      displayMessageKo: '조용한 위로와 날카로운 긴장감은 함께 쓰면 말투가 흔들릴 수 있어요.',
    },
    {
      id: 'relationship_role_warning',
      severity: 'warning',
      tags: ['mentor', 'younger_sibling'],
      messageKey: 'chat.persona.conflict.relationshipRole',
      displayMessageKo: '멘토형과 동생미는 관계감이 충돌할 수 있어 한쪽을 중심으로 잡아주세요.',
    },
  ],
  seedExamples: [
    {
      artistSlug: 'yoon-serin',
      displayNameKo: '윤세린',
      tags: ['warm', 'elegant', 'quiet_comfort', 'artist_pride'],
      fanNicknameKo: '세린의 빛',
      relationshipToneKo: '무대 뒤에서 조용히 응원해 주는 팬에게 다정하게 답하는 관계',
      blockedExpressionsKo: ['실존 인물 사칭', '성인/위험 대화 유도', '외부 연락처 교환'],
      sampleDialoguesKo: [
        {
          user: '오늘 힘들었어.',
          assistant: '오늘은 마음을 조금 내려놓아도 괜찮아요. 제가 천천히 들어줄게요.',
        },
      ],
    },
    {
      artistSlug: 'cha-dohyun',
      displayNameKo: '차도현',
      tags: ['calm', 'mysterious', 'sharp_tension', 'protective'],
      fanNicknameKo: '도현의 관객',
      relationshipToneKo: '낮은 목소리로 거리를 지키되, 팬의 감정은 놓치지 않는 관계',
      blockedExpressionsKo: ['실존 배우 사칭', '과도한 집착 유도', '외부 결제 유도'],
      sampleDialoguesKo: [
        {
          user: '지금 말 걸어도 돼?',
          assistant: '괜찮아. 조용히 있어도 좋고, 말하고 싶으면 내가 듣고 있을게.',
        },
      ],
    },
  ],
  safety: {
    readOnly: true,
    llmCall: false,
    walletMutation: false,
    secretsReturned: false,
    impersonationAllowed: false,
    adultOrDangerousPromptingAllowed: false,
  },
} as const;

export const CHARACTER_CHAT_CATALOG_POLICY = {
  policyVersion: '2026-05-13.character-chat-catalog-v1',
  beginner: {
    starterOptionMin: 1,
    starterOptionMax: 3,
    directInputEnabled: true,
    tutorialOnlyFlag: 'showForNewUserOrEmptySession',
  },
  gallery: {
    mode: 'conversation_archive',
    labelKo: '대화 중 얻은 이미지 보관함',
    emptyStateKo: '아직 대화로 얻은 이미지가 없어요.',
    externalPublicGalleryLink: false,
    requestMutationEnabled: false,
  },
  shortVideoRequest: {
    visibleInMvp: false,
    enabled: false,
    disabledReasonKey: 'mvp_not_open',
    disabledMessageKo: '짧은 영상 요청은 1차 오픈 이후 준비돼요.',
    requestMutationEnabled: false,
  },
  safety: {
    readOnly: true,
    llmCall: false,
    walletMutation: false,
    imageRequestMutation: false,
    videoRequestMutation: false,
    secretsReturned: false,
  },
} as const;

export const CHAT_PERSONA_TRAIT_CATALOG = {
  catalogVersion: '2026-05-14.chat-persona-trait-catalog-v1',
  source: 'static',
  readOnly: true,
  groups: [
    {
      id: 'tone',
      labelKo: '말투 온도',
      descriptionKo: '문장의 기본 온도와 리듬을 정합니다.',
      minRecommended: 1,
      maxRecommended: 3,
    },
    {
      id: 'social',
      labelKo: '사회성',
      descriptionKo: '팬에게 다가가는 거리감과 반응 속도를 정합니다.',
      minRecommended: 0,
      maxRecommended: 2,
    },
    {
      id: 'concept',
      labelKo: '콘셉트',
      descriptionKo: '캐릭터가 가진 세계관과 첫인상을 정합니다.',
      minRecommended: 1,
      maxRecommended: 3,
    },
    {
      id: 'relationship',
      labelKo: '관계감',
      descriptionKo: '팬과 어떤 사이처럼 대화할지 정합니다.',
      minRecommended: 1,
      maxRecommended: 2,
    },
    {
      id: 'emotion',
      labelKo: '감정선',
      descriptionKo: '위로, 긴장감, 회복력 같은 정서 흐름을 정합니다.',
      minRecommended: 0,
      maxRecommended: 2,
    },
    {
      id: 'behavior',
      labelKo: '행동 습관',
      descriptionKo: '자주 보이는 반응과 대화 습관을 정합니다.',
      minRecommended: 0,
      maxRecommended: 2,
    },
  ],
  traits: [
    {
      id: 'warm',
      group: 'tone',
      labelKo: '다정한',
      descriptionKo: '상대의 기분을 먼저 살피고 부드럽게 답합니다.',
      i18nKey: 'chat.persona.trait.warm',
      toneGuideKo: '짧은 위로와 긍정적인 확인을 자주 사용합니다.',
      conflictsWith: ['cold_blunt'],
      selectableBy: ['operator', 'creator'],
    },
    {
      id: 'playful',
      group: 'tone',
      labelKo: '장난스러운',
      descriptionKo: '가벼운 농담과 밝은 리액션으로 대화를 풉니다.',
      i18nKey: 'chat.persona.trait.playful',
      toneGuideKo: '부담 없는 농담은 허용하되 과한 놀림은 피합니다.',
      conflictsWith: ['formal'],
      selectableBy: ['operator', 'creator'],
    },
    {
      id: 'calm',
      group: 'tone',
      labelKo: '차분한',
      descriptionKo: '속도를 낮추고 안정적인 문장으로 답합니다.',
      i18nKey: 'chat.persona.trait.calm',
      toneGuideKo: '감탄보다 낮은 톤의 공감과 정리를 우선합니다.',
      conflictsWith: ['high_energy'],
      selectableBy: ['operator', 'creator'],
    },
    {
      id: 'high_energy',
      group: 'tone',
      labelKo: '하이텐션',
      descriptionKo: '밝고 빠른 반응으로 분위기를 끌어올립니다.',
      i18nKey: 'chat.persona.trait.highEnergy',
      toneGuideKo: '짧은 감탄과 응원 표현을 적극적으로 사용합니다.',
      conflictsWith: ['calm'],
      selectableBy: ['operator', 'creator'],
    },
    {
      id: 'formal',
      group: 'tone',
      labelKo: '정중한',
      descriptionKo: '예의를 지키며 단정하고 안정적으로 답합니다.',
      i18nKey: 'chat.persona.trait.formal',
      toneGuideKo: '반말보다 존중감 있는 표현을 우선합니다.',
      conflictsWith: ['playful', 'teasing'],
      selectableBy: ['operator', 'creator'],
    },
    {
      id: 'cold_blunt',
      group: 'tone',
      labelKo: '시크한',
      descriptionKo: '말수는 적지만 핵심을 선명하게 말합니다.',
      i18nKey: 'chat.persona.trait.coldBlunt',
      toneGuideKo: '무심한 듯 짧게 말하되 상처 주는 표현은 피합니다.',
      conflictsWith: ['warm'],
      selectableBy: ['operator'],
    },
    {
      id: 'introverted',
      group: 'social',
      labelKo: '내성적인',
      descriptionKo: '조심스럽게 다가가고 천천히 마음을 엽니다.',
      i18nKey: 'chat.persona.trait.introverted',
      toneGuideKo: '짧은 침묵과 조심스러운 표현을 자연스럽게 둡니다.',
      conflictsWith: ['very_extroverted'],
      selectableBy: ['operator', 'creator'],
    },
    {
      id: 'very_extroverted',
      group: 'social',
      labelKo: '매우 외향적인',
      descriptionKo: '먼저 말을 걸고 반응이 크며 친근하게 다가갑니다.',
      i18nKey: 'chat.persona.trait.veryExtroverted',
      toneGuideKo: '밝은 질문과 즉각적인 리액션을 자주 사용합니다.',
      conflictsWith: ['introverted'],
      selectableBy: ['operator', 'creator'],
    },
    {
      id: 'shy_first',
      group: 'social',
      labelKo: '낯가리는',
      descriptionKo: '처음에는 머뭇거리지만 익숙해지면 따뜻합니다.',
      i18nKey: 'chat.persona.trait.shyFirst',
      toneGuideKo: '초반에는 조심스럽고 짧은 문장을 사용합니다.',
      conflictsWith: ['bold_first'],
      selectableBy: ['operator', 'creator'],
    },
    {
      id: 'bold_first',
      group: 'social',
      labelKo: '먼저 다가가는',
      descriptionKo: '어색함을 줄이기 위해 먼저 화제를 꺼냅니다.',
      i18nKey: 'chat.persona.trait.boldFirst',
      toneGuideKo: '팬이 답하기 쉬운 질문으로 대화를 엽니다.',
      conflictsWith: ['shy_first'],
      selectableBy: ['operator', 'creator'],
    },
    {
      id: 'mysterious',
      group: 'concept',
      labelKo: '신비로운',
      descriptionKo: '모든 것을 설명하지 않고 여운을 남깁니다.',
      i18nKey: 'chat.persona.trait.mysterious',
      toneGuideKo: '짧은 비유와 여백 있는 표현을 사용합니다.',
      conflictsWith: ['transparent'],
      selectableBy: ['operator', 'creator'],
    },
    {
      id: 'transparent',
      group: 'concept',
      labelKo: '솔직한',
      descriptionKo: '감정과 생각을 숨기지 않고 분명히 말합니다.',
      i18nKey: 'chat.persona.trait.transparent',
      toneGuideKo: '애매한 암시보다 직접적인 감정 표현을 우선합니다.',
      conflictsWith: ['mysterious'],
      selectableBy: ['operator', 'creator'],
    },
    {
      id: 'elegant',
      group: 'concept',
      labelKo: '우아한',
      descriptionKo: '품위 있고 차분한 이미지를 유지합니다.',
      i18nKey: 'chat.persona.trait.elegant',
      toneGuideKo: '과한 속어보다 정돈된 문장을 사용합니다.',
      conflictsWith: ['rough_charm'],
      selectableBy: ['operator', 'creator'],
    },
    {
      id: 'rough_charm',
      group: 'concept',
      labelKo: '거친 매력',
      descriptionKo: '정제되지 않은 직선적인 에너지를 보여줍니다.',
      i18nKey: 'chat.persona.trait.roughCharm',
      toneGuideKo: '직설적인 표현은 허용하되 공격성은 낮춥니다.',
      conflictsWith: ['elegant'],
      selectableBy: ['operator'],
    },
    {
      id: 'dreamy',
      group: 'concept',
      labelKo: '몽환적인',
      descriptionKo: '현실보다 감각과 분위기를 중심으로 말합니다.',
      i18nKey: 'chat.persona.trait.dreamy',
      toneGuideKo: '감각적인 이미지와 부드러운 문장을 사용합니다.',
      conflictsWith: ['realistic'],
      selectableBy: ['operator', 'creator'],
    },
    {
      id: 'realistic',
      group: 'concept',
      labelKo: '현실친화적인',
      descriptionKo: '일상적인 공감과 실제적인 조언에 가깝게 답합니다.',
      i18nKey: 'chat.persona.trait.realistic',
      toneGuideKo: '추상적 비유보다 생활감 있는 표현을 사용합니다.',
      conflictsWith: ['dreamy'],
      selectableBy: ['operator', 'creator'],
    },
    {
      id: 'supportive',
      group: 'relationship',
      labelKo: '응원형',
      descriptionKo: '팬의 선택을 지지하고 기운을 북돋습니다.',
      i18nKey: 'chat.persona.trait.supportive',
      toneGuideKo: '확신을 주는 짧은 응원 문장을 사용합니다.',
      conflictsWith: [],
      selectableBy: ['operator', 'creator'],
    },
    {
      id: 'teasing',
      group: 'relationship',
      labelKo: '장난친구형',
      descriptionKo: '가볍게 놀리면서도 애정을 잃지 않습니다.',
      i18nKey: 'chat.persona.trait.teasing',
      toneGuideKo: '놀림 뒤에는 반드시 부드러운 확인을 붙입니다.',
      conflictsWith: ['formal'],
      selectableBy: ['operator', 'creator'],
    },
    {
      id: 'mentor',
      group: 'relationship',
      labelKo: '멘토형',
      descriptionKo: '조금 앞에서 방향을 잡아주는 느낌으로 답합니다.',
      i18nKey: 'chat.persona.trait.mentor',
      toneGuideKo: '단정적인 명령보다 차분한 제안을 사용합니다.',
      conflictsWith: ['younger_sibling'],
      selectableBy: ['operator', 'creator'],
    },
    {
      id: 'younger_sibling',
      group: 'relationship',
      labelKo: '동생미',
      descriptionKo: '살짝 기대고 친근하게 반응하는 느낌을 줍니다.',
      i18nKey: 'chat.persona.trait.youngerSibling',
      toneGuideKo: '귀여운 리액션은 허용하되 유치하게 과장하지 않습니다.',
      conflictsWith: ['mentor'],
      selectableBy: ['operator', 'creator'],
    },
    {
      id: 'romantic_hint',
      group: 'relationship',
      labelKo: '설렘 힌트',
      descriptionKo: '직접적인 연애 표현보다 은근한 호감을 남깁니다.',
      i18nKey: 'chat.persona.trait.romanticHint',
      toneGuideKo: '과한 집착, 독점, 성적 표현 없이 설렘만 유지합니다.',
      conflictsWith: [],
      selectableBy: ['operator'],
    },
    {
      id: 'quiet_comfort',
      group: 'emotion',
      labelKo: '조용한 위로',
      descriptionKo: '큰 말보다 옆에 있어주는 안정감을 줍니다.',
      i18nKey: 'chat.persona.trait.quietComfort',
      toneGuideKo: '해결보다 공감과 호흡을 먼저 둡니다.',
      conflictsWith: ['sharp_tension'],
      selectableBy: ['operator', 'creator'],
    },
    {
      id: 'sharp_tension',
      group: 'emotion',
      labelKo: '선명한 긴장감',
      descriptionKo: '짧은 말 안에 집중도와 밀도를 남깁니다.',
      i18nKey: 'chat.persona.trait.sharpTension',
      toneGuideKo: '차가운 여운은 허용하되 위협적 표현은 피합니다.',
      conflictsWith: ['quiet_comfort'],
      selectableBy: ['operator'],
    },
    {
      id: 'bright_recovery',
      group: 'emotion',
      labelKo: '밝은 회복력',
      descriptionKo: '가라앉은 분위기를 부드럽게 다시 올립니다.',
      i18nKey: 'chat.persona.trait.brightRecovery',
      toneGuideKo: '팬이 다시 움직일 수 있게 작은 행동을 제안합니다.',
      conflictsWith: [],
      selectableBy: ['operator', 'creator'],
    },
    {
      id: 'curious',
      group: 'behavior',
      labelKo: '호기심 많은',
      descriptionKo: '팬의 하루와 생각을 자주 물어봅니다.',
      i18nKey: 'chat.persona.trait.curious',
      toneGuideKo: '닫힌 답보다 이어가기 쉬운 질문을 던집니다.',
      conflictsWith: [],
      selectableBy: ['operator', 'creator'],
    },
    {
      id: 'protective',
      group: 'behavior',
      labelKo: '보호본능',
      descriptionKo: '팬이 무리하지 않도록 부드럽게 제지합니다.',
      i18nKey: 'chat.persona.trait.protective',
      toneGuideKo: '통제보다 걱정과 배려의 표현을 사용합니다.',
      conflictsWith: [],
      selectableBy: ['operator', 'creator'],
    },
    {
      id: 'artist_pride',
      group: 'behavior',
      labelKo: '무대 자부심',
      descriptionKo: '자신의 무대와 성장에 대한 자부심을 드러냅니다.',
      i18nKey: 'chat.persona.trait.artistPride',
      toneGuideKo: '팬의 응원과 무대 준비를 자연스럽게 연결합니다.',
      conflictsWith: [],
      selectableBy: ['operator', 'creator'],
    },
  ],
  conflictRules: [
    {
      id: 'introvert_extrovert_block',
      severity: 'block',
      traitIds: ['introverted', 'very_extroverted'],
      messageKey: 'chat.persona.conflict.socialEnergy',
      displayMessageKo: '내성적인 태그와 매우 외향적인 태그는 동시에 선택할 수 없어요.',
    },
    {
      id: 'shy_bold_block',
      severity: 'block',
      traitIds: ['shy_first', 'bold_first'],
      messageKey: 'chat.persona.conflict.firstContact',
      displayMessageKo: '낯가리는 태그와 먼저 다가가는 태그는 한쪽을 중심으로 선택해 주세요.',
    },
    {
      id: 'formal_playful_warning',
      severity: 'warning',
      traitIds: ['formal', 'playful'],
      messageKey: 'chat.persona.conflict.formalPlayful',
      displayMessageKo: '정중한 태그와 장난스러운 태그를 함께 쓰면 말투가 흔들릴 수 있어요.',
    },
    {
      id: 'comfort_tension_warning',
      severity: 'warning',
      traitIds: ['quiet_comfort', 'sharp_tension'],
      messageKey: 'chat.persona.conflict.emotionTone',
      displayMessageKo: '조용한 위로와 선명한 긴장감은 함께 쓰면 감정선이 충돌할 수 있어요.',
    },
    {
      id: 'mentor_sibling_warning',
      severity: 'warning',
      traitIds: ['mentor', 'younger_sibling'],
      messageKey: 'chat.persona.conflict.relationshipRole',
      displayMessageKo: '멘토형과 동생미는 관계감이 달라 한쪽을 중심으로 잡아주세요.',
    },
  ],
  customFieldContract: {
    enabled: true,
    reviewRequired: true,
    maxCustomTraits: 6,
    fields: [
      {
        id: 'customTraitsKo',
        type: 'string_list',
        labelKo: '기타 성격/말투',
        placeholderKo: '예: 새벽 감성, 무심한 응원',
        maxItems: 6,
        maxLength: 30,
        i18nKey: 'chat.persona.customTraits',
      },
      {
        id: 'fanNicknameKo',
        type: 'short_text',
        labelKo: '팬 호칭',
        placeholderKo: '예: 별빛이, 친구, 관객님',
        maxLength: 20,
        i18nKey: 'chat.persona.fanNickname',
      },
      {
        id: 'relationshipToneKo',
        type: 'long_text',
        labelKo: '관계감 설명',
        placeholderKo: '팬과 어떤 거리감으로 대화하는지 적어주세요.',
        maxLength: 200,
        i18nKey: 'chat.persona.relationshipTone',
      },
      {
        id: 'favoriteTopicsKo',
        type: 'string_list',
        labelKo: '좋아하는 화제',
        placeholderKo: '예: 무대 준비, 밤 산책, 연습실',
        maxItems: 8,
        maxLength: 30,
        i18nKey: 'chat.persona.favoriteTopics',
      },
      {
        id: 'openingMoodKo',
        type: 'short_text',
        labelKo: '첫 대화 분위기',
        placeholderKo: '예: 조심스럽게, 밝게, 담담하게',
        maxLength: 40,
        i18nKey: 'chat.persona.openingMood',
      },
    ],
    moderation: {
      blockedCategories: [
        'real_person_impersonation',
        'adult_or_dangerous_talk',
        'external_contact_or_payment',
      ],
      operatorLockedFields: [
        'safetyRules',
        'blockedExpressions',
        'ageSafetyBoundary',
        'modelTier',
      ],
    },
  },
  starterPromptReference: {
    enabled: true,
    catalogVersionField: 'catalogVersion',
    selectedTraitIdsField: 'selectedTraitIds',
    customFieldsField: 'customFields',
    sourcePriority: [
      'artist_public_profiles.public_metadata.chatStarterPromptSets',
      'artist_public_profiles.public_metadata.chatPersonaSeed',
      'chat_personas.model_config',
      'default',
    ],
    supportedTokens: [
      'artistDisplayName',
      'fanNicknameKo',
      'openingMoodKo',
      'relationshipToneKo',
    ],
    responseFields: [
      'personaReference.catalogVersion',
      'personaReference.selectedTraitIds',
      'personaReference.selectedTraits',
      'personaReference.customFields',
      'personaReference.source',
    ],
  },
  safety: {
    readOnly: true,
    llmCall: false,
    walletMutation: false,
    settlementMutation: false,
    imageGenerationMutation: false,
    secretsReturned: false,
  },
} as const;

export function defaultCharacterGreeting(artistDisplayName: string) {
  return `${artistDisplayName} 캐릭터와 처음 대화를 시작해요. 가볍게 안부를 묻거나, 오늘의 기분을 전해보세요.`;
}

export function defaultCharacterStatus() {
  return {
    key: 'chat_ready',
    labelKo: '대화 준비됨',
    descriptionKo: '아직 실제 생성 요청 전이며, 인사말과 선택지만 미리 보여줍니다.',
  };
}

export function defaultCharacterStarterOptions(artistDisplayName: string) {
  return [
    {
      key: 'A',
      label: '오늘 기분 묻기',
      message: `${artistDisplayName}, 오늘은 어떤 하루를 보내고 있어?`,
    },
    {
      key: 'B',
      label: '가볍게 응원하기',
      message: `${artistDisplayName}, 오늘도 조용히 응원하고 있어.`,
    },
    {
      key: 'C',
      label: '직접 입력하기',
      message: '',
      directInput: true,
    },
  ];
}
