export const ACCOUNT_PAID_FEATURE_ACCESS_GUARD_CONTRACT = {
  version: '2026-06-28.account-paid-feature-access-guard.v1',
  guardedSurfaces: [
    'premium_chat_room_open',
    'premium_chat_donation',
    'premium_chat_message_send',
    'premium_video_unlock',
    'story_chapter_purchase',
    'story_comment_or_rating',
    'creator_image_or_video_request',
  ],
  authority: {
    accountStatusSource: 'users.status',
    deletedSource: 'users.deletedAt',
    emailVerificationSource: 'users.emailVerifiedAt',
    authAccountSource: 'user_auth_accounts',
    paidFeatureLedgerSource: 'wallet_accounts_and_domain_specific_server_policy',
  },
  allowedAccountState: {
    userStatus: 'active',
    deletedAt: null,
    authAccountRequired: true,
    emailVerifiedWhenRequired: true,
  },
  blockedStates: {
    deleted: {
      status: 403,
      code: 'ACCOUNT_DELETED',
      messageKey: 'auth.account.deleted',
      walletMutation: false,
    },
    suspended: {
      status: 403,
      code: 'ACCOUNT_SUSPENDED',
      messageKey: 'auth.account.suspended',
      walletMutation: false,
    },
    inactive: {
      status: 403,
      code: 'ACCOUNT_INACTIVE',
      messageKey: 'auth.account.inactive',
      walletMutation: false,
    },
    emailUnverified: {
      status: 403,
      code: 'EMAIL_VERIFICATION_REQUIRED',
      messageKey: 'auth.emailVerification.required',
      walletMutation: false,
    },
    missingAuthAccount: {
      status: 403,
      code: 'AUTH_ACCOUNT_REQUIRED',
      messageKey: 'auth.account.authAccountRequired',
      walletMutation: false,
    },
  },
  validationOrder: [
    'authenticate_session',
    'load_user_by_session_subject',
    'reject_deleted_or_missing_user',
    'reject_suspended_or_inactive_user',
    'require_auth_account',
    'require_email_verification_when_surface_requires_it',
    'apply_surface_specific_server_policy',
    'only_then_evaluate_wallet_or_ledger_mutation',
  ],
  noClientAuthority: {
    clientSubmittedUserStatusTrusted: false,
    clientSubmittedEmailVerifiedTrusted: false,
    clientSubmittedWalletBalanceTrusted: false,
    clientSubmittedEntitlementTrusted: false,
  },
  privacy: {
    rawEmailReturned: false,
    passwordHashReturned: false,
    providerCredentialReturned: false,
    tokenReturned: false,
    cookieReturned: false,
    apiKeyReturned: false,
    databaseUrlReturned: false,
  },
} as const;
