const AUTH_SAFE_COPY_LOCALES = ['ko', 'en', 'ja', 'zh-Hans', 'zh-Hant'] as const;

export const AUTH_PROTECTED_ENTRY_BRIDGE_CONTRACT = {
  version: '2026-07-08.auth-protected-entry-bridge.v1',
  readModel: 'public_auth_entry_gate_projection',
  entryFields: [
    'surface',
    'requiredAccountState',
    'allowedPreview',
    'afterLoginAction',
    'mutationBlocked',
  ],
  surfaces: [
    {
      surface: 'story_preview',
      requiredAccountState: 'anonymous_or_active',
      allowedPreview: true,
      afterLoginAction: 'continue_story_preview',
      mutationBlocked: false,
    },
    {
      surface: 'story_write_or_progress',
      requiredAccountState: 'active_session',
      allowedPreview: false,
      afterLoginAction: 'resume_story_action',
      mutationBlocked: true,
    },
    {
      surface: 'creator_studio',
      requiredAccountState: 'active_verified_creator',
      allowedPreview: false,
      afterLoginAction: 'return_to_creator_entry',
      mutationBlocked: true,
    },
    {
      surface: 'premium_chat_or_unlock',
      requiredAccountState: 'active_verified_paid_feature_user',
      allowedPreview: true,
      afterLoginAction: 'return_to_premium_entry',
      mutationBlocked: true,
    },
    {
      surface: 'debut_application',
      requiredAccountState: 'active_verified_identity_ready_user',
      allowedPreview: true,
      afterLoginAction: 'return_to_debut_entry',
      mutationBlocked: true,
    },
    {
      surface: 'mypage_account',
      requiredAccountState: 'active_session',
      allowedPreview: false,
      afterLoginAction: 'return_to_mypage',
      mutationBlocked: false,
    },
  ],
  previewPolicy: {
    publicReadOnlyPreviewAllowed: true,
    paidPreviewAllowedWithoutWalletMutation: true,
    uploadImportPublishMutationAllowedWithoutLogin: false,
    creatorMutationAllowedWithoutCreatorState: false,
    paymentWalletSettlementMutationAllowedFromBridge: false,
  },
  fixture: {
    fixtureKey: 'auth_entry_gate_preview',
    accounts: ['anonymous_preview', 'active_unverified', 'active_social_only', 'active_verified_creator'],
    responseContainsOnlyPublicState: true,
  },
  privacy: {
    rawEmailReturned: false,
    providerPayloadReturned: false,
    sessionTokenReturned: false,
    cookieReturned: false,
    passwordReturned: false,
    internalAccountIdReturned: false,
  },
} as const;

export const AUTH_ACCOUNT_STATE_PROJECTION_BRIDGE = {
  version: '2026-07-08.auth-account-state-projection-bridge.v1',
  readModel: 'public_account_state_projection',
  sourceOfTruth: {
    emailVerified: 'server_resolved_account_state',
    hasPassword: 'server_resolved_credential_state',
    isSocialOnly: 'server_resolved_provider_state',
    identityVerification: 'server_resolved_identity_state',
    settlementProfile: 'server_resolved_settlement_state',
  },
  projectionFields: [
    'emailVerified',
    'hasPassword',
    'isSocialOnly',
    'identityVerification',
    'settlementProfile',
    'recommendedAction',
  ],
  states: [
    {
      fixtureState: 'verified_password_user',
      emailVerified: true,
      hasPassword: true,
      isSocialOnly: false,
      identityVerification: 'not_required',
      settlementProfile: 'not_required',
      recommendedAction: 'continue',
    },
    {
      fixtureState: 'unverified_email_user',
      emailVerified: false,
      hasPassword: true,
      isSocialOnly: false,
      identityVerification: 'not_required',
      settlementProfile: 'not_required',
      recommendedAction: 'verify_email',
    },
    {
      fixtureState: 'social_only_user',
      emailVerified: true,
      hasPassword: false,
      isSocialOnly: true,
      identityVerification: 'not_required',
      settlementProfile: 'not_required',
      recommendedAction: 'set_password',
    },
    {
      fixtureState: 'creator_settlement_missing',
      emailVerified: true,
      hasPassword: true,
      isSocialOnly: false,
      identityVerification: 'approved',
      settlementProfile: 'missing',
      recommendedAction: 'complete_settlement_profile',
    },
  ],
  socialOnlyPolicy: {
    passwordResetCtaAllowed: false,
    passwordSetupCtaRequired: true,
  },
  reuseTargets: ['mypage', 'creator_studio', 'debut_application', 'premium_entry'],
  privacy: {
    rawEmailReturned: false,
    providerIdReturned: false,
    providerPayloadReturned: false,
    sessionTokenReturned: false,
    cookieReturned: false,
    internalAccountIdReturned: false,
  },
} as const;

export const AUTH_SAFE_VISUAL_FIXTURE_CONTRACT = {
  version: '2026-07-09.auth-safe-visual-fixture.v1',
  actionTokenLanding: {
    tokenRequiredForFixture: false,
    publicPaths: [
      '/verify-email?fixture=success',
      '/verify-email?fixture=expired',
      '/verify-email?fixture=request-again',
      '/reset-password?fixture=save-password',
      '/reset-password?fixture=success',
      '/reset-password?fixture=expired',
      '/reset-password?fixture=request-again',
    ],
    states: ['success', 'expired', 'request-again', 'save-password'],
    mutationAllowed: false,
    forbiddenQueryKeys: ['token', 'email', 'password', 'providerId', 'userId'],
  },
  accountStateVisual: {
    tokenRequiredForFixture: false,
    publicPaths: [
      '/mypage?accountfixture=verified',
      '/mypage?accountfixture=unverified',
      '/mypage?accountfixture=social-only',
      '/mypage?accountfixture=no-password',
      '/mypage?accountfixture=identity-pending',
    ],
    states: ['verified', 'unverified', 'social-only', 'no-password', 'identity-pending'],
    socialOnlyPasswordResetVisible: false,
    passwordSetupGuidanceRequiredForSocialOnly: true,
    mutationAllowed: false,
  },
  privacy: {
    rawEmailReturned: false,
    providerIdReturned: false,
    internalUserIdReturned: false,
    sessionTokenReturned: false,
    resetTokenReturned: false,
    cookieReturned: false,
    databaseUrlReturned: false,
    apiKeyReturned: false,
  },
} as const;

export const AUTH_SOCIAL_PROVIDER_FALLBACK_BRIDGE = {
  version: '2026-07-08.auth-social-provider-fallback-bridge.v1',
  readModel: 'public_social_provider_fallback_projection',
  providerStates: [
    {
      state: 'provider_disabled',
      providerAttemptAllowed: false,
      emailLoginFallbackVisible: true,
      accountLinkingNoticeVisible: false,
      mutationAllowed: false,
    },
    {
      state: 'sdk_load_failed',
      providerAttemptAllowed: false,
      emailLoginFallbackVisible: true,
      accountLinkingNoticeVisible: false,
      mutationAllowed: false,
    },
    {
      state: 'social_collision',
      providerAttemptAllowed: false,
      emailLoginFallbackVisible: true,
      accountLinkingNoticeVisible: true,
      mutationAllowed: false,
    },
    {
      state: 'unlink_unsafe',
      providerAttemptAllowed: false,
      emailLoginFallbackVisible: true,
      accountLinkingNoticeVisible: true,
      mutationAllowed: false,
    },
  ],
  userFacingCopy: {
    ko: '이메일 로그인으로 계속 진행해 주세요.',
    en: 'Continue with email login.',
    ja: 'メールログインで続行してください。',
    'zh-Hans': '请使用邮箱登录继续。',
    'zh-Hant': '請使用電子郵件登入後繼續。',
  },
  privacy: {
    rawProviderErrorReturned: false,
    rawEmailReturned: false,
    providerPayloadReturned: false,
    sessionTokenReturned: false,
    cookieReturned: false,
    internalAccountIdReturned: false,
  },
} as const;

export const AUTH_LIVE_QA_HANDOFF_SCHEMA = {
  version: '2026-07-08.auth-live-qa-handoff-schema.v1',
  allowedFields: [
    'runId',
    'accountType',
    'verifiedEmailState',
    'socialOnlyState',
    'environment',
    'readOnlyEndpoints',
    'blocked_by',
  ],
  requiredWhenSafeAccountMissing: {
    blocked_by: 'safe QA account needed',
    mutationAllowed: false,
    liveLoginAttemptAllowed: false,
  },
  readOnlyEndpoints: [
    'GET /api/v1/me',
    'GET /api/v1/ai-premium-content/status-preview-fixture',
    'GET /api/v1/chat/premium-rooms/refund-status-preview-fixture',
  ],
  forbiddenFields: [
    'rawEmail',
    'password',
    'sessionToken',
    'cookie',
    'resetLink',
    'databaseUrl',
    'apiKey',
  ],
} as const;

export const AUTH_ENTRY_STATUS_DASHBOARD_BRIDGE = {
  version: '2026-07-08.auth-entry-status-dashboard-bridge.v1',
  readModel: 'auth_entry_status_dashboard',
  columns: [
    'surface',
    'publicPreview',
    'loginRequired',
    'emailVerificationNotice',
    'socialOnlyNotice',
    'identityNotice',
    'mutationBlocked',
  ],
  rows: [
    {
      surface: 'story',
      publicPreview: true,
      loginRequired: 'write_or_progress_only',
      emailVerificationNotice: false,
      socialOnlyNotice: false,
      identityNotice: false,
      mutationBlocked: true,
    },
    {
      surface: 'creator',
      publicPreview: false,
      loginRequired: 'entry_required',
      emailVerificationNotice: true,
      socialOnlyNotice: true,
      identityNotice: false,
      mutationBlocked: true,
    },
    {
      surface: 'premium',
      publicPreview: true,
      loginRequired: 'unlock_or_support_required',
      emailVerificationNotice: true,
      socialOnlyNotice: true,
      identityNotice: false,
      mutationBlocked: true,
    },
    {
      surface: 'debut',
      publicPreview: true,
      loginRequired: 'submit_required',
      emailVerificationNotice: true,
      socialOnlyNotice: true,
      identityNotice: true,
      mutationBlocked: true,
    },
    {
      surface: 'mypage',
      publicPreview: false,
      loginRequired: 'entry_required',
      emailVerificationNotice: true,
      socialOnlyNotice: true,
      identityNotice: false,
      mutationBlocked: false,
    },
  ],
  localeCopyLocales: AUTH_SAFE_COPY_LOCALES,
  fixturePolicy: {
    stableFixtureNames: true,
    rawBackendEnumAsVisibleCopy: false,
    providerErrorAsVisibleCopy: false,
  },
  privacy: {
    rawEmailReturned: false,
    providerPayloadReturned: false,
    sessionTokenReturned: false,
    cookieReturned: false,
    databaseUrlReturned: false,
    internalAccountIdReturned: false,
  },
} as const;
