export const AUTH_PASSWORD_RESET_TOKEN_AUDIT_CONTRACT = {
  version: '2026-06-26.password-reset-token-audit.v1',
  inspectEndpoint: 'POST /api/v1/auth/password-resets/inspect',
  confirmEndpoint: 'POST /api/v1/auth/password-resets/confirm',
  purpose: 'password_reset',
  invalidStates: ['invalid', 'expired', 'already_used'] as const,
  responsePolicy: {
    code: 'AUTH_PASSWORD_RESET_TOKEN_INVALID_OR_EXPIRED',
    messageKey: 'auth.passwordReset.tokenInvalidOrExpired',
    statusKeyPrefix: 'auth.passwordReset.',
    rawTokenReturned: false,
    tokenHashReturned: false,
    rawEmailReturned: false,
    passwordReturned: false,
    cookieReturned: false,
    apiKeyReturned: false,
    databaseUrlReturned: false,
  },
  inspectPolicy: {
    readOnly: true,
    consumesToken: false,
    invalidOrExpiredTokenEmailReturned: false,
    fullEmailReturned: false,
    maskedEmailOnlyWhenValid: true,
    tokenOrCookieUsedAsPrefillValue: false,
  },
  confirmFailurePolicy: {
    validatesTokenBeforePasswordMutation: true,
    invalidExpiredOrUsedMutatesToken: false,
    invalidExpiredOrUsedUpdatesPassword: false,
    invalidExpiredOrUsedRevokesSessions: false,
    invalidExpiredOrUsedSendsEmail: false,
  },
  auditSafety: {
    stableStateAllowed: true,
    requestIdAllowed: true,
    rawTokenLogAllowed: false,
    tokenHashLogAllowed: false,
    rawPasswordLogAllowed: false,
    rawEmailLogAllowed: false,
  },
} as const;
