export const AUTH_SAFE_QA_FIXTURE_CONTRACT_PACK = {
  version: '2026-07-10.auth-safe-qa-fixture-pack.v1',
  endpoint: 'GET /api/v1/qa-fixtures/auth/session-states',
  status: 'contract_only_read_only',
  purpose:
    'Let QA reproduce logged-out, logged-in, protected-entry, and expired-session UI states without sharing real account credentials.',
  allowedOutput: [
    'runId',
    'fixtureStatus',
    'scenarioKey',
    'authStateKey',
    'accountStateKey',
    'publicPath',
    'httpStatus',
    'messageKey',
    'localeCopyKeys',
    'viewportBreakpoints',
    'safe boolean flags',
  ],
  scenarios: [
    {
      scenarioKey: 'logged_out_public_entry',
      authStateKey: 'logged_out',
      publicPath: '/login?fixture=logged-out',
      expectedHttpStatus: 200,
      protectedRouteAccess: false,
      messageKey: 'auth.fixture.loggedOut',
    },
    {
      scenarioKey: 'logged_in_account_ready',
      authStateKey: 'logged_in',
      accountStateKey: 'active_safe_fixture',
      publicPath: '/mypage?accountfixture=verified',
      expectedHttpStatus: 200,
      protectedRouteAccess: true,
      messageKey: 'auth.fixture.loggedIn',
    },
    {
      scenarioKey: 'protected_entry_requires_login',
      authStateKey: 'login_required',
      publicPath: '/login?fixture=protected-entry',
      expectedHttpStatus: 401,
      protectedRouteAccess: false,
      messageKey: 'auth.fixture.loginRequired',
    },
    {
      scenarioKey: 'session_expired_reauth',
      authStateKey: 'session_expired',
      publicPath: '/login?fixture=session-expired',
      expectedHttpStatus: 401,
      protectedRouteAccess: false,
      messageKey: 'auth.fixture.sessionExpired',
    },
  ],
  localeContract: {
    requiredLocales: ['ko', 'en', 'ja', 'zh-Hans', 'zh-Hant'],
    rawCopyReturned: false,
    keyPrefix: 'auth.fixture.',
  },
  viewportContract: {
    requiredWidthsPx: [390, 400],
    horizontalOverflowAllowed: false,
  },
  forbiddenOutput: [
    'raw email',
    'password',
    'access token',
    'refresh token',
    'cookie',
    'raw user id',
    'provider id',
    'provider payload',
    'API key',
    'database URL',
  ],
  mutationPolicy: {
    createsUser: false,
    logsInUser: false,
    mintsSession: false,
    refreshesSession: false,
    revokesSession: false,
    accountMutation: false,
    passwordMutation: false,
    walletMutation: false,
  },
} as const;

export const EMAIL_RESET_SAFE_INBOX_FIXTURE_CONTRACT = {
  version: '2026-07-10.email-reset-safe-inbox-fixture.v1',
  endpoint: 'GET /api/v1/qa-fixtures/auth/password-reset-inbox-preview',
  status: 'contract_only_read_only',
  purpose:
    'Preview reset request and token-state UI without accessing a real inbox or exposing reset links.',
  allowedOutput: [
    'runId',
    'fixtureStatus',
    'resetStateKey',
    'publicPath',
    'httpStatus',
    'messageKey',
    'maskedEmailHint',
    'localeCopyKeys',
    'safe boolean flags',
  ],
  resetStates: [
    {
      resetStateKey: 'request_success',
      publicPath: '/reset-password?fixture=request-success',
      expectedHttpStatus: 200,
      messageKey: 'auth.reset.fixture.requestSuccess',
      canSavePassword: false,
    },
    {
      resetStateKey: 'token_expired',
      publicPath: '/reset-password?fixture=expired',
      expectedHttpStatus: 410,
      messageKey: 'auth.reset.fixture.expired',
      canSavePassword: false,
    },
    {
      resetStateKey: 'token_invalid',
      publicPath: '/reset-password?fixture=invalid',
      expectedHttpStatus: 400,
      messageKey: 'auth.reset.fixture.invalid',
      canSavePassword: false,
    },
    {
      resetStateKey: 'token_already_used',
      publicPath: '/reset-password?fixture=already-used',
      expectedHttpStatus: 409,
      messageKey: 'auth.reset.fixture.alreadyUsed',
      canSavePassword: false,
    },
  ],
  guard: {
    qaFixtureFlagRequired: true,
    productionMutationSeparated: true,
    realInboxRead: false,
    providerSend: false,
    tokenLookup: false,
    tokenConsume: false,
    passwordUpdate: false,
  },
  forbiddenOutput: [
    'raw email',
    'reset link',
    'reset token',
    'token hash',
    'provider payload',
    'mail body',
    'password',
    'cookie',
    'database URL',
  ],
} as const;
