export const AUTH_QA_ACCOUNT_ACCESS_CONTRACT = {
  version: '2026-05-24.auth-qa-account-access.v3',
  sensitiveValuesRecorded: false,
  secureStorageOnly: [
    'raw email',
    'password',
    'access token',
    'refresh token',
    'cookie',
    'database url',
    'provider secret',
    'provider account credential',
    'provider access token',
    'provider authorization code',
  ],
  credentialSource: {
    storage: 'private_credential_source_only',
    missingRequiredSlotBlock: {
      blockedBy: 'safe QA credential source needed',
      nextAction:
        'Populate required QA slots in a private local credential source, then rerun npm run qa:auth-credential-source.',
      passwordRequestAllowed: false,
      rawCredentialRecordAllowed: false,
    },
    rawValuePolicy: {
      git: false,
      notion: false,
      chat: false,
      logs: false,
    },
    requiredSlotGroups: [
      {
        key: 'verified_email_password',
        purpose: 'verified email-password live QA',
        requiredSlots: ['QA_VERIFIED_EMAIL', 'QA_VERIFIED_PASSWORD'],
        expectedProjection: {
          emailVerified: true,
          emailVerificationStatus: 'verified',
          hasPassword: true,
          isSocialOnly: false,
        },
      },
      {
        key: 'social_only_manual_provider',
        purpose: 'social-only browser QA through the provider login surface',
        requiredSlots: ['QA_SOCIAL_PROVIDER', 'QA_SOCIAL_EMAIL', 'QA_SOCIAL_PASSWORD'],
        expectedProjection: {
          hasPassword: false,
          isSocialOnly: true,
          passwordSetupSurface: true,
        },
      },
    ],
    optionalAutomationSlotGroups: [
      {
        key: 'social_only_provider_token',
        purpose: 'API-level social login smoke when a private provider token exists',
        anyOf: [
          ['QA_SOCIAL_PROVIDER', 'QA_SOCIAL_ACCESS_TOKEN'],
          ['QA_SOCIAL_PROVIDER', 'QA_SOCIAL_AUTH_CODE', 'QA_SOCIAL_REDIRECT_URI'],
        ],
      },
      {
        key: 'secure_social_session_fixture',
        purpose:
          'secure runtime session fixture only when live OAuth/browser login is unavailable',
        requiredSlots: ['QA_SOCIAL_SESSION_USER_ID', 'JWT_ACCESS_SECRET'],
        tokenOutputAllowedOnlyToPrivateFile: true,
      },
    ],
  },
  accounts: [
    {
      key: 'QA_USER',
      purpose: 'normal_user_live_smoke',
      requiredState: {
        userStatus: 'active',
        authAccountRequired: true,
        adminAccessRequired: false,
        artistOperatorRequired: false,
      },
      allowedChecks: [
        'POST /api/v1/auth/login',
        'GET /api/v1/me',
        'GET /api/v1/me/trust',
        'GET /api/v1/debut/policy',
        'POST /api/v1/debut/applications',
      ],
      mayUseForBackstageWrite: false,
      mayUseForCreatorStudio: false,
      recordOnly: ['login possible', 'provider kind', 'email verification status'],
    },
    {
      key: 'QA_CREATOR',
      purpose: 'creator_studio_live_smoke',
      requiredState: {
        userStatus: 'active',
        authAccountRequired: true,
        adminAccessRequired: false,
        artistOperatorRequired: true,
        artistOperatorStatus: 'active',
      },
      allowedChecks: [
        'POST /api/v1/auth/login',
        'GET /api/v1/me',
        'GET /api/v1/me/trust',
        'GET /api/v1/me/creator-studio',
      ],
      mayUseForBackstageWrite: false,
      mayUseForCreatorStudio: true,
      recordOnly: ['login possible', 'artist operator active', 'creator access enabled'],
    },
    {
      key: 'QA_ADMIN',
      purpose: 'backstage_admin_live_smoke',
      requiredState: {
        userStatus: 'active',
        authAccountRequired: true,
        adminAccessRequired: true,
        adminAccessStatus: 'active',
        adminRoleName: 'super_admin',
        adminPermissions: ['*'],
      },
      allowedChecks: [
        'POST /api/v1/auth/login',
        'GET /api/v1/admin/api/v1/me',
        'GET /api/v1/admin/api/v1/backstage/summary',
        'GET /api/v1/admin/api/v1/admin-users',
      ],
      mayUseForBackstageWrite: true,
      mayUseForCreatorStudio: false,
      recordOnly: ['login possible', 'admin role', 'has wildcard permission'],
    },
    {
      key: 'QA_VERIFIED_EMAIL',
      purpose: 'verified_email_password_live_smoke',
      credentialSlots: ['QA_VERIFIED_EMAIL', 'QA_VERIFIED_PASSWORD'],
      requiredState: {
        userStatus: 'active',
        authAccountRequired: true,
        provider: 'email',
        emailVerified: true,
        emailVerificationStatus: 'verified',
        hasPassword: true,
        isSocialOnly: false,
        adminAccessRequired: false,
        artistOperatorRequired: false,
      },
      allowedChecks: [
        'POST /api/v1/auth/login',
        'GET /api/v1/me',
        'GET /api/v1/me/trust',
        'GET /api/v1/debut/policy',
      ],
      mayUseForBackstageWrite: false,
      mayUseForCreatorStudio: false,
      recordOnly: [
        'login possible',
        'email verification status',
        'has password',
        'not social-only',
      ],
    },
    {
      key: 'QA_SOCIAL_ONLY',
      purpose: 'social_only_live_smoke',
      credentialSlots: ['QA_SOCIAL_PROVIDER', 'QA_SOCIAL_EMAIL', 'QA_SOCIAL_PASSWORD'],
      requiredState: {
        userStatus: 'active',
        authAccountRequired: true,
        provider: 'google|kakao|naver',
        emailProviderPasswordRequired: false,
        hasPassword: false,
        isSocialOnly: true,
        adminAccessRequired: false,
        artistOperatorRequired: false,
      },
      allowedChecks: [
        'POST /api/v1/auth/social/login',
        'GET /api/v1/me',
        'GET /api/v1/me/trust',
        'PATCH /api/v1/me/password/setup',
      ],
      mayUseForBackstageWrite: false,
      mayUseForCreatorStudio: false,
      recordOnly: [
        'provider kind',
        'login possible or secure session prepared',
        'hasPassword=false',
        'isSocialOnly=true',
      ],
    },
  ],
  authority: {
    normalUser: ['users.status', 'user_auth_accounts'],
    creatorAccess: ['artist_operators.status', 'artist_operators.permissions'],
    adminAccess: [
      'admin_users.status',
      'admin_roles.name',
      'admin_roles.permissions',
      'ADMIN_EMAILS bootstrap fallback',
    ],
  },
  accountSecurity: {
    passwordReset: {
      consumesActionTokenOnce: true,
      updatesEmailPasswordHashOnly: true,
      revokesActiveRefreshSessions: true,
      rawTokenReturned: false,
      passwordReturned: false,
      emailPrefill: {
        source: 'GET /api/v1/auth/password-resets/inspect',
        value: 'masked_email_only',
        rawEmailReturned: false,
        rawTokenReturned: false,
        tokenHashReturned: false,
        passwordReturned: false,
        cookieReturned: false,
        confirmWithoutEmailInput: true,
        invalidOrExpiredTokenEmailReturned: false,
      },
    },
    passwordChange: {
      requiresExistingEmailPasswordHash: true,
      socialOnlyChangePasswordBlocked: true,
      successfulChangeRevokesActiveRefreshSessions: true,
      rawCurrentPasswordLogged: false,
      rawNewPasswordLogged: false,
    },
    socialOnlyProjection: {
      sourceOfTruth: 'user_auth_accounts',
      myPageSettingsProjectionSource: 'GET /api/v1/me',
      emailPasswordProjectionSource: 'user_auth_accounts.passwordHash',
      exposesProviderKind: true,
      exposesHasPasswordBoolean: true,
      exposesIsSocialOnlyBoolean: true,
      passwordResetCtaAllowed: false,
      passwordSetupSurfaceAllowed: true,
      rawStatusCopyReturned: false,
      exposesProviderCredential: false,
      exposesCookieOrToken: false,
    },
    sessionRevokeAuditProjection: {
      sourceOfTruth: 'user_refresh_tokens.revokedAt',
      passwordResetRevokesActiveSessions: true,
      passwordResetActionKey: 'auth.password_reset.session_revoke',
      adminRevokeActionKey: 'admin.user.sessions.revoke',
      readModel: 'admin audit event read model',
      readOnlyProjection: true,
      rawRefreshTokenReturned: false,
      refreshTokenHashReturned: false,
      sessionCookieReturned: false,
      passwordReturned: false,
      rawEmailReturned: false,
      providerCredentialReturned: false,
      actorEmailMasked: true,
      requestIdAllowed: true,
    },
  },
  qaSessionFixtureAuthBoundary: {
    version: '2026-06-22.qa-session-fixture-auth-boundary.v1',
    status: 'contract_only_no_session_minting',
    purpose:
      'Allow live smoke teams to verify read-only QA fixtures without requesting account passwords.',
    fixtureAccessMode: 'read_only',
    sessionMintingByThisContract: false,
    productionAutoProvision: false,
    allowedPrincipals: [
      {
        key: 'disposable_qa_owner',
        requiredUserStatus: 'active',
        realUserAllowed: false,
        allowedScopes: ['own_qa_fixture_read'],
      },
      {
        key: 'disposable_qa_operator',
        requiredUserStatus: 'active',
        realUserAllowed: false,
        requiredAccess: ['artist_operator_active_or_admin_read_permission'],
        allowedScopes: ['qa_fixture_read', 'qa_fixture_visibility_check'],
      },
    ],
    boundaryChecks: [
      'authenticate_existing_session_or_private_credential_fixture',
      'resolve_disposable_qa_user_by_run_id',
      'reject_real_user_or_missing_run_id',
      'require_read_only_fixture_scope',
      'return_sanitized_fixture_projection',
    ],
    forbiddenMixing: {
      generalUserSessionCanReadFixture: false,
      fixtureSessionCanMutateRealUserData: false,
      fixtureRowsVisibleWithoutRunId: false,
      fixtureRowsVisibleToUnapprovedPrincipal: false,
    },
    allowedOutput: [
      'runId',
      'qaPrincipalKey',
      'safeUserId',
      'fixtureScope',
      'HTTP status',
      'stable code/messageKey',
      'readOnly boolean',
      'nextOwner routing key',
    ],
    forbiddenOutput: [
      'raw email',
      'password',
      'access token',
      'refresh token',
      'cookie',
      'database url',
      'raw session id',
      'environment value',
    ],
  },
  disposableQaAccountOwnershipBoundary: {
    version: '2026-06-24.disposable-qa-account-ownership-boundary.v1',
    status: 'contract_only_no_production_mutation',
    purpose:
      'Keep disposable QA fixture accounts isolated from real user owner-only API data.',
    accountClassification: {
      sourceOfTruth: ['private QA runbook slot', 'server-side QA run id label'],
      realUserAllowed: false,
      productionAutoProvision: false,
      requiresQaRunId: true,
      requiresDisposableLabel: true,
    },
    ownerOnlyApiGuard: {
      authority: 'authenticated currentUser.id',
      allowedUserIdSource: 'server session principal only',
      forbiddenUserIdSources: [
        'request body userId',
        'query userId',
        'fixture label supplied by client',
        'masked UUID copied from QA notes',
      ],
      whereClauseRequired: {
        ownerUserId: 'currentUser.id',
        deletedAt: null,
      },
      crossUserFixtureReadAllowed: false,
      realUserDataVisibleToDisposableAccount: false,
      disposableDataVisibleToRealUser: false,
    },
    mutationPolicy: {
      productionUserMutation: false,
      ownerOnlyWriteSmoke: false,
      accountDeletion: false,
      passwordReset: false,
      sessionMinting: false,
      walletLedgerMutation: false,
      settlementOrPayoutMutation: false,
    },
    safeOutputPolicy: {
      recordFixtureLabel: true,
      recordMaskedStableUserRef: true,
      recordRawEmail: false,
      recordPassword: false,
      recordToken: false,
      recordCookie: false,
      recordRawUuid: false,
      recordDatabaseUrl: false,
    },
  },
  liveAccessSelfCheck: {
    task: '#458',
    script: 'npm run qa:auth-access-self-check',
    confirmEnv: 'AUTH_QA_ACCESS_VERIFY_CONFIRM',
    confirmValue: 'VERIFY_AUTH_QA_ACCESS_SELF_CHECK',
    dryRunEnv: 'AUTH_QA_ACCESS_VERIFY_DRY_RUN',
    apiBaseEnv: ['AUTH_QA_ACCESS_API_BASE', 'AUTH_QA_API_BASE', 'API_BASE_URL'],
    requiredSlotGroups: [
      {
        key: 'qa_creator',
        requiredSlots: ['QA_CREATOR_EMAIL', 'QA_CREATOR_PASSWORD'],
        checks: [
          'POST /api/v1/auth/login',
          'GET /api/v1/me',
          'GET /api/v1/me/trust',
          'GET /api/v1/me/creator-studio',
        ],
        passCriteria: {
          creatorStudioAccessEnabled: true,
          artistOperatorAccess: true,
          accessSource: 'artist_operator',
        },
        failureOwner: {
          missingCredentials: 'private_credential_owner',
          missingArtistOperator: 'creator_access_owner',
          serverError: 'backend_owner',
        },
      },
      {
        key: 'qa_admin',
        requiredSlots: ['QA_ADMIN_EMAIL', 'QA_ADMIN_PASSWORD'],
        checks: [
          'POST /api/v1/auth/login',
          'GET /api/v1/admin/api/v1/me',
          'GET /api/v1/admin/api/v1/backstage/summary',
        ],
        passCriteria: {
          adminAccessEnabled: true,
          roleKind: 'super_admin',
          hasWildcardPermission: true,
          backstageSummaryAccess: true,
        },
        failureOwner: {
          missingCredentials: 'private_credential_owner',
          missingAdminAccess: 'backstage_admin_owner',
          missingPermission: 'backstage_permission_owner',
          serverError: 'backend_owner',
        },
      },
    ],
    allowedOutput: [
      'slot names present/missing',
      'HTTP status',
      'stable code/messageKey',
      'access enabled booleans',
      'safe role kind',
      'permission booleans',
      'nextOwner routing key',
    ],
    forbiddenOutput: [
      'raw email',
      'password',
      'access token',
      'refresh token',
      'cookie',
      'database url',
      'raw response body',
      'environment value',
    ],
  },
  missingAccountRunbook: [
    'Prepare credentials only in a private secure channel or local security file.',
    'Create or identify an active user without recording raw email/password in Git or Notion.',
    'For QA_VERIFIED_EMAIL, use an active email-password user whose emailVerification.status is verified.',
    'For QA_SOCIAL_ONLY, use a provider-owned account or secure session fixture whose /me projection is hasPassword=false and isSocialOnly=true.',
    'For QA_CREATOR, grant an active artist operator row through an existing super-admin path.',
    'For QA_ADMIN, prefer an active admin_users row with the super_admin role and * permission.',
    'Verify with /me, /me/trust, and /admin/api/v1/me responses; record only roles and booleans.',
  ],
} as const;
