export const AUTH_QA_ACCOUNT_ACCESS_CONTRACT = {
  version: '2026-05-20.auth-qa-account-access.v1',
  sensitiveValuesRecorded: false,
  secureStorageOnly: [
    'raw email',
    'password',
    'access token',
    'refresh token',
    'cookie',
    'database url',
    'provider secret',
  ],
  accounts: [
    {
      key: 'QA_USER',
      purpose: 'normal_user_live_smoke',
      requiredState: {
        userStatus: 'active',
        authAccountRequired: true,
        adminAccessRequired: false,
        artistOperatorRequired: false,
      },
      allowedChecks: [
        'POST /api/v1/auth/login',
        'GET /api/v1/me',
        'GET /api/v1/me/trust',
        'GET /api/v1/debut/policy',
        'POST /api/v1/debut/applications',
      ],
      mayUseForBackstageWrite: false,
      mayUseForCreatorStudio: false,
      recordOnly: ['login possible', 'provider kind', 'email verification status'],
    },
    {
      key: 'QA_CREATOR',
      purpose: 'creator_studio_live_smoke',
      requiredState: {
        userStatus: 'active',
        authAccountRequired: true,
        adminAccessRequired: false,
        artistOperatorRequired: true,
        artistOperatorStatus: 'active',
      },
      allowedChecks: [
        'POST /api/v1/auth/login',
        'GET /api/v1/me',
        'GET /api/v1/me/trust',
        'GET /api/v1/me/creator-studio',
      ],
      mayUseForBackstageWrite: false,
      mayUseForCreatorStudio: true,
      recordOnly: ['login possible', 'artist operator active', 'creator access enabled'],
    },
    {
      key: 'QA_ADMIN',
      purpose: 'backstage_admin_live_smoke',
      requiredState: {
        userStatus: 'active',
        authAccountRequired: true,
        adminAccessRequired: true,
        adminAccessStatus: 'active',
        adminRoleName: 'super_admin',
        adminPermissions: ['*'],
      },
      allowedChecks: [
        'POST /api/v1/auth/login',
        'GET /api/v1/admin/api/v1/me',
        'GET /api/v1/admin/api/v1/backstage/summary',
        'GET /api/v1/admin/api/v1/admin-users',
      ],
      mayUseForBackstageWrite: true,
      mayUseForCreatorStudio: false,
      recordOnly: ['login possible', 'admin role', 'has wildcard permission'],
    },
  ],
  authority: {
    normalUser: ['users.status', 'user_auth_accounts'],
    creatorAccess: ['artist_operators.status', 'artist_operators.permissions'],
    adminAccess: [
      'admin_users.status',
      'admin_roles.name',
      'admin_roles.permissions',
      'ADMIN_EMAILS bootstrap fallback',
    ],
  },
  missingAccountRunbook: [
    'Prepare credentials only in a private secure channel or local security file.',
    'Create or identify an active user without recording raw email/password in Git or Notion.',
    'For QA_CREATOR, grant an active artist operator row through an existing super-admin path.',
    'For QA_ADMIN, prefer an active admin_users row with the super_admin role and * permission.',
    'Verify with /me, /me/trust, and /admin/api/v1/me responses; record only roles and booleans.',
  ],
} as const;
