export const QA_FIXTURE_HANDOFF_CONTRACT = {
  version: '2026-06-28.qa-fixture-handoff.v1',
  allowedOutput: [
    'runId',
    'fixtureStatus',
    'publicProfileHandle',
    'publicProfilePath',
    'publicProfileApiPath',
    'followersApiPath',
    'followingApiPath',
    'blockApiPath',
    'followerPublicHandle',
    'HTTP status',
    'stable code/messageKey',
    'safe boolean flags',
    'nextOwner routing key',
  ],
  conditionallyAllowedOutput: {
    qaOnlyRowId: 'only for disposable QA rows and only when needed for cleanup',
    qaOnlyRowStatus: 'active/inactive/deleted status only',
    maskedStableUserRef: 'masked stable ref only, never raw UUID copied from private notes',
  },
  forbiddenOutput: [
    'raw email',
    'password',
    'access token',
    'refresh token',
    'cookie',
    'API key',
    'database URL',
    'raw session id',
    'raw user UUID copied from private notes',
    'provider credential',
    'environment value',
  ],
  handoffRules: {
    productionAutoSeed: false,
    realUserFixtureMixing: false,
    confirmedRunRequiresApprovedEnvironment: true,
    dryRunOutputIsNotLivePassEvidence: true,
    recordOnlyNonSecretHandoffFields: true,
    nextOwnerRequired: true,
  },
  mutationBoundaries: {
    followBlockFixtureConfirmedRun: 'qa_only_disposable_rows_after_approval',
    realUserFollowBlockMutation: false,
    walletMutation: false,
    settlementMutation: false,
    payoutMutation: false,
    accountPasswordMutation: false,
    sessionMinting: false,
  },
} as const;
