export const WALLET_READONLY_QA_FIXTURE_CONTRACT = {
  version: '2026-07-10.wallet-readonly-qa-fixture.v1',
  endpoint: 'GET /api/v1/qa-fixtures/wallet/states',
  status: 'contract_only_read_only',
  purpose:
    'Let QA verify charge and wallet UI states without payment provider calls or wallet ledger mutations.',
  allowedOutput: [
    'runId',
    'fixtureStatus',
    'walletStateKey',
    'publicPath',
    'balanceDisplayKey',
    'productDisplayKeys',
    'firstChargeBonusKey',
    'paymentStatusKey',
    'messageKey',
    'safe boolean flags',
  ],
  states: [
    {
      walletStateKey: 'balance_ready',
      publicPath: '/charge?walletFixture=balance-ready',
      balanceDisplayKey: 'wallet.fixture.balanceReady',
      paymentStatusKey: 'wallet.fixture.status.ready',
    },
    {
      walletStateKey: 'products_ready',
      publicPath: '/charge?walletFixture=products-ready',
      productDisplayKeys: ['wallet.product.small', 'wallet.product.medium', 'wallet.product.large'],
      paymentStatusKey: 'wallet.fixture.status.productsReady',
    },
    {
      walletStateKey: 'first_charge_bonus_available',
      publicPath: '/charge?walletFixture=first-charge-bonus',
      firstChargeBonusKey: 'wallet.fixture.firstChargeBonus.available',
      paymentStatusKey: 'wallet.fixture.status.bonusPreview',
    },
    {
      walletStateKey: 'payment_pending',
      publicPath: '/charge?walletFixture=pending',
      paymentStatusKey: 'wallet.fixture.status.pending',
    },
    {
      walletStateKey: 'payment_failed',
      publicPath: '/charge?walletFixture=failed',
      paymentStatusKey: 'wallet.fixture.status.failed',
    },
    {
      walletStateKey: 'payment_refunded',
      publicPath: '/charge?walletFixture=refunded',
      paymentStatusKey: 'wallet.fixture.status.refunded',
    },
  ],
  mutationPolicy: {
    walletDebit: false,
    walletCredit: false,
    paymentOrderCreate: false,
    paymentProviderCall: false,
    refundMutation: false,
    walletLedgerWrite: false,
    settlementMutation: false,
    payoutMutation: false,
  },
  forbiddenOutput: [
    'transaction id',
    'wallet ledger id',
    'payment order id',
    'provider payment key',
    'provider payload',
    'API key',
    'database URL',
    'raw user id',
    'raw receipt',
  ],
} as const;
