export const SERVER_AUTHORITY_WALLET_POLICY = {
  policyVersion: '2026-05-21.server-authority-ledger-v1',
  clientSubmittedBalanceTrusted: false,
  clientSubmittedPriceTrusted: false,
  clientSubmittedSettlementTrusted: false,
  offlinePaidActionAllowed: false,
  allWalletDebitsRequireServerLedgerBalanceCheck: true,
  allWalletDebitsRequireAtomicNonNegativeUpdate: true,
  allWalletMutationsRequireIdempotencyOrProviderTransactionKey: true,
  localTestGrantRequiresEnvGate: true,
  localTestGrantRequiresIdempotencyKey: true,
  paymentOrderReplayRequiresSameUserProductAndProvider: true,
  paymentWebhookRawProviderPayloadStored: false,
  purchaseCreditsRequireProviderVerification: true,
  appIntegrityIsAdvisoryOnly: true,
  rawPurchaseTokensLogged: false,
} as const;

export const CLIENT_ECONOMIC_TAMPER_FIELDS = [
  'balanceLumina',
  'cachedBalance',
  'priceLumina',
  'paidAmount',
  'amountLumina',
  'refundRate',
  'settlementShare',
  'walletLedgerId',
  'providerResult',
] as const;

export const WALLET_LEDGER_SOURCE_CONTRACT = [
  {
    source: 'payment_purchase_credit',
    direction: 'credit',
    ledgerType: 'purchase',
    serverAuthority: 'provider_verified_purchase',
    idempotency: 'provider_transaction_id',
  },
  {
    source: 'first_charge_bonus',
    direction: 'credit',
    ledgerType: 'first_charge_bonus',
    serverAuthority: 'server_derived_bonus',
    idempotency: 'user_once_key',
  },
  {
    source: 'gift_order',
    direction: 'debit',
    ledgerType: 'gift_spend',
    serverAuthority: 'wallet_account_cached_balance',
    idempotency: 'client_idempotency_key',
  },
  {
    source: 'boost_paid_like',
    direction: 'debit',
    ledgerType: 'boost_spend',
    serverAuthority: 'wallet_account_cached_balance',
    idempotency: 'client_idempotency_key',
  },
  {
    source: 'premium_video_unlock',
    direction: 'debit',
    ledgerType: 'premium_video_spend',
    serverAuthority: 'wallet_account_cached_balance',
    idempotency: 'client_idempotency_key',
  },
  {
    source: 'chat_feature_order',
    direction: 'debit',
    ledgerType: 'chat_feature_spend',
    serverAuthority: 'wallet_account_cached_balance',
    idempotency: 'client_idempotency_key',
  },
  {
    source: 'premium_chat_room_open',
    direction: 'debit',
    ledgerType: 'premium_chat_open',
    serverAuthority: 'premium_chat_room_policy_and_wallet_account_cached_balance',
    idempotency: 'client_idempotency_key',
  },
  {
    source: 'premium_chat_donation',
    direction: 'debit',
    ledgerType: 'premium_chat_donation',
    serverAuthority: 'wallet_account_cached_balance',
    idempotency: 'client_idempotency_key',
  },
  {
    source: 'premium_chat_room_refund',
    direction: 'credit',
    ledgerType: 'refund',
    serverAuthority: 'server_refund_policy_and_moderation_outcome',
    idempotency: 'server_room_refund_key',
  },
  {
    source: 'fan_letter',
    direction: 'debit',
    ledgerType: 'fan_letter_spend',
    serverAuthority: 'wallet_account_cached_balance',
    idempotency: 'client_idempotency_key',
  },
  {
    source: 'user_gift_transfer_send',
    direction: 'debit',
    ledgerType: 'user_gift_send',
    serverAuthority: 'wallet_account_cached_balance',
    idempotency: 'client_idempotency_key',
  },
  {
    source: 'user_gift_transfer_receive',
    direction: 'credit',
    ledgerType: 'user_gift_receive',
    serverAuthority: 'paired_server_transfer',
    idempotency: 'client_idempotency_key',
  },
  {
    source: 'chat_feature_generation_refund',
    direction: 'credit',
    ledgerType: 'refund',
    serverAuthority: 'server_failure_reversal',
    idempotency: 'server_order_refund_key',
  },
  {
    source: 'admin_wallet_adjustment',
    direction: 'credit_or_debit',
    ledgerType: 'admin_wallet_adjustment',
    serverAuthority: 'super_admin_audited_operation',
    idempotency: 'server_batch_key',
  },
  {
    source: 'local_test_grant',
    direction: 'credit',
    ledgerType: 'event_grant',
    serverAuthority: 'non_production_env_gate_and_server_amount',
    idempotency: 'client_idempotency_key_required',
  },
] as const;

export const WALLET_MUTATION_GUARD_STEPS = {
  debit: [
    'require_idempotency_key_before_wallet_lookup',
    'resolve_price_or_amount_from_server_product_policy_or_validated_transfer_body',
    'fetch_active_wallet_accounts_row',
    'atomic_update_many_cached_balance_gte_amount',
    'write_wallet_ledger_and_domain_record_in_same_transaction',
  ],
  credit: [
    'require_provider_transaction_or_server_idempotency_key',
    'derive_credit_amount_on_server',
    'dedupe_existing_ledger_or_provider_transaction',
    'increment_cached_balance_and_write_wallet_ledger_in_same_transaction',
  ],
  failClosed: [
    'insufficient_balance_creates_no_wallet_ledger',
    'idempotency_mismatch_creates_no_wallet_mutation',
    'provider_replay_creates_no_duplicate_credit',
  ],
} as const;

export const APP_WEB_LUMINA_TAMPER_DEFENSE_CHECKLIST = [
  {
    surface: 'wallet_balance',
    endpoints: ['GET /api/v1/wallet', 'GET /api/v1/me/summary'],
    mutation: false,
    clientEconomicFieldsTrusted: false,
    authority: ['wallet_accounts.cached_balance'],
    idempotencyOrProviderTransactionKey: 'not_applicable_read_only',
    doubleDebitGuard: 'not_applicable_read_only',
  },
  {
    surface: 'paid_like_boost',
    endpoints: [
      'POST /api/v1/boost-campaigns/:campaignId/like',
      'POST /api/v1/boost-campaigns/:campaignId/boost',
    ],
    mutation: true,
    clientEconomicFieldsTrusted: false,
    rejectedOrIgnoredFields: CLIENT_ECONOMIC_TAMPER_FIELDS,
    authority: ['server boost product/campaign price', 'wallet_accounts.cached_balance'],
    idempotencyOrProviderTransactionKey: 'client_idempotency_key',
    doubleDebitGuard: 'wallet conditional update and boost event idempotency',
  },
  {
    surface: 'chat_feature_product',
    endpoints: ['POST /api/v1/chat-feature-orders'],
    mutation: true,
    clientEconomicFieldsTrusted: false,
    rejectedOrIgnoredFields: CLIENT_ECONOMIC_TAMPER_FIELDS,
    authority: ['chat_feature_products.price_lumina', 'wallet_accounts.cached_balance'],
    idempotencyOrProviderTransactionKey: 'client_idempotency_key',
    doubleDebitGuard: 'chat_feature_orders.idempotency_key and wallet ledger key',
  },
  {
    surface: 'premium_chat_room_and_support',
    endpoints: [
      'POST /api/v1/chat/premium-rooms',
      'POST /api/v1/chat/sessions/:sessionId/donations',
    ],
    mutation: false,
    clientEconomicFieldsTrusted: false,
    rejectedOrIgnoredFields: CLIENT_ECONOMIC_TAMPER_FIELDS,
    authority: ['server premium chat room/support policy', 'wallet_accounts.cached_balance'],
    idempotencyOrProviderTransactionKey: 'client_idempotency_key_required_when_enabled',
    doubleDebitGuard:
      'mutation_blocked_until_room_or_donation_storage_exists_then_idempotency_fingerprint_and_atomic_cached_balance_gte_amount',
  },
  {
    surface: 'premium_video_unlock',
    endpoints: ['POST /api/v1/premium-videos/:productId/unlock'],
    mutation: true,
    clientEconomicFieldsTrusted: false,
    rejectedOrIgnoredFields: CLIENT_ECONOMIC_TAMPER_FIELDS,
    authority: ['premium_video_products.price_lumina', 'wallet_accounts.cached_balance'],
    idempotencyOrProviderTransactionKey: 'client_idempotency_key',
    doubleDebitGuard: 'user unlock uniqueness and wallet ledger key',
  },
  {
    surface: 'donation_gift_fan_letter_user_gift',
    endpoints: [
      'POST /api/v1/gifts/orders',
      'POST /api/v1/fan-letters',
      'POST /api/v1/user-gifts/transfers',
    ],
    mutation: true,
    clientEconomicFieldsTrusted: false,
    rejectedOrIgnoredFields: CLIENT_ECONOMIC_TAMPER_FIELDS,
    authority: ['server product/transfer policy', 'wallet_accounts.cached_balance'],
    idempotencyOrProviderTransactionKey: 'client_idempotency_key',
    doubleDebitGuard: 'domain idempotency key and wallet conditional update',
  },
  {
    surface: 'charge_purchase_credit',
    endpoints: [
      'POST /api/v1/payments/orders',
      'POST /api/v1/payments/webhooks/:provider',
    ],
    mutation: true,
    clientEconomicFieldsTrusted: false,
    rejectedOrIgnoredFields: CLIENT_ECONOMIC_TAMPER_FIELDS,
    authority: ['server product table', 'provider verified transaction'],
    idempotencyOrProviderTransactionKey: 'provider_transaction_id',
    doubleDebitGuard:
      'payment order status transition, provider transaction dedupe, and sanitized webhook audit payload',
  },
  {
    surface: 'refund_reversal',
    endpoints: ['provider refund tracking', 'server technical failure reversal'],
    mutation: true,
    clientEconomicFieldsTrusted: false,
    rejectedOrIgnoredFields: CLIENT_ECONOMIC_TAMPER_FIELDS,
    authority: ['server refund policy', 'existing wallet ledger/order state'],
    idempotencyOrProviderTransactionKey: 'server_refund_key',
    doubleDebitGuard: 'refund ledger idempotency key',
  },
] as const;

export const APP_PURCHASE_VERIFICATION_CONTRACT = [
  {
    platform: 'google_play',
    purchaseProof: 'purchase_token',
    serverVerification: 'google_play_developer_api',
    integritySignal: 'play_integrity_api',
    integritySignalRequiredForLedgerCredit: false,
    rawProofLogged: false,
  },
  {
    platform: 'apple_app_store',
    purchaseProof: 'signed_transaction_or_app_store_server_api_payload',
    serverVerification: 'app_store_server_api_or_signed_transaction_validation',
    integritySignal: 'app_attest_or_device_check',
    integritySignalRequiredForLedgerCredit: false,
    rawProofLogged: false,
  },
] as const;
