export const SERVER_AUTHORITY_WALLET_POLICY = {
  policyVersion: '2026-05-23.app-tamper-server-trust-v1',
  clientSubmittedBalanceTrusted: false,
  clientSubmittedPriceTrusted: false,
  clientSubmittedSettlementTrusted: false,
  clientSubmittedPaymentSuccessTrusted: false,
  clientSubmittedBonusTrusted: false,
  offlinePaidActionAllowed: false,
  allWalletDebitsRequireServerLedgerBalanceCheck: true,
  allWalletDebitsRequireAtomicNonNegativeUpdate: true,
  allWalletMutationsRequireIdempotencyOrProviderTransactionKey: true,
  localTestGrantRequiresEnvGate: true,
  localTestGrantRequiresIdempotencyKey: true,
  paymentOrderReplayRequiresSameUserProductAndProvider: true,
  paymentWebhookRawProviderPayloadStored: false,
  purchaseCreditsRequireProviderVerification: true,
  appIntegrityIsAdvisoryOnly: true,
  rawPurchaseTokensLogged: false,
} as const;

export const WALLET_MUTATION_SURFACE_GUARD_MATRIX = [
  {
    surface: 'payment_purchase_credit',
    direction: 'credit',
    authority: ['server product table', 'provider verified transaction'],
    duplicateGuard: 'provider_transaction_id_unique',
    negativeBalanceGuard: 'not_applicable_credit',
    ledgerWriteAtomicity: 'payment_order_status_and_wallet_ledger_in_transaction',
    clientEconomicFieldsTrusted: false,
  },
  {
    surface: 'premium_chat_room_open',
    direction: 'debit',
    authority: ['server room tier policy', 'wallet_accounts.cached_balance'],
    duplicateGuard: 'room_open_idempotency_fingerprint',
    negativeBalanceGuard: 'atomic_update_many_cached_balance_gte_server_amount',
    ledgerWriteAtomicity: 'premium_chat_room_and_wallet_ledger_in_transaction',
    clientEconomicFieldsTrusted: false,
  },
  {
    surface: 'premium_chat_donation',
    direction: 'debit',
    authority: ['server normalized donation amount', 'wallet_accounts.cached_balance'],
    duplicateGuard: 'client_idempotency_key',
    negativeBalanceGuard: 'atomic_update_many_cached_balance_gte_server_amount',
    ledgerWriteAtomicity: 'donation_and_wallet_ledger_in_transaction',
    clientEconomicFieldsTrusted: false,
  },
  {
    surface: 'premium_chat_message_debit',
    direction: 'debit',
    authority: [
      'server visible two-way sentence pair meter',
      'wallet_accounts.cached_balance',
    ],
    duplicateGuard: 'server_message_pair_meter_key',
    negativeBalanceGuard: 'atomic_update_many_cached_balance_gte_server_amount',
    ledgerWriteAtomicity: 'meter_window_and_wallet_ledger_in_transaction',
    clientEconomicFieldsTrusted: false,
  },
  {
    surface: 'premium_chat_room_refund',
    direction: 'credit',
    authority: ['server refund policy', 'moderation outcome', 'existing room ledger'],
    duplicateGuard: 'server_room_refund_key',
    negativeBalanceGuard: 'not_applicable_credit',
    ledgerWriteAtomicity: 'refund_status_and_wallet_ledger_in_transaction',
    clientEconomicFieldsTrusted: false,
  },
] as const;

export const CLIENT_ECONOMIC_TAMPER_FIELDS = [
  'balanceLumina',
  'cachedBalance',
  'priceLumina',
  'paidAmount',
  'amountLumina',
  'refundRate',
  'settlementShare',
  'walletLedgerId',
  'providerResult',
  'paymentSuccess',
  'bonusAmount',
  'sku',
  'productSku',
] as const;

export const APP_TAMPER_THREAT_MODEL = [
  {
    threat: 'client_balance_or_bonus_display_tamper',
    examples: ['modified_app_balance', 'browser_console_balance', 'fake_bonus_badge'],
    trustedClientFields: false,
    serverGate: 'wallet_accounts.cached_balance_and_wallet_ledger',
    expectedDecision: 'ignore_client_display_values',
    walletMutationAllowedFromClientProof: false,
  },
  {
    threat: 'client_payment_success_spoof',
    examples: ['fake_success_redirect', 'forged_provider_result'],
    trustedClientFields: false,
    serverGate: 'server_verified_provider_transaction',
    expectedDecision: 'no_credit_without_provider_verification',
    walletMutationAllowedFromClientProof: false,
  },
  {
    threat: 'offline_replay_or_retry',
    examples: ['offline_queue_replay', 'duplicate_submit', 'same_key_changed_body'],
    trustedClientFields: false,
    serverGate: 'user_scoped_idempotency_key_and_request_fingerprint',
    expectedDecision: 'same_fingerprint_replay_or_conflict_before_wallet_lookup',
    walletMutationAllowedFromClientProof: false,
  },
  {
    threat: 'amount_or_sku_tamper',
    examples: ['priceLumina_zero', 'amountLumina_override', 'rogue_product_sku'],
    trustedClientFields: false,
    serverGate: 'server_product_catalog_and_domain_policy',
    expectedDecision: 'resolve_amount_on_server_or_reject',
    walletMutationAllowedFromClientProof: false,
  },
  {
    threat: 'refund_or_settlement_tamper',
    examples: ['client_refundRate_override', 'client_settlementShare_override'],
    trustedClientFields: false,
    serverGate: 'server_refund_policy_existing_order_and_ledger_state',
    expectedDecision: 'ignore_client_refund_and_settlement_values',
    walletMutationAllowedFromClientProof: false,
  },
] as const;

export const WALLET_RISK_LOG_CONTRACT = {
  requiredFields: [
    'requestId',
    'userId',
    'sessionOrActionId',
    'surface',
    'idempotencyScope',
    'requestFingerprintHash',
    'serverAmountLumina',
    'decision',
    'reasonCode',
  ],
  optionalFields: [
    'provider',
    'providerTransactionId',
    'serverProductId',
    'riskSignals',
  ],
  forbiddenFields: [
    'rawIdempotencyKey',
    'rawPurchaseToken',
    'rawProviderPayload',
    'rawIntegrityPayload',
    'cookie',
    'password',
    'dbUrl',
    'signedUrl',
    'providerSecret',
  ],
  clientEconomicValuesStoredAsAuthority: false,
  providerSecretsLogged: false,
  rawProviderPayloadLogged: false,
} as const;

export const APP_TAMPER_CONTRACT_TEST_CASES = [
  {
    caseId: 'client_balance_tamper_ignored',
    tamperedFields: ['balanceLumina', 'cachedBalance'],
    expectedGate: 'wallet_accounts.cached_balance',
    expectedOutcome: 'server_amount_and_balance_only',
  },
  {
    caseId: 'fake_payment_success_rejected',
    tamperedFields: ['providerResult', 'paymentSuccess'],
    expectedGate: 'provider_verified_transaction',
    expectedOutcome: 'no_purchase_credit_without_verified_provider_event',
  },
  {
    caseId: 'idempotency_replay_same_body',
    tamperedFields: [],
    expectedGate: 'request_fingerprint_match',
    expectedOutcome: 'replay_existing_projection_without_duplicate_ledger',
  },
  {
    caseId: 'idempotency_replay_changed_body',
    tamperedFields: ['amountLumina', 'productSku'],
    expectedGate: 'request_fingerprint_mismatch',
    expectedOutcome: 'stable_conflict_before_wallet_lookup',
  },
  {
    caseId: 'sku_or_amount_tamper_rejected',
    tamperedFields: ['sku', 'priceLumina', 'amountLumina'],
    expectedGate: 'server_product_catalog_and_policy',
    expectedOutcome: 'reject_or_use_server_amount_never_client_amount',
  },
] as const;

export const WALLET_LEDGER_SOURCE_CONTRACT = [
  {
    source: 'payment_purchase_credit',
    direction: 'credit',
    ledgerType: 'purchase',
    serverAuthority: 'provider_verified_purchase',
    idempotency: 'provider_transaction_id',
  },
  {
    source: 'first_charge_bonus',
    direction: 'credit',
    ledgerType: 'first_charge_bonus',
    serverAuthority: 'server_derived_bonus',
    idempotency: 'user_once_key',
  },
  {
    source: 'gift_order',
    direction: 'debit',
    ledgerType: 'gift_spend',
    serverAuthority: 'wallet_account_cached_balance',
    idempotency: 'client_idempotency_key',
  },
  {
    source: 'boost_paid_like',
    direction: 'debit',
    ledgerType: 'boost_spend',
    serverAuthority: 'wallet_account_cached_balance',
    idempotency: 'client_idempotency_key',
  },
  {
    source: 'premium_video_unlock',
    direction: 'debit',
    ledgerType: 'premium_video_spend',
    serverAuthority: 'wallet_account_cached_balance',
    idempotency: 'client_idempotency_key',
  },
  {
    source: 'chat_feature_order',
    direction: 'debit',
    ledgerType: 'chat_feature_spend',
    serverAuthority: 'wallet_account_cached_balance',
    idempotency: 'client_idempotency_key',
  },
  {
    source: 'premium_chat_room_open',
    direction: 'debit',
    ledgerType: 'premium_chat_open',
    serverAuthority: 'premium_chat_room_policy_and_wallet_account_cached_balance',
    idempotency: 'client_idempotency_key',
  },
  {
    source: 'premium_chat_message',
    direction: 'debit',
    ledgerType: 'premium_chat_message',
    serverAuthority: 'server_visible_two_way_sentence_pair_meter',
    idempotency: 'server_message_pair_meter_key',
  },
  {
    source: 'premium_chat_donation',
    direction: 'debit',
    ledgerType: 'premium_chat_donation',
    serverAuthority: 'wallet_account_cached_balance',
    idempotency: 'client_idempotency_key',
  },
  {
    source: 'premium_chat_room_refund',
    direction: 'credit',
    ledgerType: 'refund',
    serverAuthority: 'server_refund_policy_and_moderation_outcome',
    idempotency: 'server_room_refund_key',
  },
  {
    source: 'premium_chat_room_refund_restriction',
    direction: 'credit',
    ledgerType: 'premium_chat_room_company_revenue',
    serverAuthority: 'server_refund_restriction_outcome',
    idempotency: 'server_admin_decision_key',
  },
  {
    source: 'premium_chat_room_refund_restriction',
    direction: 'credit',
    ledgerType: 'premium_chat_room_artist_compensation',
    serverAuthority: 'server_refund_restriction_outcome',
    idempotency: 'server_admin_decision_key',
  },
  {
    source: 'fan_letter',
    direction: 'debit',
    ledgerType: 'fan_letter_spend',
    serverAuthority: 'wallet_account_cached_balance',
    idempotency: 'client_idempotency_key',
  },
  {
    source: 'user_gift_transfer_send',
    direction: 'debit',
    ledgerType: 'user_gift_send',
    serverAuthority: 'wallet_account_cached_balance',
    idempotency: 'client_idempotency_key',
  },
  {
    source: 'user_gift_transfer_receive',
    direction: 'credit',
    ledgerType: 'user_gift_receive',
    serverAuthority: 'paired_server_transfer',
    idempotency: 'client_idempotency_key',
  },
  {
    source: 'chat_feature_generation_refund',
    direction: 'credit',
    ledgerType: 'refund',
    serverAuthority: 'server_failure_reversal',
    idempotency: 'server_order_refund_key',
  },
  {
    source: 'admin_wallet_adjustment',
    direction: 'credit_or_debit',
    ledgerType: 'admin_wallet_adjustment',
    serverAuthority: 'super_admin_audited_operation',
    idempotency: 'server_batch_key',
  },
  {
    source: 'local_test_grant',
    direction: 'credit',
    ledgerType: 'event_grant',
    serverAuthority: 'non_production_env_gate_and_server_amount',
    idempotency: 'client_idempotency_key_required',
  },
] as const;

export const WALLET_MUTATION_GUARD_STEPS = {
  debit: [
    'require_idempotency_key_before_wallet_lookup',
    'resolve_price_or_amount_from_server_product_policy_or_validated_transfer_body',
    'fetch_active_wallet_accounts_row',
    'atomic_update_many_cached_balance_gte_amount',
    'write_wallet_ledger_and_domain_record_in_same_transaction',
  ],
  credit: [
    'require_provider_transaction_or_server_idempotency_key',
    'derive_credit_amount_on_server',
    'dedupe_existing_ledger_or_provider_transaction',
    'increment_cached_balance_and_write_wallet_ledger_in_same_transaction',
  ],
  failClosed: [
    'insufficient_balance_creates_no_wallet_ledger',
    'idempotency_mismatch_creates_no_wallet_mutation',
    'provider_replay_creates_no_duplicate_credit',
  ],
} as const;

export const WALLET_LEDGER_INVARIANT_CONTRACT = {
  version: '2026-06-08.wallet-ledger-invariant.v1',
  globalInvariants: {
    clientEconomicFieldsTrusted: false,
    walletMutationRequiresLedger: true,
    ledgerRequiresIdempotencyOrProviderTransaction: true,
    walletAndLedgerSameTransaction: true,
    debitRequiresAtomicNonNegativeBalanceUpdate: true,
    failedValidationCreatesLedger: false,
    settlementOrPayoutFromClientInput: false,
  },
  surfaces: [
    {
      surface: 'charge_purchase_credit',
      direction: 'credit',
      amountAuthority: 'server_active_charge_product_and_verified_provider_event',
      duplicateGuard: 'provider_transaction_id_unique',
      packageBonus: 'included_in_purchase_credit_ledger',
      firstChargeBonus: 'separate_user_once_first_charge_bonus_ledger',
      clientSubmittedAmountTrusted: false,
      failedProviderEventCreatesLedger: false,
      settlementMutation: false,
      payoutMutation: false,
    },
    {
      surface: 'first_charge_bonus',
      direction: 'credit',
      amountAuthority: 'server_10_percent_of_base_lumina',
      duplicateGuard: 'first_charge_bonus_user_idempotency_key',
      packageBonusIncluded: false,
      clientSubmittedAmountTrusted: false,
      failedProviderEventCreatesLedger: false,
      settlementMutation: false,
      payoutMutation: false,
    },
    {
      surface: 'premium_chat_donation',
      direction: 'debit',
      amountAuthority: 'server_normalized_donation_amount',
      duplicateGuard: 'premium_chat_donation_idempotency_key',
      negativeBalanceGuard: 'atomic_cached_balance_gte_amount_update',
      clientSubmittedAmountTrusted: false,
      insufficientBalanceCreatesLedger: false,
      settlementMutation: false,
      payoutMutation: false,
    },
    {
      surface: 'premium_chat_refund_restriction',
      direction: 'credit',
      amountAuthority: 'server_admin_or_moderation_refund_policy',
      duplicateGuard: 'server_admin_decision_key',
      existingLedgerRequired: true,
      clientSubmittedRefundRateTrusted: false,
      settlementMutation: false,
      payoutMutation: false,
    },
  ],
} as const;

export const WALLET_SERVER_ONLY_SPEND_GUARD_CONTRACT = {
  version: '2026-06-08.wallet-server-only-spend-guard.v1',
  clientDisplayedBalanceTrusted: false,
  clientSubmittedLedgerIdTrusted: false,
  clientSubmittedCachedBalanceTrusted: false,
  spendRequiresServerWalletAccount: true,
  spendRequiresServerLedgerWrite: true,
  spendRequiresAtomicBalanceGuard: true,
  missingLedgerMeansSpendImpossible: true,
  blackMarketOrModifiedAppDisplayValueIgnored: true,
  insufficientBalanceCreatesDomainRecord: false,
  insufficientBalanceCreatesLedger: false,
  spendSurfaces: [
    'gift_order',
    'boost_paid_like',
    'premium_video_unlock',
    'chat_feature_order',
    'premium_chat_room_open',
    'premium_chat_message',
    'premium_chat_donation',
    'fan_letter',
    'user_gift_transfer_send',
  ],
  requiredServerSources: [
    'wallet_accounts.cached_balance',
    'wallet_ledger.idempotency_key',
    'server_product_or_domain_policy_amount',
  ],
} as const;

export const APP_WEB_LUMINA_TAMPER_DEFENSE_CHECKLIST = [
  {
    surface: 'wallet_balance',
    endpoints: ['GET /api/v1/wallet', 'GET /api/v1/me/summary'],
    mutation: false,
    clientEconomicFieldsTrusted: false,
    authority: ['wallet_accounts.cached_balance'],
    idempotencyOrProviderTransactionKey: 'not_applicable_read_only',
    doubleDebitGuard: 'not_applicable_read_only',
  },
  {
    surface: 'paid_like_boost',
    endpoints: [
      'POST /api/v1/boost-campaigns/:campaignId/like',
      'POST /api/v1/boost-campaigns/:campaignId/boost',
    ],
    mutation: true,
    clientEconomicFieldsTrusted: false,
    rejectedOrIgnoredFields: CLIENT_ECONOMIC_TAMPER_FIELDS,
    authority: ['server boost product/campaign price', 'wallet_accounts.cached_balance'],
    idempotencyOrProviderTransactionKey: 'client_idempotency_key',
    doubleDebitGuard: 'wallet conditional update and boost event idempotency',
  },
  {
    surface: 'chat_feature_product',
    endpoints: ['POST /api/v1/chat-feature-orders'],
    mutation: true,
    clientEconomicFieldsTrusted: false,
    rejectedOrIgnoredFields: CLIENT_ECONOMIC_TAMPER_FIELDS,
    authority: ['chat_feature_products.price_lumina', 'wallet_accounts.cached_balance'],
    idempotencyOrProviderTransactionKey: 'client_idempotency_key',
    doubleDebitGuard: 'chat_feature_orders.idempotency_key and wallet ledger key',
  },
  {
    surface: 'premium_chat_room_and_support',
    endpoints: [
      'POST /api/v1/chat/premium-rooms',
      'POST /api/v1/chat/sessions/:sessionId/donations',
    ],
    mutation: false,
    clientEconomicFieldsTrusted: false,
    rejectedOrIgnoredFields: CLIENT_ECONOMIC_TAMPER_FIELDS,
    authority: ['server premium chat room/support policy', 'wallet_accounts.cached_balance'],
    idempotencyOrProviderTransactionKey: 'client_idempotency_key_required_when_enabled',
    doubleDebitGuard:
      'mutation_blocked_until_room_or_donation_storage_exists_then_idempotency_fingerprint_and_atomic_cached_balance_gte_amount',
  },
  {
    surface: 'premium_video_unlock',
    endpoints: ['POST /api/v1/premium-videos/:productId/unlock'],
    mutation: true,
    clientEconomicFieldsTrusted: false,
    rejectedOrIgnoredFields: CLIENT_ECONOMIC_TAMPER_FIELDS,
    authority: ['premium_video_products.price_lumina', 'wallet_accounts.cached_balance'],
    idempotencyOrProviderTransactionKey: 'client_idempotency_key',
    doubleDebitGuard: 'user unlock uniqueness and wallet ledger key',
  },
  {
    surface: 'donation_gift_fan_letter_user_gift',
    endpoints: [
      'POST /api/v1/gifts/orders',
      'POST /api/v1/fan-letters',
      'POST /api/v1/user-gifts/transfers',
    ],
    mutation: true,
    clientEconomicFieldsTrusted: false,
    rejectedOrIgnoredFields: CLIENT_ECONOMIC_TAMPER_FIELDS,
    authority: ['server product/transfer policy', 'wallet_accounts.cached_balance'],
    idempotencyOrProviderTransactionKey: 'client_idempotency_key',
    doubleDebitGuard: 'domain idempotency key and wallet conditional update',
  },
  {
    surface: 'charge_purchase_credit',
    endpoints: [
      'POST /api/v1/payments/orders',
      'POST /api/v1/payments/webhooks/:provider',
    ],
    mutation: true,
    clientEconomicFieldsTrusted: false,
    rejectedOrIgnoredFields: CLIENT_ECONOMIC_TAMPER_FIELDS,
    authority: ['server product table', 'provider verified transaction'],
    idempotencyOrProviderTransactionKey: 'provider_transaction_id',
    doubleDebitGuard:
      'payment order status transition, provider transaction dedupe, and sanitized webhook audit payload',
  },
  {
    surface: 'refund_reversal',
    endpoints: ['provider refund tracking', 'server technical failure reversal'],
    mutation: true,
    clientEconomicFieldsTrusted: false,
    rejectedOrIgnoredFields: CLIENT_ECONOMIC_TAMPER_FIELDS,
    authority: ['server refund policy', 'existing wallet ledger/order state'],
    idempotencyOrProviderTransactionKey: 'server_refund_key',
    doubleDebitGuard: 'refund ledger idempotency key',
  },
] as const;

export const APP_PURCHASE_VERIFICATION_CONTRACT = [
  {
    platform: 'google_play',
    purchaseProof: 'purchase_token',
    serverVerification: 'google_play_developer_api',
    integritySignal: 'play_integrity_api',
    integritySignalRequiredForLedgerCredit: false,
    rawProofLogged: false,
  },
  {
    platform: 'apple_app_store',
    purchaseProof: 'signed_transaction_or_app_store_server_api_payload',
    serverVerification: 'app_store_server_api_or_signed_transaction_validation',
    integritySignal: 'app_attest_or_device_check',
    integritySignalRequiredForLedgerCredit: false,
    rawProofLogged: false,
  },
] as const;
