export const SERVER_AUTHORITY_WALLET_POLICY = {
  policyVersion: '2026-05-20.server-authority-ledger',
  clientSubmittedBalanceTrusted: false,
  clientSubmittedPriceTrusted: false,
  clientSubmittedSettlementTrusted: false,
  offlinePaidActionAllowed: false,
  allWalletDebitsRequireServerLedgerBalanceCheck: true,
  allWalletDebitsRequireAtomicNonNegativeUpdate: true,
  allWalletMutationsRequireIdempotencyOrProviderTransactionKey: true,
  purchaseCreditsRequireProviderVerification: true,
  appIntegrityIsAdvisoryOnly: true,
  rawPurchaseTokensLogged: false,
} as const;

export const WALLET_LEDGER_SOURCE_CONTRACT = [
  {
    source: 'payment_purchase_credit',
    direction: 'credit',
    ledgerType: 'purchase',
    serverAuthority: 'provider_verified_purchase',
    idempotency: 'provider_transaction_id',
  },
  {
    source: 'first_charge_bonus',
    direction: 'credit',
    ledgerType: 'first_charge_bonus',
    serverAuthority: 'server_derived_bonus',
    idempotency: 'user_once_key',
  },
  {
    source: 'gift_order',
    direction: 'debit',
    ledgerType: 'gift_spend',
    serverAuthority: 'wallet_account_cached_balance',
    idempotency: 'client_idempotency_key',
  },
  {
    source: 'boost_paid_like',
    direction: 'debit',
    ledgerType: 'boost_spend',
    serverAuthority: 'wallet_account_cached_balance',
    idempotency: 'client_idempotency_key',
  },
  {
    source: 'premium_video_unlock',
    direction: 'debit',
    ledgerType: 'premium_video_spend',
    serverAuthority: 'wallet_account_cached_balance',
    idempotency: 'client_idempotency_key',
  },
  {
    source: 'chat_feature_order',
    direction: 'debit',
    ledgerType: 'chat_feature_spend',
    serverAuthority: 'wallet_account_cached_balance',
    idempotency: 'client_idempotency_key',
  },
  {
    source: 'premium_chat_donation',
    direction: 'debit',
    ledgerType: 'premium_chat_donation',
    serverAuthority: 'wallet_account_cached_balance',
    idempotency: 'client_idempotency_key',
  },
  {
    source: 'fan_letter',
    direction: 'debit',
    ledgerType: 'fan_letter_spend',
    serverAuthority: 'wallet_account_cached_balance',
    idempotency: 'client_idempotency_key',
  },
  {
    source: 'user_gift_transfer_send',
    direction: 'debit',
    ledgerType: 'user_gift_send',
    serverAuthority: 'wallet_account_cached_balance',
    idempotency: 'client_idempotency_key',
  },
  {
    source: 'user_gift_transfer_receive',
    direction: 'credit',
    ledgerType: 'user_gift_receive',
    serverAuthority: 'paired_server_transfer',
    idempotency: 'client_idempotency_key',
  },
  {
    source: 'chat_feature_generation_refund',
    direction: 'credit',
    ledgerType: 'refund',
    serverAuthority: 'server_failure_reversal',
    idempotency: 'server_order_refund_key',
  },
  {
    source: 'admin_wallet_adjustment',
    direction: 'credit_or_debit',
    ledgerType: 'admin_wallet_adjustment',
    serverAuthority: 'super_admin_audited_operation',
    idempotency: 'server_batch_key',
  },
] as const;

export const APP_PURCHASE_VERIFICATION_CONTRACT = [
  {
    platform: 'google_play',
    purchaseProof: 'purchase_token',
    serverVerification: 'google_play_developer_api',
    integritySignal: 'play_integrity_api',
    integritySignalRequiredForLedgerCredit: false,
    rawProofLogged: false,
  },
  {
    platform: 'apple_app_store',
    purchaseProof: 'signed_transaction_or_app_store_server_api_payload',
    serverVerification: 'app_store_server_api_or_signed_transaction_validation',
    integritySignal: 'app_attest_or_device_check',
    integritySignalRequiredForLedgerCredit: false,
    rawProofLogged: false,
  },
] as const;
